// Gujarat — YojanaSetu State Schemes
// ─────────────────────────────────────────────────────────────────────────────
// HOW TO ADD A NEW SCHEME:
//   1. Copy any block below, paste it above the closing ];
//   2. Give it a unique id like "gujarat_new_scheme"
//   3. Update name, benefit, docs, match() and save.
//   No other file needs to change.
// ─────────────────────────────────────────────────────────────────────────────

export const GUJARAT_SCHEMES = [

  {
    id: "gujarat_amrutum",
    icon: "🏥", color: "#0891B2", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Health & Family Welfare", hi: "गुजरात स्वास्थ्य विभाग" },
    name:    { en: "Mukhyamantri Amrutum Yojana (Guj.)", hi: "मुख्यमंत्री अमृतम योजना (गुजरात)" },
    benefit: { en: "₹5 Lakh/year free medical treatment", hi: "₹5 लाख/वर्ष मुफ्त चिकित्सा" },
    tag:     { en: "Health", hi: "स्वास्थ्य" },
    annual: 500000,
    apply:   { en: "health.gujarat.gov.in", hi: "health.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Ration Card","Income Certificate"],
               hi: ["आधार कार्ड","राशन कार्ड","आय प्रमाण"] },
    match: (a) => a.state === "Gujarat" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "gujarat_manav_garima",
    icon: "🧰", color: "#D97706", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Social Justice & Empowerment Dept.", hi: "गुजरात सामाजिक न्याय एवं अधिकारिता विभाग" },
    name:    { en: "Manav Garima Yojana (Gujarat)",                   hi: "मानव गरिमा योजना (गुजरात)" },
    benefit: { en: "Free toolkit worth ₹4,000 for SC artisans to start self-employment", hi: "SC कारीगरों को स्वरोजगार के लिए ₹4,000 मूल्य का मुफ्त टूलकिट" },
    tag:     { en: "Business / SC", hi: "व्यापार / SC" },
    annual: 4000,
    apply:   { en: "esamajkalyan.gujarat.gov.in", hi: "esamajkalyan.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Caste Certificate (SC)","Income Certificate (below ₹1.20L)","Domicile Certificate","Photo"],
               hi: ["आधार कार्ड","जाति प्रमाण पत्र (SC)","आय प्रमाण (₹1.20 लाख से कम)","अधिवास प्रमाण","फोटो"] },
    match: (a) => a.state === "Gujarat" && a.who === "business" && ["below1"].includes(a.income),
  },

  {
    id: "gujarat_kisan_sahay",
    icon: "🌱", color: "#16A34A", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Agriculture & Co-operation Dept.", hi: "गुजरात कृषि और सहकारिता विभाग" },
    name:    { en: "Mukhyamantri Kisan Sahay Yojana (Gujarat)",       hi: "मुख्यमंत्री किसान सहाय योजना (गुजरात)" },
    benefit: { en: "₹20,000/ha for 33–60% crop loss · ₹25,000/ha for >60% loss · Up to 4 ha", hi: "33–60% फसल नुकसान पर ₹20,000/हेक्टेयर · 60% से अधिक नुकसान पर ₹25,000/हेक्टेयर · अधिकतम 4 हेक्टेयर" },
    tag:     { en: "Farmer", hi: "किसान" },
    annual: 80000,
    apply:   { en: "ikhedut.gujarat.gov.in", hi: "ikhedut.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Land Records (7/12 Utara)", "Bank Passbook", "Crop Sowing Certificate", "Photo"],
               hi: ["आधार कार्ड", "जमीन के कागज़ (7/12 उतारा)", "बैंक पासबुक", "फसल बुवाई प्रमाण", "फोटो"] },
    match: (a) => a.state === "Gujarat" && a.who === "farmer",
  },

  {
    id: "gujarat_ikhedut",
    icon: "🚜", color: "#15803D", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Agriculture & Co-operation Dept.", hi: "गुजरात कृषि और सहकारिता विभाग" },
    name:    { en: "i-Khedut Portal – Farm Equipment & Input Subsidy", hi: "आई-खेडूत पोर्टल – कृषि यंत्र एवं इनपुट सब्सिडी" },
    benefit: { en: "25–50% subsidy on tractors, tools, seeds & irrigation equipment", hi: "ट्रेक्टर, औज़ार, बीज व सिंचाई उपकरण पर 25–50% सब्सिडी" },
    tag:     { en: "Farmer", hi: "किसान" },
    annual: 50000,
    apply:   { en: "ikhedut.gujarat.gov.in", hi: "ikhedut.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Land Records (7/12 Utara)", "Bank Passbook", "Caste Certificate (if SC/ST)", "Photo"],
               hi: ["आधार कार्ड", "जमीन के कागज़ (7/12 उतारा)", "बैंक पासबुक", "जाति प्रमाण (SC/ST के लिए)", "फोटो"] },
    match: (a) => a.state === "Gujarat" && a.who === "farmer",
  },

  {
    id: "gujarat_vhali_dikri",
    icon: "👧", color: "#EC4899", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Women & Child Development Dept.", hi: "गुजरात महिला एवं बाल विकास विभाग" },
    name:    { en: "Vhali Dikri Yojana (Gujarat)",                    hi: "वहाली दीकरी योजना (गुजरात)" },
    benefit: { en: "₹4,000 at birth · ₹6,000 at Class 1 · ₹10,000 at Class 9 · ₹1 Lakh at age 18", hi: "जन्म पर ₹4,000 · कक्षा 1 में ₹6,000 · कक्षा 9 में ₹10,000 · 18 वर्ष पर ₹1 लाख" },
    tag:     { en: "Girl Child / Women", hi: "बालिका / महिला" },
    annual: 4000,
    apply:   { en: "wcd.gujarat.gov.in", hi: "wcd.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card (Parent)", "Girl Child's Birth Certificate", "Income Certificate (below ₹2L)", "Bank Account (Parent)", "Ration Card"],
               hi: ["आधार कार्ड (माता-पिता)", "बालिका का जन्म प्रमाण पत्र", "आय प्रमाण (₹2 लाख से कम)", "बैंक खाता (माता-पिता)", "राशन कार्ड"] },
    match: (a) => a.state === "Gujarat" && a.who === "women" && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "gujarat_namo_lakshmi",
    icon: "🎓", color: "#DB2777", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Education Dept.", hi: "गुजरात शिक्षा विभाग" },
    name:    { en: "Namo Lakshmi Yojana (Gujarat)",                   hi: "नमो लक्ष्मी योजना (गुजरात)" },
    benefit: { en: "₹10,000/year (Class 9–10) · ₹15,000/year (Class 11–12) · Total ₹50,000 for girl students", hi: "कक्षा 9–10 में ₹10,000/वर्ष · कक्षा 11–12 में ₹15,000/वर्ष · कुल ₹50,000 बालिका छात्राओं को" },
    tag:     { en: "Student / Girl", hi: "छात्र / बालिका" },
    annual: 15000,
    apply:   { en: "sebexam.org", hi: "sebexam.org" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "School Enrollment Certificate", "Income Certificate (below ₹6L)", "Bank Account", "Caste Certificate (if applicable)", "Passport Photo"],
               hi: ["आधार कार्ड", "स्कूल नामांकन प्रमाण", "आय प्रमाण (₹6 लाख से कम)", "बैंक खाता", "जाति प्रमाण (यदि लागू हो)", "पासपोर्ट फोटो"] },
    match: (a) => a.state === "Gujarat" && a.who === "student" && ["below1", "1to3", "3to6"].includes(a.income),
  },

  {
    id: "gujarat_mahila_utkarsh",
    icon: "👩‍💼", color: "#9D174D", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Finance Dept. / SEWA Bank", hi: "गुजरात वित्त विभाग / सेवा बैंक" },
    name:    { en: "Mukhyamantri Mahila Utkarsh Yojana (Gujarat)",    hi: "मुख्यमंत्री महिला उत्कर्ष योजना (गुजरात)" },
    benefit: { en: "Interest-free loan up to ₹1 Lakh for women SHGs (SWAMIH / SHRI groups)", hi: "महिला स्वयं सहायता समूहों (SWAMIH/SHRI) को ₹1 लाख तक ब्याज मुक्त ऋण" },
    tag:     { en: "Women / SHG", hi: "महिला / SHG" },
    annual: 0,
    apply:   { en: "mmuy.gujarat.gov.in", hi: "mmuy.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "SHG Registration Certificate", "Bank Account (Group)", "Income Certificate", "Ration Card"],
               hi: ["आधार कार्ड", "SHG पंजीकरण प्रमाण पत्र", "बैंक खाता (समूह)", "आय प्रमाण", "राशन कार्ड"] },
    match: (a) => a.state === "Gujarat" && a.who === "women" && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "gujarat_chiranjeevi",
    icon: "🤱", color: "#BE185D", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Health & Family Welfare Dept.", hi: "गुजरात स्वास्थ्य एवं परिवार कल्याण विभाग" },
    name:    { en: "Chiranjivi Yojana (Gujarat)",                      hi: "चिरंजीवी योजना (गुजरात)" },
    benefit: { en: "Free delivery at empanelled hospitals + ₹1,400 for transport & nutrition for BPL mothers", hi: "BPL माताओं को सूचीबद्ध अस्पतालों में मुफ्त प्रसव + ₹1,400 परिवहन व पोषण सहायता" },
    tag:     { en: "Women / Maternity", hi: "महिला / मातृत्व" },
    annual: 1400,
    apply:   { en: "108.gov.in / nearest PHC", hi: "108.gov.in / नज़दीकी PHC" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "BPL / Ration Card", "Pregnancy Registration (MCP Card)", "Bank Account"],
               hi: ["आधार कार्ड", "BPL / राशन कार्ड", "गर्भावस्था पंजीकरण (MCP कार्ड)", "बैंक खाता"] },
    match: (a) => a.state === "Gujarat" && a.who === "women" && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "gujarat_ganga_swarupa",
    icon: "👩‍🦳", color: "#7E22CE", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Social Justice & Empowerment Dept.", hi: "गुजरात सामाजिक न्याय एवं अधिकारिता विभाग" },
    name:    { en: "Ganga Swarupa Yojana – Widow Pension (Gujarat)",  hi: "गंगा स्वरूपा योजना – विधवा पेंशन (गुजरात)" },
    benefit: { en: "₹1,250/month pension for widows with no fixed income source", hi: "बिना निश्चित आय स्रोत वाली विधवाओं को ₹1,250/माह पेंशन" },
    tag:     { en: "Women / Widow", hi: "महिला / विधवा" },
    annual: 15000,
    apply:   { en: "esamajkalyan.gujarat.gov.in", hi: "esamajkalyan.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Husband's Death Certificate", "Age Proof", "Income Certificate (no fixed income)", "Bank Account", "Domicile Certificate"],
               hi: ["आधार कार्ड", "पति का मृत्यु प्रमाण पत्र", "आयु प्रमाण", "आय प्रमाण (कोई निश्चित आय नहीं)", "बैंक खाता", "अधिवास प्रमाण"] },
    match: (a) => a.state === "Gujarat" && a.who === "women" && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "gujarat_vriddha_sahay",
    icon: "👴", color: "#B45309", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Social Justice & Empowerment Dept.", hi: "गुजरात सामाजिक न्याय एवं अधिकारिता विभाग" },
    name:    { en: "Vriddha Sahay Pension Yojana (Gujarat)",          hi: "वृद्ध सहाय पेंशन योजना (गुजरात)" },
    benefit: { en: "₹1,000/month pension for destitute senior citizens aged 60+", hi: "60+ वर्ष के निराश्रित वरिष्ठ नागरिकों को ₹1,000/माह पेंशन" },
    tag:     { en: "Senior / Pension", hi: "वरिष्ठ / पेंशन" },
    annual: 12000,
    apply:   { en: "esamajkalyan.gujarat.gov.in", hi: "esamajkalyan.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Age Proof (60+)", "Income Certificate", "Domicile Certificate", "Bank Account", "Photo"],
               hi: ["आधार कार्ड", "आयु प्रमाण (60+)", "आय प्रमाण", "अधिवास प्रमाण", "बैंक खाता", "फोटो"] },
    match: (a) => a.state === "Gujarat" && (a.who === "senior" || a.age === "above60") && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "gujarat_pandit_dindayal_awas",
    icon: "🏡", color: "#92400E", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Rural Housing Dept. (DRDA)", hi: "गुजरात ग्रामीण आवास विभाग (DRDA)" },
    name:    { en: "Pandit Dindayal Upadhyay Awas Yojana (Gujarat)", hi: "पंडित दीनदयाल उपाध्याय आवास योजना (गुजरात)" },
    benefit: { en: "₹1.20–₹1.50 Lakh for BPL rural families to build a pucca house", hi: "BPL ग्रामीण परिवारों को पक्का मकान बनाने के लिए ₹1.20–₹1.50 लाख सहायता" },
    tag:     { en: "Housing / Rural", hi: "आवास / ग्रामीण" },
    annual: 150000,
    apply:   { en: "gramnirman.gujarat.gov.in", hi: "gramnirman.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "BPL Certificate", "Land / Plot Ownership Proof", "No-House Certificate", "Bank Account", "Passport Photo"],
               hi: ["आधार कार्ड", "BPL प्रमाण पत्र", "जमीन/प्लॉट स्वामित्व प्रमाण", "मकान न होने का प्रमाण", "बैंक खाता", "पासपोर्ट फोटो"] },
    match: (a) => a.state === "Gujarat" && a.area === "rural" && ["no", "kutcha"].includes(a.house) && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "gujarat_dr_ambedkar_awas",
    icon: "🏠", color: "#1E40AF", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Scheduled Caste Development Corporation", hi: "गुजरात अनुसूचित जाति विकास निगम" },
    name:    { en: "Dr. Ambedkar Awas Yojana (Gujarat)",             hi: "डॉ. अंबेडकर आवास योजना (गुजरात)" },
    benefit: { en: "₹1.20 Lakh for SC families to construct a pucca house (rural)", hi: "SC परिवारों को ग्रामीण क्षेत्र में पक्का मकान बनाने हेतु ₹1.20 लाख सहायता" },
    tag:     { en: "Housing / SC", hi: "आवास / SC" },
    annual: 120000,
    apply:   { en: "sje.gujarat.gov.in", hi: "sje.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Caste Certificate (SC)", "Income Certificate (below ₹1.20L)", "Land Ownership Proof", "No-House Certificate", "Bank Account"],
               hi: ["आधार कार्ड", "जाति प्रमाण पत्र (SC)", "आय प्रमाण (₹1.20 लाख से कम)", "भूमि स्वामित्व प्रमाण", "मकान न होने का प्रमाण", "बैंक खाता"] },
    match: (a) => a.state === "Gujarat" && ["no", "kutcha"].includes(a.house) && a.income === "below1",
  },

  {
    id: "gujarat_namo_saraswati",
    icon: "🔬", color: "#0284C7", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Education Dept.", hi: "गुजरात शिक्षा विभाग" },
    name:    { en: "Namo Saraswati Vigyan Sadhana Yojana (Gujarat)", hi: "नमो सरस्वती विज्ञान साधना योजना (गुजरात)" },
    benefit: { en: "₹25,000/year scholarship for girl students in Science stream (Class 11–12)", hi: "विज्ञान प्रवाह (कक्षा 11–12) की बालिका छात्राओं को ₹25,000/वर्ष छात्रवृत्ति" },
    tag:     { en: "Student / Science", hi: "छात्र / विज्ञान" },
    annual: 25000,
    apply:   { en: "sebexam.org", hi: "sebexam.org" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Enrollment in Science Stream (Class 11 / 12)", "Income Certificate (below ₹6L)", "Bank Account", "Passport Photo"],
               hi: ["आधार कार्ड", "विज्ञान प्रवाह में नामांकन (कक्षा 11/12)", "आय प्रमाण (₹6 लाख से कम)", "बैंक खाता", "पासपोर्ट फोटो"] },
    match: (a) => a.state === "Gujarat" && a.who === "student" && ["below1", "1to3", "3to6"].includes(a.income),
  },

  {
    id: "gujarat_postmatric_sc",
    icon: "📖", color: "#6D28D9", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Social Justice & Empowerment Dept.", hi: "गुजरात सामाजिक न्याय एवं अधिकारिता विभाग" },
    name:    { en: "Post-Matric Scholarship SC / ST / OBC (Gujarat)", hi: "पोस्ट-मैट्रिक छात्रवृत्ति SC/ST/OBC (गुजरात)" },
    benefit: { en: "Tuition fee waiver + maintenance allowance ₹5,000–₹18,000/year for higher studies", hi: "उच्च शिक्षा हेतु ट्यूशन फीस माफी + ₹5,000–₹18,000/वर्ष रखरखाव भत्ता" },
    tag:     { en: "Student / SC OBC", hi: "छात्र / SC OBC" },
    annual: 18000,
    apply:   { en: "esamajkalyan.gujarat.gov.in", hi: "esamajkalyan.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Caste Certificate (SC / ST / OBC)", "Previous Year Mark Sheets", "Income Certificate (below ₹2.5L)", "Bonafide Certificate from Institution", "Bank Account"],
               hi: ["आधार कार्ड", "जाति प्रमाण पत्र (SC/ST/OBC)", "पिछले वर्ष की मार्कशीट", "आय प्रमाण (₹2.5 लाख से कम)", "संस्थान से बोनाफाइड प्रमाण पत्र", "बैंक खाता"] },
    match: (a) => a.state === "Gujarat" && a.who === "student" && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "gujarat_saat_fer",
    icon: "💍", color: "#9D174D", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Social Justice & Empowerment Dept.", hi: "गुजरात सामाजिक न्याय एवं अधिकारिता विभाग" },
    name:    { en: "Mukhyamantri Saat Fera Samuh Lagna Yojana (Gujarat)", hi: "मुख्यमंत्री सात फेरा सामूहिक विवाह योजना (गुजरात)" },
    benefit: { en: "₹12,000 of household gifts per couple + ₹10,000 cash to the bride at mass community weddings", hi: "सामूहिक विवाह में प्रति जोड़े को ₹12,000 के गृह उपकरण + दुल्हन को ₹10,000 नकद" },
    tag:     { en: "Women / Marriage", hi: "महिला / विवाह" },
    annual: 22000,
    apply:   { en: "sje.gujarat.gov.in", hi: "sje.gujarat.gov.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card (Both)", "Age Proof (Bride 18+, Groom 21+)", "Income Certificate", "Caste Certificate (if applicable)", "Passport Photos"],
               hi: ["आधार कार्ड (दोनों)", "आयु प्रमाण (दुल्हन 18+, दूल्हा 21+)", "आय प्रमाण", "जाति प्रमाण (यदि लागू)", "पासपोर्ट फोटो"] },
    match: (a) => a.state === "Gujarat" && a.who === "women" && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "gujarat_swavlamban",
    icon: "♿", color: "#0F766E", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Social Justice & Empowerment Dept.", hi: "गुजरात सामाजिक न्याय एवं अधिकारिता विभाग" },
    name:    { en: "Swavlamban – Divyang Sahay & Pension Yojana (Gujarat)", hi: "स्वावलंबन – दिव्यांग सहाय एवं पेंशन योजना (गुजरात)" },
    benefit: { en: "₹1,000/month pension + free assistive devices (wheelchair, hearing aid, etc.) for persons with disability (40%+)", hi: "₹1,000/माह पेंशन + मुफ्त सहायक उपकरण (व्हीलचेयर, श्रवण यंत्र आदि) 40%+ दिव्यांगजनों को" },
    tag:     { en: "Disability / Pension", hi: "दिव्यांग / पेंशन" },
    annual: 12000,
    apply:   { en: "esamajkalyan.gujarat.gov.in", hi: "esamajkalyan.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Disability Certificate (40%+ disability from Govt. Hospital)", "Income Certificate", "Domicile Certificate", "Bank Account", "Photo"],
               hi: ["आधार कार्ड", "विकलांगता प्रमाण पत्र (सरकारी अस्पताल से 40%+)", "आय प्रमाण", "अधिवास प्रमाण", "बैंक खाता", "फोटो"] },
    match: (a) => a.state === "Gujarat" && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "gujarat_gruha_jyoti",
    icon: "💡", color: "#CA8A04", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Energy Dept. / GEBCOs (DISCOMs)", hi: "गुजरात ऊर्जा विभाग / GEBCOs (DISCOMs)" },
    name:    { en: "Indira Gandhi Gruha Jyoti Yojana (Gujarat)",     hi: "इंदिरा गांधी गृह ज्योति योजना (गुजरात)" },
    benefit: { en: "Free electricity up to 100 units/month for BPL households; subsidised tariff for 101–200 units", hi: "BPL परिवारों को 100 यूनिट/माह तक मुफ्त बिजली; 101–200 यूनिट पर रियायती दर" },
    tag:     { en: "Energy / BPL", hi: "ऊर्जा / BPL" },
    annual: 6000,
    apply:   { en: "pgvcl.com / local DISCOM office", hi: "pgvcl.com / स्थानीय DISCOM कार्यालय" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "BPL / Ration Card", "Electricity Consumer Number", "Bank Account"],
               hi: ["आधार कार्ड", "BPL / राशन कार्ड", "बिजली उपभोक्ता संख्या", "बैंक खाता"] },
    match: (a) => a.state === "Gujarat" && a.income === "below1",
  },

  {
    id: "gujarat_mukhyamantri_apprentice",
    icon: "🛠️", color: "#1D4ED8", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Labour & Employment Dept.", hi: "गुजरात श्रम एवं रोजगार विभाग" },
    name:    { en: "Mukhyamantri Apprenticeship Scheme – MMAS (Gujarat)", hi: "मुख्यमंत्री अप्रेंटिसशिप योजना – MMAS (गुजरात)" },
    benefit: { en: "₹3,000/month stipend for 1 year during industry apprenticeship + placement support", hi: "उद्योग प्रशिक्षुता के दौरान 1 वर्ष तक ₹3,000/माह वजीफा + नौकरी सहायता" },
    tag:     { en: "Skill / Youth", hi: "कौशल / युवा" },
    annual: 36000,
    apply:   { en: "nats.education.gov.in", hi: "nats.education.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Educational Certificate (10th / ITI / Diploma / Degree)", "Bank Account", "Passport Photo"],
               hi: ["आधार कार्ड", "शैक्षणिक प्रमाण (10वीं / ITI / डिप्लोमा / डिग्री)", "बैंक खाता", "पासपोर्ट फोटो"] },
    match: (a) => a.state === "Gujarat" && a.age === "18to35" && ["below1", "1to3", "3to6"].includes(a.income),
  },

  // ADD MORE GUJARAT SCHEMES ABOVE THIS LINE ↓
  // {
  //   id: "gujarat_new_scheme",
  //   icon: "🆕", color: "#123456", scope: "state", state: "Gujarat",
  //   ministry: { en: "Dept. Name", hi: "विभाग का नाम" },
  //   name:    { en: "Scheme Name", hi: "योजना का नाम" },
  //   benefit: { en: "Benefit details", hi: "लाभ विवरण" },
  //   tag:     { en: "Tag", hi: "टैग" },
  //   annual: 0,
  //   apply:   { en: "website.gov.in", hi: "website.gov.in" }, applyType: "online",
  //   docs:    { en: ["Aadhaar Card"], hi: ["आधार कार्ड"] },
  //   match: (a) => a.state === "Gujarat",
  // },

];
