// Gujarat — YojanaSetu State Schemes
// ─────────────────────────────────────────────────────────────────────────────
// HOW TO ADD A NEW SCHEME:
//   1. Copy any block below, paste it above the closing ];
//   2. Give it a unique id like "gujarat_new_scheme"
//   3. Update name, benefit, docs, match() and save.
//   No other file needs to change.
// ─────────────────────────────────────────────────────────────────────────────

export const GUJARAT_SCHEMES = [

  {
    id: "gujarat_amrutum",
    icon: "🏥", color: "#0891B2", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Health & Family Welfare", hi: "गुजरात स्वास्थ्य विभाग" },
    name:    { en: "Mukhyamantri Amrutum Yojana (Guj.)", hi: "मुख्यमंत्री अमृतम योजना (गुजरात)" },
    benefit: { en: "₹5 Lakh/year free medical treatment", hi: "₹5 लाख/वर्ष मुफ्त चिकित्सा" },
    tag:     { en: "Health", hi: "स्वास्थ्य" },
    annual: 500000,
    apply:   { en: "https://health.gujarat.gov.in", hi: "health.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Ration Card","Income Certificate"],
               hi: ["आधार कार्ड","राशन कार्ड","आय प्रमाण"] },
    match: (a) => a.state === "Gujarat" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "gujarat_manav_garima",
    icon: "🧰", color: "#D97706", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Social Justice & Empowerment Dept.", hi: "गुजरात सामाजिक न्याय एवं अधिकारिता विभाग" },
    name:    { en: "Manav Garima Yojana (Gujarat)",                   hi: "मानव गरिमा योजना (गुजरात)" },
    benefit: { en: "Free toolkit worth ₹4,000 for SC artisans to start self-employment", hi: "SC कारीगरों को स्वरोजगार के लिए ₹4,000 मूल्य का मुफ्त टूलकिट" },
    tag:     { en: "Business / SC", hi: "व्यापार / SC" },
    annual: 4000,
    apply:   { en: "https://esamajkalyan.gujarat.gov.in", hi: "esamajkalyan.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Caste Certificate (SC)","Income Certificate (below ₹1.20L)","Domicile Certificate","Photo"],
               hi: ["आधार कार्ड","जाति प्रमाण पत्र (SC)","आय प्रमाण (₹1.20 लाख से कम)","अधिवास प्रमाण","फोटो"] },
    match: (a) => a.state === "Gujarat" && a.who === "business" && ["below1"].includes(a.income),
  },

  {
    id: "gujarat_kisan_sahay",
    icon: "🌱", color: "#16A34A", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Agriculture & Co-operation Dept.", hi: "गुजरात कृषि और सहकारिता विभाग" },
    name:    { en: "Mukhyamantri Kisan Sahay Yojana (Gujarat)",       hi: "मुख्यमंत्री किसान सहाय योजना (गुजरात)" },
    benefit: { en: "₹20,000/ha for 33–60% crop loss · ₹25,000/ha for >60% loss · Up to 4 ha", hi: "33–60% फसल नुकसान पर ₹20,000/हेक्टेयर · 60% से अधिक नुकसान पर ₹25,000/हेक्टेयर · अधिकतम 4 हेक्टेयर" },
    tag:     { en: "Farmer", hi: "किसान" },
    annual: 80000,
    apply:   { en: "https://ikhedut.gujarat.gov.in", hi: "ikhedut.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Land Records (7/12 Utara)", "Bank Passbook", "Crop Sowing Certificate", "Photo"],
               hi: ["आधार कार्ड", "जमीन के कागज़ (7/12 उतारा)", "बैंक पासबुक", "फसल बुवाई प्रमाण", "फोटो"] },
    match: (a) => a.state === "Gujarat" && a.who === "farmer",
  },

  {
    id: "gujarat_ikhedut",
    icon: "🚜", color: "#15803D", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Agriculture & Co-operation Dept.", hi: "गुजरात कृषि और सहकारिता विभाग" },
    name:    { en: "i-Khedut Portal – Farm Equipment & Input Subsidy", hi: "आई-खेडूत पोर्टल – कृषि यंत्र एवं इनपुट सब्सिडी" },
    benefit: { en: "25–50% subsidy on tractors, tools, seeds & irrigation equipment", hi: "ट्रेक्टर, औज़ार, बीज व सिंचाई उपकरण पर 25–50% सब्सिडी" },
    tag:     { en: "Farmer", hi: "किसान" },
    annual: 50000,
    apply:   { en: "https://ikhedut.gujarat.gov.in", hi: "ikhedut.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Land Records (7/12 Utara)", "Bank Passbook", "Caste Certificate (if SC/ST)", "Photo"],
               hi: ["आधार कार्ड", "जमीन के कागज़ (7/12 उतारा)", "बैंक पासबुक", "जाति प्रमाण (SC/ST के लिए)", "फोटो"] },
    match: (a) => a.state === "Gujarat" && a.who === "farmer",
  },

  {
    id: "gujarat_vhali_dikri",
    icon: "👧", color: "#EC4899", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Women & Child Development Dept.", hi: "गुजरात महिला एवं बाल विकास विभाग" },
    name:    { en: "Vhali Dikri Yojana (Gujarat)",                    hi: "वहाली दीकरी योजना (गुजरात)" },
    benefit: { en: "₹4,000 at birth · ₹6,000 at Class 1 · ₹10,000 at Class 9 · ₹1 Lakh at age 18", hi: "जन्म पर ₹4,000 · कक्षा 1 में ₹6,000 · कक्षा 9 में ₹10,000 · 18 वर्ष पर ₹1 लाख" },
    tag:     { en: "Girl Child / Women", hi: "बालिका / महिला" },
    annual: 4000,
    apply:   { en: "https://wcd.gujarat.gov.in", hi: "wcd.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card (Parent)", "Girl Child's Birth Certificate", "Income Certificate (below ₹2L)", "Bank Account (Parent)", "Ration Card"],
               hi: ["आधार कार्ड (माता-पिता)", "बालिका का जन्म प्रमाण पत्र", "आय प्रमाण (₹2 लाख से कम)", "बैंक खाता (माता-पिता)", "राशन कार्ड"] },
    match: (a) => a.state === "Gujarat" && a.who === "women" && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "gujarat_namo_lakshmi",
    icon: "🎓", color: "#DB2777", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Education Dept.", hi: "गुजरात शिक्षा विभाग" },
    name:    { en: "Namo Lakshmi Yojana (Gujarat)",                   hi: "नमो लक्ष्मी योजना (गुजरात)" },
    benefit: { en: "₹10,000/year (Class 9–10) · ₹15,000/year (Class 11–12) · Total ₹50,000 for girl students", hi: "कक्षा 9–10 में ₹10,000/वर्ष · कक्षा 11–12 में ₹15,000/वर्ष · कुल ₹50,000 बालिका छात्राओं को" },
    tag:     { en: "Student / Girl", hi: "छात्र / बालिका" },
    annual: 15000,
    apply:   { en: "https://sebexam.org", hi: "sebexam.org" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "School Enrollment Certificate", "Income Certificate (below ₹6L)", "Bank Account", "Caste Certificate (if applicable)", "Passport Photo"],
               hi: ["आधार कार्ड", "स्कूल नामांकन प्रमाण", "आय प्रमाण (₹6 लाख से कम)", "बैंक खाता", "जाति प्रमाण (यदि लागू हो)", "पासपोर्ट फोटो"] },
    match: (a) => a.state === "Gujarat" && a.who === "student" && ["below1", "1to3", "3to6"].includes(a.income),
  },

  {
    id: "gujarat_mahila_utkarsh",
    icon: "👩‍💼", color: "#9D174D", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Finance Dept. / SEWA Bank", hi: "गुजरात वित्त विभाग / सेवा बैंक" },
    name:    { en: "Mukhyamantri Mahila Utkarsh Yojana (Gujarat)",    hi: "मुख्यमंत्री महिला उत्कर्ष योजना (गुजरात)" },
    benefit: { en: "Interest-free loan up to ₹1 Lakh for women SHGs (SWAMIH / SHRI groups)", hi: "महिला स्वयं सहायता समूहों (SWAMIH/SHRI) को ₹1 लाख तक ब्याज मुक्त ऋण" },
    tag:     { en: "Women / SHG", hi: "महिला / SHG" },
    annual: 0,
    apply:   { en: "https://mmuy.gujarat.gov.in", hi: "mmuy.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "SHG Registration Certificate", "Bank Account (Group)", "Income Certificate", "Ration Card"],
               hi: ["आधार कार्ड", "SHG पंजीकरण प्रमाण पत्र", "बैंक खाता (समूह)", "आय प्रमाण", "राशन कार्ड"] },
    match: (a) => a.state === "Gujarat" && a.who === "women" && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "gujarat_chiranjeevi",
    icon: "🤱", color: "#BE185D", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Health & Family Welfare Dept.", hi: "गुजरात स्वास्थ्य एवं परिवार कल्याण विभाग" },
    name:    { en: "Chiranjivi Yojana (Gujarat)",                      hi: "चिरंजीवी योजना (गुजरात)" },
    benefit: { en: "Free delivery at empanelled hospitals + ₹1,400 for transport & nutrition for BPL mothers", hi: "BPL माताओं को सूचीबद्ध अस्पतालों में मुफ्त प्रसव + ₹1,400 परिवहन व पोषण सहायता" },
    tag:     { en: "Women / Maternity", hi: "महिला / मातृत्व" },
    annual: 1400,
    apply:   { en: "108.gov.in / nearest PHC", hi: "108.gov.in / नज़दीकी PHC" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "BPL / Ration Card", "Pregnancy Registration (MCP Card)", "Bank Account"],
               hi: ["आधार कार्ड", "BPL / राशन कार्ड", "गर्भावस्था पंजीकरण (MCP कार्ड)", "बैंक खाता"] },
    match: (a) => a.state === "Gujarat" && a.who === "women" && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "gujarat_ganga_swarupa",
    icon: "👩‍🦳", color: "#7E22CE", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Social Justice & Empowerment Dept.", hi: "गुजरात सामाजिक न्याय एवं अधिकारिता विभाग" },
    name:    { en: "Ganga Swarupa Yojana – Widow Pension (Gujarat)",  hi: "गंगा स्वरूपा योजना – विधवा पेंशन (गुजरात)" },
    benefit: { en: "₹1,250/month pension for widows with no fixed income source", hi: "बिना निश्चित आय स्रोत वाली विधवाओं को ₹1,250/माह पेंशन" },
    tag:     { en: "Women / Widow", hi: "महिला / विधवा" },
    annual: 15000,
    apply:   { en: "esamajkalyan.gujarat.gov.in", hi: "esamajkalyan.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Husband's Death Certificate", "Age Proof", "Income Certificate (no fixed income)", "Bank Account", "Domicile Certificate"],
               hi: ["आधार कार्ड", "पति का मृत्यु प्रमाण पत्र", "आयु प्रमाण", "आय प्रमाण (कोई निश्चित आय नहीं)", "बैंक खाता", "अधिवास प्रमाण"] },
    match: (a) => a.state === "Gujarat" && a.who === "women" && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "gujarat_vriddha_sahay",
    icon: "👴", color: "#B45309", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Social Justice & Empowerment Dept.", hi: "गुजरात सामाजिक न्याय एवं अधिकारिता विभाग" },
    name:    { en: "Vriddha Sahay Pension Yojana (Gujarat)",          hi: "वृद्ध सहाय पेंशन योजना (गुजरात)" },
    benefit: { en: "₹1,000/month pension for destitute senior citizens aged 60+", hi: "60+ वर्ष के निराश्रित वरिष्ठ नागरिकों को ₹1,000/माह पेंशन" },
    tag:     { en: "Senior / Pension", hi: "वरिष्ठ / पेंशन" },
    annual: 12000,
    apply:   { en: "esamajkalyan.gujarat.gov.in", hi: "esamajkalyan.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Age Proof (60+)", "Income Certificate", "Domicile Certificate", "Bank Account", "Photo"],
               hi: ["आधार कार्ड", "आयु प्रमाण (60+)", "आय प्रमाण", "अधिवास प्रमाण", "बैंक खाता", "फोटो"] },
    match: (a) => a.state === "Gujarat" && (a.who === "senior" || a.age === "above60") && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "gujarat_pandit_dindayal_awas",
    icon: "🏡", color: "#92400E", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Rural Housing Dept. (DRDA)", hi: "गुजरात ग्रामीण आवास विभाग (DRDA)" },
    name:    { en: "Pandit Dindayal Upadhyay Awas Yojana (Gujarat)", hi: "पंडित दीनदयाल उपाध्याय आवास योजना (गुजरात)" },
    benefit: { en: "₹1.20–₹1.50 Lakh for BPL rural families to build a pucca house", hi: "BPL ग्रामीण परिवारों को पक्का मकान बनाने के लिए ₹1.20–₹1.50 लाख सहायता" },
    tag:     { en: "Housing / Rural", hi: "आवास / ग्रामीण" },
    annual: 150000,
    apply:   { en: "gramnirman.gujarat.gov.in", hi: "gramnirman.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "BPL Certificate", "Land / Plot Ownership Proof", "No-House Certificate", "Bank Account", "Passport Photo"],
               hi: ["आधार कार्ड", "BPL प्रमाण पत्र", "जमीन/प्लॉट स्वामित्व प्रमाण", "मकान न होने का प्रमाण", "बैंक खाता", "पासपोर्ट फोटो"] },
    match: (a) => a.state === "Gujarat" && a.area === "rural" && ["no", "kutcha"].includes(a.house) && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "gujarat_dr_ambedkar_awas",
    icon: "🏠", color: "#1E40AF", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Scheduled Caste Development Corporation", hi: "गुजरात अनुसूचित जाति विकास निगम" },
    name:    { en: "Dr. Ambedkar Awas Yojana (Gujarat)",             hi: "डॉ. अंबेडकर आवास योजना (गुजरात)" },
    benefit: { en: "₹1.20 Lakh for SC families to construct a pucca house (rural)", hi: "SC परिवारों को ग्रामीण क्षेत्र में पक्का मकान बनाने हेतु ₹1.20 लाख सहायता" },
    tag:     { en: "Housing / SC", hi: "आवास / SC" },
    annual: 120000,
    apply:   { en: "sje.gujarat.gov.in", hi: "sje.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Caste Certificate (SC)", "Income Certificate (below ₹1.20L)", "Land Ownership Proof", "No-House Certificate", "Bank Account"],
               hi: ["आधार कार्ड", "जाति प्रमाण पत्र (SC)", "आय प्रमाण (₹1.20 लाख से कम)", "भूमि स्वामित्व प्रमाण", "मकान न होने का प्रमाण", "बैंक खाता"] },
    match: (a) => a.state === "Gujarat" && ["no", "kutcha"].includes(a.house) && a.income === "below1",
  },

  {
    id: "gujarat_namo_saraswati",
    icon: "🔬", color: "#0284C7", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Education Dept.", hi: "गुजरात शिक्षा विभाग" },
    name:    { en: "Namo Saraswati Vigyan Sadhana Yojana (Gujarat)", hi: "नमो सरस्वती विज्ञान साधना योजना (गुजरात)" },
    benefit: { en: "₹25,000/year scholarship for girl students in Science stream (Class 11–12)", hi: "विज्ञान प्रवाह (कक्षा 11–12) की बालिका छात्राओं को ₹25,000/वर्ष छात्रवृत्ति" },
    tag:     { en: "Student / Science", hi: "छात्र / विज्ञान" },
    annual: 25000,
    apply:   { en: "sebexam.org", hi: "sebexam.org" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Enrollment in Science Stream (Class 11 / 12)", "Income Certificate (below ₹6L)", "Bank Account", "Passport Photo"],
               hi: ["आधार कार्ड", "विज्ञान प्रवाह में नामांकन (कक्षा 11/12)", "आय प्रमाण (₹6 लाख से कम)", "बैंक खाता", "पासपोर्ट फोटो"] },
    match: (a) => a.state === "Gujarat" && a.who === "student" && ["below1", "1to3", "3to6"].includes(a.income),
  },

  {
    id: "gujarat_postmatric_sc",
    icon: "📖", color: "#6D28D9", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Social Justice & Empowerment Dept.", hi: "गुजरात सामाजिक न्याय एवं अधिकारिता विभाग" },
    name:    { en: "Post-Matric Scholarship SC / ST / OBC (Gujarat)", hi: "पोस्ट-मैट्रिक छात्रवृत्ति SC/ST/OBC (गुजरात)" },
    benefit: { en: "Tuition fee waiver + maintenance allowance ₹5,000–₹18,000/year for higher studies", hi: "उच्च शिक्षा हेतु ट्यूशन फीस माफी + ₹5,000–₹18,000/वर्ष रखरखाव भत्ता" },
    tag:     { en: "Student / SC OBC", hi: "छात्र / SC OBC" },
    annual: 18000,
    apply:   { en: "esamajkalyan.gujarat.gov.in", hi: "esamajkalyan.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Caste Certificate (SC / ST / OBC)", "Previous Year Mark Sheets", "Income Certificate (below ₹2.5L)", "Bonafide Certificate from Institution", "Bank Account"],
               hi: ["आधार कार्ड", "जाति प्रमाण पत्र (SC/ST/OBC)", "पिछले वर्ष की मार्कशीट", "आय प्रमाण (₹2.5 लाख से कम)", "संस्थान से बोनाफाइड प्रमाण पत्र", "बैंक खाता"] },
    match: (a) => a.state === "Gujarat" && a.who === "student" && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "gujarat_saat_fer",
    icon: "💍", color: "#9D174D", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Social Justice & Empowerment Dept.", hi: "गुजरात सामाजिक न्याय एवं अधिकारिता विभाग" },
    name:    { en: "Mukhyamantri Saat Fera Samuh Lagna Yojana (Gujarat)", hi: "मुख्यमंत्री सात फेरा सामूहिक विवाह योजना (गुजरात)" },
    benefit: { en: "₹12,000 of household gifts per couple + ₹10,000 cash to the bride at mass community weddings", hi: "सामूहिक विवाह में प्रति जोड़े को ₹12,000 के गृह उपकरण + दुल्हन को ₹10,000 नकद" },
    tag:     { en: "Women / Marriage", hi: "महिला / विवाह" },
    annual: 22000,
    apply:   { en: "sje.gujarat.gov.in", hi: "sje.gujarat.gov.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card (Both)", "Age Proof (Bride 18+, Groom 21+)", "Income Certificate", "Caste Certificate (if applicable)", "Passport Photos"],
               hi: ["आधार कार्ड (दोनों)", "आयु प्रमाण (दुल्हन 18+, दूल्हा 21+)", "आय प्रमाण", "जाति प्रमाण (यदि लागू)", "पासपोर्ट फोटो"] },
    match: (a) => a.state === "Gujarat" && a.who === "women" && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "gujarat_swavlamban",
    icon: "♿", color: "#0F766E", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Social Justice & Empowerment Dept.", hi: "गुजरात सामाजिक न्याय एवं अधिकारिता विभाग" },
    name:    { en: "Swavlamban – Divyang Sahay & Pension Yojana (Gujarat)", hi: "स्वावलंबन – दिव्यांग सहाय एवं पेंशन योजना (गुजरात)" },
    benefit: { en: "₹1,000/month pension + free assistive devices (wheelchair, hearing aid, etc.) for persons with disability (40%+)", hi: "₹1,000/माह पेंशन + मुफ्त सहायक उपकरण (व्हीलचेयर, श्रवण यंत्र आदि) 40%+ दिव्यांगजनों को" },
    tag:     { en: "Disability / Pension", hi: "दिव्यांग / पेंशन" },
    annual: 12000,
    apply:   { en: "esamajkalyan.gujarat.gov.in", hi: "esamajkalyan.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Disability Certificate (40%+ disability from Govt. Hospital)", "Income Certificate", "Domicile Certificate", "Bank Account", "Photo"],
               hi: ["आधार कार्ड", "विकलांगता प्रमाण पत्र (सरकारी अस्पताल से 40%+)", "आय प्रमाण", "अधिवास प्रमाण", "बैंक खाता", "फोटो"] },
    match: (a) => a.state === "Gujarat" && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "gujarat_gruha_jyoti",
    icon: "💡", color: "#CA8A04", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Energy Dept. / GEBCOs (DISCOMs)", hi: "गुजरात ऊर्जा विभाग / GEBCOs (DISCOMs)" },
    name:    { en: "Indira Gandhi Gruha Jyoti Yojana (Gujarat)",     hi: "इंदिरा गांधी गृह ज्योति योजना (गुजरात)" },
    benefit: { en: "Free electricity up to 100 units/month for BPL households; subsidised tariff for 101–200 units", hi: "BPL परिवारों को 100 यूनिट/माह तक मुफ्त बिजली; 101–200 यूनिट पर रियायती दर" },
    tag:     { en: "Energy / BPL", hi: "ऊर्जा / BPL" },
    annual: 6000,
    apply:   { en: "pgvcl.com / local DISCOM office", hi: "pgvcl.com / स्थानीय DISCOM कार्यालय" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "BPL / Ration Card", "Electricity Consumer Number", "Bank Account"],
               hi: ["आधार कार्ड", "BPL / राशन कार्ड", "बिजली उपभोक्ता संख्या", "बैंक खाता"] },
    match: (a) => a.state === "Gujarat" && a.income === "below1",
  },

  {
    id: "gujarat_mukhyamantri_apprentice",
    icon: "🛠️", color: "#1D4ED8", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Labour & Employment Dept.", hi: "गुजरात श्रम एवं रोजगार विभाग" },
    name:    { en: "Mukhyamantri Apprenticeship Scheme – MMAS (Gujarat)", hi: "मुख्यमंत्री अप्रेंटिसशिप योजना – MMAS (गुजरात)" },
    benefit: { en: "₹3,000/month stipend for 1 year during industry apprenticeship + placement support", hi: "उद्योग प्रशिक्षुता के दौरान 1 वर्ष तक ₹3,000/माह वजीफा + नौकरी सहायता" },
    tag:     { en: "Skill / Youth", hi: "कौशल / युवा" },
    annual: 36000,
    apply:   { en: "nats.education.gov.in", hi: "nats.education.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Educational Certificate (10th / ITI / Diploma / Degree)", "Bank Account", "Passport Photo"],
               hi: ["आधार कार्ड", "शैक्षणिक प्रमाण (10वीं / ITI / डिप्लोमा / डिग्री)", "बैंक खाता", "पासपोर्ट फोटो"] },
    match: (a) => a.state === "Gujarat" && a.age === "18to35" && ["below1", "1to3", "3to6"].includes(a.income),
  },

  {
    id: "gujarat_drip_irrigation",
    icon: "💧", color: "#0369A1", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Agriculture Dept. (Micro Irrigation)", hi: "गुजरात कृषि विभाग (सूक्ष्म सिंचाई)" },
    name:    { en: "Drip / Sprinkler Irrigation Subsidy (Gujarat)",   hi: "ड्रिप / स्प्रिंकलर सिंचाई सब्सिडी (गुजरात)" },
    benefit: { en: "70% subsidy on drip & sprinkler systems for small & marginal farmers", hi: "छोटे व सीमांत किसानों को ड्रिप व स्प्रिंकलर सिंचाई प्रणाली पर 70% सब्सिडी" },
    tag:     { en: "Farmer / Irrigation", hi: "किसान / सिंचाई" },
    annual: 70000,
    apply:   { en: "ikhedut.gujarat.gov.in", hi: "ikhedut.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Land Records (7/12 Utara)", "Bank Passbook", "Caste Certificate (if SC/ST)", "Photo"],
               hi: ["आधार कार्ड", "जमीन के कागज़ (7/12 उतारा)", "बैंक पासबुक", "जाति प्रमाण (SC/ST के लिए)", "फोटो"] },
    match: (a) => a.state === "Gujarat" && a.who === "farmer" && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "gujarat_machhi_mar",
    icon: "🎣", color: "#0891B2", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Fisheries Dept.", hi: "गुजरात मत्स्य पालन विभाग" },
    name:    { en: "Machhi Mar Kalyan Yojana – Fishermen Welfare (Gujarat)", hi: "मछीमार कल्याण योजना (गुजरात)" },
    benefit: { en: "₹2 Lakh accident insurance + 50% subsidy on boat & net equipment for registered fishermen", hi: "पंजीकृत मछुआरों को ₹2 लाख दुर्घटना बीमा + नाव व जाल उपकरण पर 50% सब्सिडी" },
    tag:     { en: "Fishermen / Welfare", hi: "मछुआरा / कल्याण" },
    annual: 50000,
    apply:   { en: "fisheries.gujarat.gov.in", hi: "fisheries.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Fisherman Registration Certificate", "Bank Passbook", "Domicile Certificate", "Photo"],
               hi: ["आधार कार्ड", "मछुआरा पंजीकरण प्रमाण पत्र", "बैंक पासबुक", "अधिवास प्रमाण", "फोटो"] },
    match: (a) => a.state === "Gujarat" && a.who === "farmer",
  },

  {
    id: "gujarat_tribal_ashram",
    icon: "🏫", color: "#065F46", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Tribal Development Dept.", hi: "गुजरात जनजाति विकास विभाग" },
    name:    { en: "Ashram Shala – Free Residential School for ST (Gujarat)", hi: "आश्रम शाला – अनुसूचित जनजाति हेतु मुफ्त आवासीय विद्यालय (गुजरात)" },
    benefit: { en: "Free boarding, lodging, uniform & education for Scheduled Tribe students (Class 1–12)", hi: "अनुसूचित जनजाति के छात्रों को मुफ्त आवास, भोजन, वर्दी व शिक्षा (कक्षा 1–12)" },
    tag:     { en: "Student / Tribal ST", hi: "छात्र / जनजाति ST" },
    annual: 30000,
    apply:   { en: "tribal.gujarat.gov.in", hi: "tribal.gujarat.gov.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "ST Caste Certificate", "Birth Certificate", "Income Certificate", "Previous School Leaving Certificate", "Passport Photo"],
               hi: ["आधार कार्ड", "ST जाति प्रमाण पत्र", "जन्म प्रमाण पत्र", "आय प्रमाण", "पिछले विद्यालय का प्रमाण पत्र", "पासपोर्ट फोटो"] },
    match: (a) => a.state === "Gujarat" && a.who === "student" && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "gujarat_prematric_sc",
    icon: "✏️", color: "#4338CA", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Social Justice & Empowerment Dept.", hi: "गुजरात सामाजिक न्याय एवं अधिकारिता विभाग" },
    name:    { en: "Pre-Matric Scholarship SC / ST – Class 1–10 (Gujarat)", hi: "प्री-मैट्रिक छात्रवृत्ति SC/ST – कक्षा 1–10 (गुजरात)" },
    benefit: { en: "₹225–₹700/month maintenance allowance + free books & uniforms for SC/ST students", hi: "SC/ST छात्रों को ₹225–₹700/माह रखरखाव भत्ता + मुफ्त किताबें व वर्दी" },
    tag:     { en: "Student / Pre-Matric SC", hi: "छात्र / प्री-मैट्रिक SC" },
    annual: 8400,
    apply:   { en: "esamajkalyan.gujarat.gov.in", hi: "esamajkalyan.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Caste Certificate (SC / ST)", "School Enrollment Certificate", "Income Certificate (below ₹2.5L)", "Bank Account (Parent)", "Photo"],
               hi: ["आधार कार्ड", "जाति प्रमाण पत्र (SC/ST)", "स्कूल नामांकन प्रमाण", "आय प्रमाण (₹2.5 लाख से कम)", "बैंक खाता (माता-पिता)", "फोटो"] },
    match: (a) => a.state === "Gujarat" && a.who === "student" && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "gujarat_kanyadan",
    icon: "👰", color: "#DB2777", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Social Justice & Empowerment Dept.", hi: "गुजरात सामाजिक न्याय एवं अधिकारिता विभाग" },
    name:    { en: "Kanyadan Yojana – Girl Marriage Assistance (Gujarat)", hi: "कन्यादान योजना – बालिका विवाह सहायता (गुजरात)" },
    benefit: { en: "₹1 Lakh financial assistance for marriage of girls from SC / ST / OBC / EWS families", hi: "SC/ST/OBC/EWS परिवारों की बेटियों के विवाह हेतु ₹1 लाख वित्तीय सहायता" },
    tag:     { en: "Women / Marriage Aid", hi: "महिला / विवाह सहायता" },
    annual: 100000,
    apply:   { en: "esamajkalyan.gujarat.gov.in", hi: "esamajkalyan.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card (Girl)", "Caste Certificate (SC/ST/OBC)", "Income Certificate (below ₹1.5L)", "Age Proof (18+)", "Marriage Registration", "Bank Account"],
               hi: ["आधार कार्ड (बालिका)", "जाति प्रमाण पत्र (SC/ST/OBC)", "आय प्रमाण (₹1.5 लाख से कम)", "आयु प्रमाण (18+)", "विवाह पंजीकरण", "बैंक खाता"] },
    match: (a) => a.state === "Gujarat" && a.who === "women" && a.income === "below1",
  },

  {
    id: "gujarat_bocw",
    icon: "👷", color: "#78350F", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Building & Other Construction Workers Welfare Board", hi: "गुजरात भवन एवं अन्य निर्माण कर्मकार कल्याण बोर्ड" },
    name:    { en: "BOCW Welfare Scheme – Construction Workers (Gujarat)", hi: "BOCW कल्याण योजना – निर्माण श्रमिक (गुजरात)" },
    benefit: { en: "₹1,000/month pension · ₹20,000 daughter's marriage aid · ₹5,000 tool grant · Education & health benefits for registered construction workers", hi: "₹1,000/माह पेंशन · बेटी की शादी पर ₹20,000 · ₹5,000 उपकरण अनुदान · पंजीकृत निर्माण श्रमिकों को शिक्षा व स्वास्थ्य सहायता" },
    tag:     { en: "Labour / Construction", hi: "श्रम / निर्माण" },
    annual: 20000,
    apply:   { en: "bocwwb.gujarat.gov.in", hi: "bocwwb.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "90-day Work Certificate from Contractor", "Bank Account", "Photo", "Nominee's Aadhaar"],
               hi: ["आधार कार्ड", "ठेकेदार से 90 दिन का कार्य प्रमाण पत्र", "बैंक खाता", "फोटो", "नामांकित व्यक्ति का आधार"] },
    match: (a) => a.state === "Gujarat" && ["below1", "1to3"].includes(a.income) && ["18to35", "35to60"].includes(a.age),
  },

  {
    id: "gujarat_ghb_housing",
    icon: "🏢", color: "#1E3A8A", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Housing Board (GHB)", hi: "गुजरात आवास बोर्ड (GHB)" },
    name:    { en: "Gujarat Housing Board – EWS / LIG Affordable Flats", hi: "गुजरात आवास बोर्ड – EWS/LIG सस्ता आवास" },
    benefit: { en: "Below-market-rate flats for EWS (₹4–8L) & LIG (₹8–15L) families in urban Gujarat cities", hi: "शहरी गुजरात में EWS (₹4–8 लाख) व LIG (₹8–15 लाख) परिवारों को बाज़ार से कम दर पर फ्लैट" },
    tag:     { en: "Housing / Urban", hi: "आवास / शहरी" },
    annual: 0,
    apply:   { en: "ghb.gujarat.gov.in", hi: "ghb.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Income Certificate (EWS: below ₹3L · LIG: ₹3–6L)", "No-Property Certificate", "Bank Statement (6 months)", "Passport Photo"],
               hi: ["आधार कार्ड", "आय प्रमाण (EWS: ₹3 लाख से कम · LIG: ₹3–6 लाख)", "संपत्ति न होने का प्रमाण", "बैंक स्टेटमेंट (6 माह)", "पासपोर्ट फोटो"] },
    match: (a) => a.state === "Gujarat" && ["urban", "semi"].includes(a.area) && ["no", "kutcha"].includes(a.house) && ["below1", "1to3", "3to6"].includes(a.income),
  },

  {
    id: "gujarat_icreate",
    icon: "🚀", color: "#7C3AED", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Science & Technology Dept. / iCreate", hi: "गुजरात विज्ञान एवं प्रौद्योगिकी विभाग / iCreate" },
    name:    { en: "iCreate – Gujarat Startup Seed Funding & Incubation", hi: "आईक्रिएट – गुजरात स्टार्टअप बीज निधि एवं इनक्यूबेशन" },
    benefit: { en: "Seed grant up to ₹15 Lakh + mentoring, lab access & co-working space for tech startups", hi: "टेक स्टार्टअप को ₹15 लाख तक बीज अनुदान + मेंटरिंग, लैब एक्सेस व को-वर्किंग स्पेस" },
    tag:     { en: "Business / Startup", hi: "व्यापार / स्टार्टअप" },
    annual: 0,
    apply:   { en: "icreate.org.in", hi: "icreate.org.in" }, applyType: "online",
    docs:    { en: ["Aadhaar & PAN Card", "Startup / Business Registration", "Project Proposal / Pitch Deck", "Bank Account"],
               hi: ["आधार और पैन कार्ड", "स्टार्टअप / व्यापार पंजीकरण", "प्रोजेक्ट प्रस्ताव / पिच डेक", "बैंक खाता"] },
    match: (a) => a.state === "Gujarat" && a.who === "business" && ["18to35", "35to60"].includes(a.age),
  },

  {
    id: "gujarat_surya_rooftop",
    icon: "☀️", color: "#D97706", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Energy Dept. / GUVNL", hi: "गुजरात ऊर्जा विभाग / GUVNL" },
    name:    { en: "Surya Gujarat – Rooftop Solar Subsidy",           hi: "सूर्य गुजरात – रूफटॉप सोलर सब्सिडी" },
    benefit: { en: "40% subsidy on rooftop solar (up to 3kW) + net metering buyback ₹3/unit fed to grid", hi: "3kW तक रूफटॉप सोलर पर 40% सब्सिडी + ग्रिड को भेजी यूनिट पर ₹3/यूनिट वापसी" },
    tag:     { en: "Energy / Solar", hi: "ऊर्जा / सोलर" },
    annual: 40000,
    apply:   { en: "solarrooftop.gov.in / guvnl.in", hi: "solarrooftop.gov.in / guvnl.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Electricity Consumer Number", "Latest Electricity Bill", "Bank Account", "Photo of Roof Area"],
               hi: ["आधार कार्ड", "बिजली उपभोक्ता संख्या", "नवीनतम बिजली बिल", "बैंक खाता", "छत क्षेत्र की फोटो"] },
    match: (a) => a.state === "Gujarat" && ["below1", "1to3", "3to6"].includes(a.income),
  },

  {
    id: "gujarat_pashu_sahay",
    icon: "🐄", color: "#15803D", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Animal Husbandry Dept.", hi: "गुजरात पशुपालन विभाग" },
    name:    { en: "Pashu Palan Sahay – Livestock Purchase Subsidy (Gujarat)", hi: "पशु पालन सहाय – पशुधन क्रय सब्सिडी (गुजरात)" },
    benefit: { en: "50% subsidy (SC/ST) · 25% (Others) on purchase of milch cattle, goats & poultry units", hi: "दुधारू पशु, बकरी व मुर्गी इकाई खरीद पर SC/ST को 50% · अन्य को 25% सब्सिडी" },
    tag:     { en: "Farmer / Livestock", hi: "किसान / पशुपालन" },
    annual: 50000,
    apply:   { en: "ikhedut.gujarat.gov.in", hi: "ikhedut.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Land / Domicile Certificate", "Caste Certificate (SC/ST if applicable)", "Bank Passbook", "Veterinary Certificate for Animal", "Photo"],
               hi: ["आधार कार्ड", "जमीन / अधिवास प्रमाण", "जाति प्रमाण (SC/ST यदि लागू)", "बैंक पासबुक", "पशु का पशु-चिकित्सा प्रमाण", "फोटो"] },
    match: (a) => a.state === "Gujarat" && a.who === "farmer",
  },

  {
    id: "gujarat_organic_farming",
    icon: "🌿", color: "#166534", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Agriculture Dept. – Organic Farming Mission", hi: "गुजरात कृषि विभाग – जैविक खेती मिशन" },
    name:    { en: "Organic Farming Mission – Jeevamrut Subsidy (Gujarat)", hi: "जैविक खेती मिशन – जीवामृत सब्सिडी (गुजरात)" },
    benefit: { en: "₹20,000/ha subsidy on organic certification, inputs & bio-fertilisers; up to 2 ha per farmer", hi: "जैविक प्रमाणीकरण, इनपुट व जैव-उर्वरक पर ₹20,000/हेक्टेयर सब्सिडी; प्रति किसान 2 हेक्टेयर तक" },
    tag:     { en: "Farmer / Organic", hi: "किसान / जैविक खेती" },
    annual: 40000,
    apply:   { en: "agri.gujarat.gov.in", hi: "agri.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Land Records (7/12 Utara)", "Soil Health Card", "Bank Passbook", "Photo"],
               hi: ["आधार कार्ड", "जमीन के कागज़ (7/12 उतारा)", "मृदा स्वास्थ्य कार्ड", "बैंक पासबुक", "फोटो"] },
    match: (a) => a.state === "Gujarat" && a.who === "farmer",
  },

  {
    id: "gujarat_minority_scholarship",
    icon: "🕌", color: "#1D4ED8", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Minority Finance & Development Corporation", hi: "गुजरात अल्पसंख्यक वित्त एवं विकास निगम" },
    name:    { en: "Post-Matric Scholarship for Minorities (Gujarat)",  hi: "अल्पसंख्यकों के लिए पोस्ट-मैट्रिक छात्रवृत्ति (गुजरात)" },
    benefit: { en: "Tuition fee + ₹5,000–₹12,000/year maintenance for Muslim, Christian, Parsi, Jain, Buddhist & Sikh students in higher education", hi: "मुस्लिम, ईसाई, पारसी, जैन, बौद्ध व सिख छात्रों को उच्च शिक्षा में ट्यूशन फीस + ₹5,000–₹12,000/वर्ष भत्ता" },
    tag:     { en: "Student / Minority", hi: "छात्र / अल्पसंख्यक" },
    annual: 12000,
    apply:   { en: "gujaratminority.gov.in", hi: "gujaratminority.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Minority Community Certificate", "Previous Year Mark Sheets", "Income Certificate (below ₹2.5L)", "Bonafide Certificate", "Bank Account"],
               hi: ["आधार कार्ड", "अल्पसंख्यक समुदाय प्रमाण पत्र", "पिछले वर्ष की मार्कशीट", "आय प्रमाण (₹2.5 लाख से कम)", "बोनाफाइड प्रमाण पत्र", "बैंक खाता"] },
    match: (a) => a.state === "Gujarat" && a.who === "student" && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "gujarat_namo_e_tab",
    icon: "📱", color: "#0284C7", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Education Dept.", hi: "गुजरात शिक्षा विभाग" },
    name:    { en: "Namo e-Tab Yojana – Free Tablet for Students (Gujarat)", hi: "नमो ई-टैब योजना – छात्रों को मुफ्त टैबलेट (गुजरात)" },
    benefit: { en: "Free Android tablet (₹10,000 value) for students in Class 9 & Class 11 in government schools", hi: "सरकारी स्कूलों में कक्षा 9 व कक्षा 11 के छात्रों को मुफ्त एंड्रॉयड टैबलेट (₹10,000 मूल्य)" },
    tag:     { en: "Student / Digital", hi: "छात्र / डिजिटल" },
    annual: 10000,
    apply:   { en: "Through school / sebexam.org", hi: "विद्यालय के माध्यम से / sebexam.org" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "School Enrollment Certificate (Class 9 / 11)", "Passport Photo"],
               hi: ["आधार कार्ड", "स्कूल नामांकन प्रमाण (कक्षा 9/11)", "पासपोर्ट फोटो"] },
    match: (a) => a.state === "Gujarat" && a.who === "student" && ["below1", "1to3", "3to6"].includes(a.income),
  },

  {
    id: "gujarat_balsakha",
    icon: "🧒", color: "#BE123C", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Women & Child Development Dept.", hi: "गुजरात महिला एवं बाल विकास विभाग" },
    name:    { en: "Balsakha Yojana – Destitute Child Welfare (Gujarat)", hi: "बालसखा योजना – निराश्रित बाल कल्याण (गुजरात)" },
    benefit: { en: "₹3,000/month for care & education of orphaned / destitute children up to age 18", hi: "18 वर्ष तक के अनाथ / निराश्रित बच्चों की देखभाल व शिक्षा हेतु ₹3,000/माह" },
    tag:     { en: "Child / Destitute", hi: "बाल / निराश्रित" },
    annual: 36000,
    apply:   { en: "wcd.gujarat.gov.in", hi: "wcd.gujarat.gov.in" }, applyType: "offline",
    docs:    { en: ["Child's Aadhaar Card", "Birth Certificate", "Death Certificate of Parents (if orphan)", "Guardian's Aadhaar", "Income Certificate", "Bank Account (Guardian)"],
               hi: ["बच्चे का आधार कार्ड", "जन्म प्रमाण पत्र", "माता-पिता का मृत्यु प्रमाण (यदि अनाथ)", "अभिभावक का आधार", "आय प्रमाण", "बैंक खाता (अभिभावक)"] },
    match: (a) => a.state === "Gujarat" && a.income === "below1",
  },

  {
    id: "gujarat_gsdm_skill",
    icon: "🎓", color: "#0F766E", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Skill Development Mission (GSDM)", hi: "गुजरात कौशल विकास मिशन (GSDM)" },
    name:    { en: "GSDM Free Skill Training (Gujarat)",              hi: "GSDM मुफ्त कौशल प्रशिक्षण (गुजरात)" },
    benefit: { en: "Free 3–6 month vocational training in 200+ trades (IT, construction, garment, hospitality, etc.) + job placement support", hi: "200+ व्यवसायों में 3–6 माह का मुफ्त व्यावसायिक प्रशिक्षण (IT, निर्माण, वस्त्र, आतिथ्य आदि) + नौकरी सहायता" },
    tag:     { en: "Skill / Vocational", hi: "कौशल / व्यावसायिक" },
    annual: 25000,
    apply:   { en: "gsdm.gujarat.gov.in", hi: "gsdm.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Educational Certificate (min. Class 8)", "Bank Account", "Passport Photo"],
               hi: ["आधार कार्ड", "शैक्षणिक प्रमाण (न्यूनतम कक्षा 8)", "बैंक खाता", "पासपोर्ट फोटो"] },
    match: (a) => a.state === "Gujarat" && ["18to35"].includes(a.age) && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "gujarat_ma_amrutum_plus",
    icon: "🏥", color: "#DC2626", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Health & Family Welfare Dept.", hi: "गुजरात स्वास्थ्य एवं परिवार कल्याण विभाग" },
    name:    { en: "MA Amrutum Plus – Health Insurance (Gujarat)",    hi: "MA अमृतम प्लस – स्वास्थ्य बीमा (गुजरात)" },
    benefit: { en: "₹5 Lakh/year cashless treatment at empanelled hospitals for families with annual income ₹2.5–₹4 Lakh", hi: "₹2.5–₹4 लाख वार्षिक आय वाले परिवारों को सूचीबद्ध अस्पतालों में ₹5 लाख/वर्ष कैशलेस उपचार" },
    tag:     { en: "Health / Insurance", hi: "स्वास्थ्य / बीमा" },
    annual: 500000,
    apply:   { en: "maavcard.gujarat.gov.in", hi: "maavcard.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Income Certificate (₹2.5L–₹4L)", "Ration Card", "Bank Account", "Passport Photo"],
               hi: ["आधार कार्ड", "आय प्रमाण (₹2.5–₹4 लाख)", "राशन कार्ड", "बैंक खाता", "पासपोर्ट फोटो"] },
    match: (a) => a.state === "Gujarat" && a.income === "1to3",
  },

  {
    id: "gujarat_horticulture",
    icon: "🍅", color: "#B91C1C", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Horticulture Dept. – NHM State Component", hi: "गुजरात बागवानी विभाग – NHM राज्य घटक" },
    name:    { en: "Gujarat Horticulture Mission – Fruit & Vegetable Subsidy", hi: "गुजरात बागवानी मिशन – फल व सब्जी सब्सिडी" },
    benefit: { en: "50% subsidy on certified planting material, poly-house, shade net & drip for fruit & vegetable farmers", hi: "फल व सब्जी किसानों को प्रमाणित पौध सामग्री, पॉलीहाउस, शेडनेट व ड्रिप पर 50% सब्सिडी" },
    tag:     { en: "Farmer / Horticulture", hi: "किसान / बागवानी" },
    annual: 60000,
    apply:   { en: "agri.gujarat.gov.in", hi: "agri.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Land Records (7/12 Utara)", "Bank Passbook", "Caste Certificate (if SC/ST)", "Photo"],
               hi: ["आधार कार्ड", "जमीन के कागज़ (7/12 उतारा)", "बैंक पासबुक", "जाति प्रमाण (SC/ST के लिए)", "फोटो"] },
    match: (a) => a.state === "Gujarat" && a.who === "farmer",
  },

  {
    id: "gujarat_beekeeping",
    icon: "🐝", color: "#D97706", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Agriculture Dept. – Apiculture Mission", hi: "गुजरात कृषि विभाग – मधुमक्खी पालन मिशन" },
    name:    { en: "Apiculture / Beekeeping Subsidy (Gujarat)",        hi: "मधुमक्खी पालन सब्सिडी (गुजरात)" },
    benefit: { en: "90% subsidy on bee boxes, colonies & extraction equipment for farmers and tribal communities", hi: "किसानों व जनजातीय समुदाय को मधुमक्खी बक्से, कॉलोनी व निष्कर्षण उपकरण पर 90% सब्सिडी" },
    tag:     { en: "Farmer / Apiculture", hi: "किसान / मधुमक्खी पालन" },
    annual: 45000,
    apply:   { en: "ikhedut.gujarat.gov.in", hi: "ikhedut.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Land / Domicile Certificate", "Bank Passbook", "Photo"],
               hi: ["आधार कार्ड", "जमीन / अधिवास प्रमाण", "बैंक पासबुक", "फोटो"] },
    match: (a) => a.state === "Gujarat" && a.who === "farmer",
  },

  {
    id: "gujarat_widow_remarriage",
    icon: "💐", color: "#9D174D", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Social Justice & Empowerment Dept.", hi: "गुजरात सामाजिक न्याय एवं अधिकारिता विभाग" },
    name:    { en: "Vidhava Punarlagna Sahay – Widow Remarriage Assistance (Gujarat)", hi: "विधवा पुनर्लग्न सहाय – विधवा पुनर्विवाह सहायता (गुजरात)" },
    benefit: { en: "₹1.25 Lakh one-time financial assistance to encourage widow remarriage", hi: "विधवा पुनर्विवाह को प्रोत्साहित करने हेतु ₹1.25 लाख एकमुश्त वित्तीय सहायता" },
    tag:     { en: "Women / Widow Remarriage", hi: "महिला / विधवा पुनर्विवाह" },
    annual: 125000,
    apply:   { en: "esamajkalyan.gujarat.gov.in", hi: "esamajkalyan.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Husband's Death Certificate", "Age Proof", "New Marriage Certificate / Registration", "Income Certificate", "Bank Account"],
               hi: ["आधार कार्ड", "पति का मृत्यु प्रमाण पत्र", "आयु प्रमाण", "नया विवाह प्रमाण पत्र / पंजीकरण", "आय प्रमाण", "बैंक खाता"] },
    match: (a) => a.state === "Gujarat" && a.who === "women" && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "gujarat_salt_worker",
    icon: "🧂", color: "#64748B", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Labour & Employment Dept. – Agaria Welfare", hi: "गुजरात श्रम एवं रोजगार विभाग – अगरिया कल्याण" },
    name:    { en: "Agaria Salt Worker Kalyan Yojana (Gujarat)",      hi: "अगरिया नमक श्रमिक कल्याण योजना (गुजरात)" },
    benefit: { en: "₹1,500/month welfare allowance + health insurance + free education for children of salt pan workers (Rann of Kutch)", hi: "नमक पट्टी श्रमिकों (रण ऑफ कच्छ) को ₹1,500/माह भत्ता + स्वास्थ्य बीमा + बच्चों की मुफ्त शिक्षा" },
    tag:     { en: "Labour / Salt Worker", hi: "श्रम / नमक श्रमिक" },
    annual: 18000,
    apply:   { en: "labour.gujarat.gov.in", hi: "labour.gujarat.gov.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "Salt Pan Worker Registration Certificate", "Domicile Certificate", "Bank Account", "Photo"],
               hi: ["आधार कार्ड", "नमक पट्टी श्रमिक पंजीकरण प्रमाण पत्र", "अधिवास प्रमाण", "बैंक खाता", "फोटो"] },
    match: (a) => a.state === "Gujarat" && ["below1", "1to3"].includes(a.income) && ["18to35", "35to60"].includes(a.age),
  },

  {
    id: "gujarat_divyang_employment",
    icon: "🤝", color: "#0F766E", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Social Justice & Empowerment Dept.", hi: "गुजरात सामाजिक न्याय एवं अधिकारिता विभाग" },
    name:    { en: "Divyang Self-Employment Scheme (Gujarat)",         hi: "दिव्यांग स्व-रोजगार योजना (गुजरात)" },
    benefit: { en: "50% subsidy up to ₹2 Lakh for disabled persons to set up a small business or shop", hi: "दिव्यांग व्यक्तियों को छोटा व्यापार / दुकान स्थापित करने पर ₹2 लाख तक 50% सब्सिडी" },
    tag:     { en: "Disability / Self-Employment", hi: "दिव्यांग / स्व-रोजगार" },
    annual: 200000,
    apply:   { en: "esamajkalyan.gujarat.gov.in", hi: "esamajkalyan.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Disability Certificate (40%+ from Govt. Hospital)", "Income Certificate", "Business Plan / Proposal", "Bank Account", "Photo"],
               hi: ["आधार कार्ड", "विकलांगता प्रमाण पत्र (सरकारी अस्पताल से 40%+)", "आय प्रमाण", "व्यापार योजना / प्रस्ताव", "बैंक खाता", "फोटो"] },
    match: (a) => a.state === "Gujarat" && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "gujarat_cm_pratibha",
    icon: "🏆", color: "#CA8A04", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Education Dept.", hi: "गुजरात शिक्षा विभाग" },
    name:    { en: "Chief Minister's Pratibha Scholarship – Merit Award (Gujarat)", hi: "मुख्यमंत्री प्रतिभा छात्रवृत्ति – मेरिट पुरस्कार (गुजरात)" },
    benefit: { en: "₹10,000 for Class 10 toppers (90%+) · ₹15,000 for Class 12 toppers (90%+) in Gujarat board exams", hi: "गुजरात बोर्ड परीक्षा में कक्षा 10 में 90%+ अंक पर ₹10,000 · कक्षा 12 में 90%+ पर ₹15,000" },
    tag:     { en: "Student / Merit", hi: "छात्र / मेरिट" },
    annual: 15000,
    apply:   { en: "sebexam.org", hi: "sebexam.org" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Class 10 / 12 Board Marksheet (90%+)", "School Bonafide Certificate", "Bank Account", "Passport Photo"],
               hi: ["आधार कार्ड", "कक्षा 10/12 बोर्ड मार्कशीट (90%+)", "स्कूल बोनाफाइड प्रमाण पत्र", "बैंक खाता", "पासपोर्ट फोटो"] },
    match: (a) => a.state === "Gujarat" && a.who === "student" && ["below1", "1to3", "3to6"].includes(a.income),
  },

  {
    id: "gujarat_rte_reimburse",
    icon: "🏫", color: "#1D4ED8", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Education Dept. – RTE Cell", hi: "गुजरात शिक्षा विभाग – RTE प्रकोष्ठ" },
    name:    { en: "RTE 25% Free Admission – Private School Reimbursement (Gujarat)", hi: "RTE 25% मुफ्त प्रवेश – निजी स्कूल प्रतिपूर्ति (गुजरात)" },
    benefit: { en: "Free private school education (Class 1–8) for EWS children; school fees reimbursed by Gujarat govt up to ₹24,000/year", hi: "EWS बच्चों को निजी स्कूल में कक्षा 1–8 तक मुफ्त शिक्षा; गुजरात सरकार ₹24,000/वर्ष तक शुल्क वापसी" },
    tag:     { en: "Student / RTE EWS", hi: "छात्र / RTE EWS" },
    annual: 24000,
    apply:   { en: "rte.orpgujarat.com", hi: "rte.orpgujarat.com" }, applyType: "online",
    docs:    { en: ["Aadhaar Card (Child)", "Income Certificate (below ₹1L for EWS)", "Caste / Disability Certificate (if applicable)", "Birth Certificate", "Domicile Certificate", "Passport Photo"],
               hi: ["आधार कार्ड (बच्चा)", "आय प्रमाण (EWS: ₹1 लाख से कम)", "जाति/विकलांगता प्रमाण (यदि लागू)", "जन्म प्रमाण पत्र", "अधिवास प्रमाण", "पासपोर्ट फोटो"] },
    match: (a) => a.state === "Gujarat" && a.who === "student" && a.income === "below1",
  },

  {
    id: "gujarat_aajeevika",
    icon: "🌾", color: "#065F46", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Rural Livelihood Mission (GRLM – Aajeevika)", hi: "गुजरात ग्रामीण आजीविका मिशन (GRLM – आजीविका)" },
    name:    { en: "Gujarat Aajeevika Mission – SHG Revolving Fund & Livelihood", hi: "गुजरात आजीविका मिशन – SHG आवर्ती निधि एवं आजीविका" },
    benefit: { en: "₹15,000 revolving fund per SHG + bank linkage, livelihood training & market access for rural poor women", hi: "प्रति SHG ₹15,000 आवर्ती निधि + बैंक लिंकेज, आजीविका प्रशिक्षण व बाज़ार पहुँच (ग्रामीण महिलाओं के लिए)" },
    tag:     { en: "Women / Rural Livelihood", hi: "महिला / ग्रामीण आजीविका" },
    annual: 15000,
    apply:   { en: "glpc.gujarat.gov.in", hi: "glpc.gujarat.gov.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "SHG Formation Proof (min. 10 members)", "Bank Account (Group)", "Income Certificate", "Ration Card"],
               hi: ["आधार कार्ड", "SHG गठन प्रमाण (न्यूनतम 10 सदस्य)", "बैंक खाता (समूह)", "आय प्रमाण", "राशन कार्ड"] },
    match: (a) => a.state === "Gujarat" && a.who === "women" && a.area === "rural" && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "gujarat_free_crop_insurance",
    icon: "🌾", color: "#16A34A", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Agriculture Dept. – PMFBY Zero Premium", hi: "गुजरात कृषि विभाग – PMFBY शून्य प्रीमियम" },
    name:    { en: "Free Crop Insurance – PMFBY Zero Premium (Gujarat)", hi: "मुफ्त फसल बीमा – PMFBY शून्य प्रीमियम (गुजरात)" },
    benefit: { en: "Gujarat state pays 100% farmer premium; free coverage ₹40,000–₹60,000/ha against drought, flood & pest crop loss", hi: "गुजरात राज्य 100% किसान प्रीमियम वहन करता है; सूखे, बाढ़ व कीटों से ₹40,000–₹60,000/हेक्टेयर मुफ्त फसल बीमा" },
    tag:     { en: "Farmer / Crop Insurance", hi: "किसान / फसल बीमा" },
    annual: 50000,
    apply:   { en: "pmfby.gov.in / ikhedut.gujarat.gov.in", hi: "pmfby.gov.in / ikhedut.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Land Records (7/12 Utara)", "Bank Passbook", "Crop Sowing Certificate"],
               hi: ["आधार कार्ड", "जमीन के कागज़ (7/12 उतारा)", "बैंक पासबुक", "फसल बुवाई प्रमाण"] },
    match: (a) => a.state === "Gujarat" && a.who === "farmer",
  },

  {
    id: "gujarat_sericulture",
    icon: "🐛", color: "#92400E", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Tribal Development Dept. – Sericulture", hi: "गुजरात जनजाति विकास विभाग – रेशम उत्पादन" },
    name:    { en: "Sericulture / Silk Farming Subsidy – Tribal Farmers (Gujarat)", hi: "रेशम उत्पादन / सिल्क खेती सब्सिडी – जनजातीय किसान (गुजरात)" },
    benefit: { en: "90% subsidy on mulberry saplings, cocoon rearing equipment & training for tribal area farmers", hi: "जनजातीय क्षेत्र के किसानों को शहतूत पौधे, कोकून पालन उपकरण व प्रशिक्षण पर 90% सब्सिडी" },
    tag:     { en: "Farmer / Sericulture", hi: "किसान / रेशम उत्पादन" },
    annual: 45000,
    apply:   { en: "tribal.gujarat.gov.in", hi: "tribal.gujarat.gov.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "ST Caste Certificate", "Land Records (7/12 Utara)", "Bank Passbook", "Photo"],
               hi: ["आधार कार्ड", "ST जाति प्रमाण पत्र", "जमीन के कागज़ (7/12 उतारा)", "बैंक पासबुक", "फोटो"] },
    match: (a) => a.state === "Gujarat" && a.who === "farmer" && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "gujarat_cold_chain",
    icon: "🏭", color: "#0369A1", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Agriculture & APMC – Agri Infrastructure Fund", hi: "गुजरात कृषि एवं APMC – कृषि अवसंरचना कोष" },
    name:    { en: "Cold Storage & Warehouse Subsidy – Agri Infra (Gujarat)", hi: "कोल्ड स्टोरेज एवं गोदाम सब्सिडी – कृषि अवसंरचना (गुजरात)" },
    benefit: { en: "25–40% capital subsidy for construction of cold storage, pack houses & primary processing units for farmers / FPOs", hi: "किसानों / FPOs को कोल्ड स्टोरेज, पैक हाउस व प्राथमिक प्रसंस्करण इकाई पर 25–40% पूंजी सब्सिडी" },
    tag:     { en: "Farmer / Agri Infra", hi: "किसान / कृषि अवसंरचना" },
    annual: 0,
    apply:   { en: "agriinfra.dac.gov.in / agri.gujarat.gov.in", hi: "agriinfra.dac.gov.in / agri.gujarat.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar & PAN Card", "Land Ownership / Lease Proof", "Detailed Project Report (DPR)", "Bank Statement (6 months)", "Caste Certificate (if SC/ST)"],
               hi: ["आधार और पैन कार्ड", "जमीन स्वामित्व / पट्टा प्रमाण", "विस्तृत परियोजना रिपोर्ट (DPR)", "बैंक स्टेटमेंट (6 माह)", "जाति प्रमाण (SC/ST के लिए)"] },
    match: (a) => a.state === "Gujarat" && a.who === "farmer",
  },

  {
    id: "gujarat_handloom_weaver",
    icon: "🧵", color: "#7C3AED", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Handloom Corporation / Industries Dept.", hi: "गुजरात हैंडलूम कॉर्पोरेशन / उद्योग विभाग" },
    name:    { en: "Handloom Weaver Welfare – Yarn & Loom Subsidy (Gujarat)", hi: "हैंडलूम बुनकर कल्याण – धागा एवं करघा सब्सिडी (गुजरात)" },
    benefit: { en: "50% subsidy on yarn & tools + ₹2 Lakh upgraded loom grant + marketing support for registered handloom weavers", hi: "पंजीकृत हैंडलूम बुनकरों को धागे व औज़ारों पर 50% सब्सिडी + ₹2 लाख उन्नत करघा अनुदान + बाज़ार सहायता" },
    tag:     { en: "Labour / Handloom", hi: "श्रम / हैंडलूम" },
    annual: 24000,
    apply:   { en: "industries.gujarat.gov.in", hi: "industries.gujarat.gov.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "Weaver Identity Card / Registration", "Caste Certificate (if SC/ST/OBC)", "Bank Account", "Photo"],
               hi: ["आधार कार्ड", "बुनकर पहचान पत्र / पंजीकरण", "जाति प्रमाण (SC/ST/OBC के लिए)", "बैंक खाता", "फोटो"] },
    match: (a) => a.state === "Gujarat" && ["below1", "1to3"].includes(a.income) && ["18to35", "35to60"].includes(a.age),
  },

  {
    id: "gujarat_minority_loan",
    icon: "🏪", color: "#0C4A6E", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Minority Finance & Development Corporation", hi: "गुजरात अल्पसंख्यक वित्त एवं विकास निगम" },
    name:    { en: "Minority Self-Employment Loan (Gujarat)",           hi: "अल्पसंख्यक स्व-रोजगार ऋण (गुजरात)" },
    benefit: { en: "Low-interest loan up to ₹10 Lakh at 5% p.a. for entrepreneurs from Muslim, Christian, Parsi, Jain, Buddhist & Sikh communities", hi: "मुस्लिम, ईसाई, पारसी, जैन, बौद्ध व सिख समुदाय के उद्यमियों को 5% प्रति वर्ष ब्याज पर ₹10 लाख तक ऋण" },
    tag:     { en: "Business / Minority Loan", hi: "व्यापार / अल्पसंख्यक ऋण" },
    annual: 0,
    apply:   { en: "gujaratminority.gov.in", hi: "gujaratminority.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar & PAN Card", "Minority Community Certificate", "Income Certificate (below ₹6L)", "Business Plan", "Bank Statement (6 months)", "Guarantor Details"],
               hi: ["आधार और पैन कार्ड", "अल्पसंख्यक समुदाय प्रमाण पत्र", "आय प्रमाण (₹6 लाख से कम)", "व्यापार योजना", "बैंक स्टेटमेंट (6 माह)", "ज़मानतदार विवरण"] },
    match: (a) => a.state === "Gujarat" && a.who === "business" && ["below1", "1to3", "3to6"].includes(a.income),
  },

  {
    id: "gujarat_urban_livelihood",
    icon: "🛒", color: "#0891B2", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Urban Development Dept. – GULP / NULM", hi: "गुजरात शहरी विकास विभाग – GULP / NULM" },
    name:    { en: "Gujarat Urban Livelihood Mission – Self-Employment Loan (GULP)", hi: "गुजरात शहरी आजीविका मिशन – स्व-रोजगार ऋण (GULP)" },
    benefit: { en: "Loan up to ₹2 Lakh at 7% interest + free skill training for urban street vendors, artisans & self-employed poor", hi: "शहरी फेरीवाले, कारीगर व स्व-रोजगारी गरीबों को 7% ब्याज पर ₹2 लाख तक ऋण + मुफ्त कौशल प्रशिक्षण" },
    tag:     { en: "Labour / Urban Poor", hi: "श्रम / शहरी गरीब" },
    annual: 0,
    apply:   { en: "nulm.gov.in / local ULB office", hi: "nulm.gov.in / स्थानीय ULB कार्यालय" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "BPL / Income Certificate", "Urban Domicile Certificate", "Bank Account", "Passport Photo"],
               hi: ["आधार कार्ड", "BPL / आय प्रमाण", "शहरी अधिवास प्रमाण", "बैंक खाता", "पासपोर्ट फोटो"] },
    match: (a) => a.state === "Gujarat" && a.area === "urban" && ["below1", "1to3"].includes(a.income) && ["18to35", "35to60"].includes(a.age),
  },

  {
    id: "gujarat_sainik_welfare",
    icon: "🎖️", color: "#1E3A8A", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Sainik Welfare Board", hi: "गुजरात सैनिक कल्याण बोर्ड" },
    name:    { en: "Ex-Serviceman Welfare – Pension Top-up & Benefits (Gujarat)", hi: "भूतपूर्व सैनिक कल्याण – पेंशन टॉप-अप एवं लाभ (गुजरात)" },
    benefit: { en: "₹2,000/month pension top-up + free state bus pass + children's education fee waiver + priority employment for ex-servicemen & war widows", hi: "भूतपूर्व सैनिकों व युद्ध विधवाओं को ₹2,000/माह पेंशन टॉप-अप + मुफ्त बस पास + बच्चों की शिक्षा शुल्क माफी + प्राथमिकता रोजगार" },
    tag:     { en: "Senior / Ex-Serviceman", hi: "वरिष्ठ / भूतपूर्व सैनिक" },
    annual: 24000,
    apply:   { en: "sainikwelfare.gujarat.gov.in", hi: "sainikwelfare.gujarat.gov.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "Discharge Certificate / PPO", "Service Record Book", "Domicile Certificate", "Bank Account"],
               hi: ["आधार कार्ड", "डिस्चार्ज प्रमाण पत्र / PPO", "सेवा रिकॉर्ड बुक", "अधिवास प्रमाण", "बैंक खाता"] },
    match: (a) => a.state === "Gujarat" && ["35to60", "above60"].includes(a.age),
  },

  {
    id: "gujarat_icds_nutrition",
    icon: "🍼", color: "#BE123C", scope: "state", state: "Gujarat",
    ministry: { en: "Gujarat Women & Child Development Dept. – ICDS", hi: "गुजरात महिला एवं बाल विकास विभाग – ICDS" },
    name:    { en: "ICDS Supplementary Nutrition – Children & Mothers (Gujarat)", hi: "ICDS पूरक पोषण – बच्चों व माताओं के लिए (गुजरात)" },
    benefit: { en: "Free take-home ration + hot cooked meals at Anganwadi for children under 6, pregnant & lactating women", hi: "6 वर्ष से कम बच्चों, गर्भवती व धात्री महिलाओं को आंगनवाड़ी पर मुफ्त THR राशन + गर्म पका हुआ भोजन" },
    tag:     { en: "Child / Nutrition", hi: "बाल / पोषण" },
    annual: 6000,
    apply:   { en: "Local Anganwadi Centre", hi: "स्थानीय आंगनवाड़ी केंद्र" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "Birth Certificate (for child)", "MCP Card (Mother & Child Protection Card)", "Ration Card"],
               hi: ["आधार कार्ड", "जन्म प्रमाण पत्र (बच्चे के लिए)", "MCP कार्ड", "राशन कार्ड"] },
    match: (a) => a.state === "Gujarat" && ["below1", "1to3"].includes(a.income),
  },

  // ADD MORE GUJARAT SCHEMES ABOVE THIS LINE ↓
  // {
  //   id: "gujarat_new_scheme",
  //   icon: "🆕", color: "#123456", scope: "state", state: "Gujarat",
  //   ministry: { en: "Dept. Name", hi: "विभाग का नाम" },
  //   name:    { en: "Scheme Name", hi: "योजना का नाम" },
  //   benefit: { en: "Benefit details", hi: "लाभ विवरण" },
  //   tag:     { en: "Tag", hi: "टैग" },
  //   annual: 0,
  //   apply:   { en: "website.gov.in", hi: "website.gov.in" }, applyType: "online",
  //   docs:    { en: ["Aadhaar Card"], hi: ["आधार कार्ड"] },
  //   match: (a) => a.state === "Gujarat",
  // },

];
