// Himachal Pradesh — YojanaSetu State Schemes
// ─────────────────────────────────────────────────────────────────────────────
// HOW TO ADD A NEW SCHEME:
//   1. Copy any block below, paste it above the closing ];
//   2. Give it a unique id like "himachal_new_scheme"
//   3. Update name, benefit, docs, match() and save.
//   No other file needs to change.
// ─────────────────────────────────────────────────────────────────────────────

export const HIMACHAL_PRADESH_SCHEMES = [

  {
    id: "hp_sahara",
    icon: "🏥", color: "#0369A1", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Health & Family Welfare Dept.", hi: "हिमाचल प्रदेश स्वास्थ्य विभाग" },
    name:    { en: "Sahara Yojana (Himachal Pradesh)",                hi: "सहारा योजना (हिमाचल प्रदेश)" },
    benefit: { en: "₹3,000/month financial aid for patients of serious chronic diseases", hi: "गंभीर पुरानी बीमारियों के रोगियों को ₹3,000/माह सहायता" },
    tag:     { en: "Health", hi: "स्वास्थ्य" },
    annual: 36000,
    apply:   { en: "https://hpsocialjustice.gov.in", hi: "hpsocialjustice.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Medical Certificate (Disease Proof)","Income Certificate","Bank Account","Domicile Certificate"],
               hi: ["आधार कार्ड","चिकित्सा प्रमाण पत्र (बीमारी का प्रमाण)","आय प्रमाण","बैंक खाता","अधिवास प्रमाण"] },
    match: (a) => a.state === "Himachal Pradesh" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "hp_himcare",
    icon: "🩺", color: "#0F766E", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Health & Family Welfare Dept.", hi: "हिमाचल प्रदेश स्वास्थ्य विभाग" },
    name:    { en: "HimCare Yojana",                                        hi: "हिमकेयर योजना" },
    benefit: { en: "₹5 Lakh/year free hospital treatment for families not covered under PMJAY", hi: "PMJAY में शामिल नहीं परिवारों के लिए ₹5 लाख/वर्ष मुफ्त इलाज" },
    tag:     { en: "Health", hi: "स्वास्थ्य" },
    annual: 500000,
    apply:   { en: "https://himcare.hp.gov.in", hi: "himcare.hp.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Ration Card / BPL Certificate","HP Domicile Certificate","Passport Size Photo","Bank Account"],
               hi: ["आधार कार्ड","राशन कार्ड / बीपीएल प्रमाण पत्र","हिमाचल अधिवास प्रमाण","पासपोर्ट साइज फोटो","बैंक खाता"] },
    match: (a) => a.state === "Himachal Pradesh" && ["below1","1to3","3to6"].includes(a.income),
  },

  {
    id: "hp_beti_hai_anmol",
    icon: "👧", color: "#BE185D", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Women & Child Development Dept.", hi: "हिमाचल प्रदेश महिला एवं बाल विकास विभाग" },
    name:    { en: "Beti Hai Anmol Yojana",                                          hi: "बेटी है अनमोल योजना" },
    benefit: { en: "₹10,000 FD at birth + annual scholarship up to ₹5,000 till Class 12", hi: "जन्म पर ₹10,000 की FD + कक्षा 12 तक वार्षिक ₹5,000 छात्रवृत्ति" },
    tag:     { en: "Women", hi: "महिला" },
    annual: 10000,
    apply:   { en: "himachal.nic.in", hi: "himachal.nic.in" }, applyType: "offline",
    docs:    { en: ["Birth Certificate of Girl Child","Aadhaar Card (Parent)","BPL / Income Certificate","Bank Account (in girl's name)","HP Domicile Certificate"],
               hi: ["बालिका का जन्म प्रमाण पत्र","आधार कार्ड (माता/पिता)","बीपीएल / आय प्रमाण पत्र","बैंक खाता (बालिका के नाम)","हिमाचल अधिवास प्रमाण"] },
    match: (a) => a.state === "Himachal Pradesh" && a.who === "women" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "hp_shagun",
    icon: "💍", color: "#9D174D", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Social Justice & Empowerment Dept.", hi: "हिमाचल प्रदेश सामाजिक न्याय एवं अधिकारिता विभाग" },
    name:    { en: "Shagun Yojana (Himachal Pradesh)",                     hi: "शगुन योजना (हिमाचल प्रदेश)" },
    benefit: { en: "₹31,000 marriage grant for daughters of BPL / widow / destitute families", hi: "बीपीएल / विधवा / निराश्रित परिवारों की बेटियों के विवाह पर ₹31,000 अनुदान" },
    tag:     { en: "Women", hi: "महिला" },
    annual: 31000,
    apply:   { en: "hpsocialjustice.gov.in", hi: "hpsocialjustice.gov.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card","BPL Certificate","Marriage Invitation Card / Certificate","Age Proof of Bride (≥18 years)","HP Domicile Certificate","Bank Account"],
               hi: ["आधार कार्ड","बीपीएल प्रमाण पत्र","विवाह निमंत्रण पत्र / प्रमाण पत्र","वधू की आयु प्रमाण (≥18 वर्ष)","हिमाचल अधिवास प्रमाण","बैंक खाता"] },
    match: (a) => a.state === "Himachal Pradesh" && a.who === "women" && a.income === "below1",
  },

  {
    id: "hp_widow_pension",
    icon: "🕊️", color: "#7C3AED", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Social Justice & Empowerment Dept.", hi: "हिमाचल प्रदेश सामाजिक न्याय एवं अधिकारिता विभाग" },
    name:    { en: "HP Widow & Single Woman Pension",                   hi: "हिमाचल प्रदेश विधवा एवं एकल महिला पेंशन" },
    benefit: { en: "₹1,500/month pension for widows and destitute single women", hi: "विधवाओं और एकल महिलाओं को ₹1,500/माह पेंशन" },
    tag:     { en: "Pension", hi: "पेंशन" },
    annual: 18000,
    apply:   { en: "https://hpsocialjustice.gov.in", hi: "hpsocialjustice.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Death Certificate of Husband (for widows)","Income Certificate (below ₹35,000/year)","HP Domicile Certificate","Bank Account","Passport Size Photo"],
               hi: ["आधार कार्ड","पति का मृत्यु प्रमाण पत्र (विधवा के लिए)","आय प्रमाण (₹35,000/वर्ष से कम)","हिमाचल अधिवास प्रमाण","बैंक खाता","पासपोर्ट साइज फोटो"] },
    match: (a) => a.state === "Himachal Pradesh" && a.who === "women" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "hp_old_age_pension",
    icon: "👴", color: "#FF9933", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Social Justice & Empowerment Dept.", hi: "हिमाचल प्रदेश सामाजिक न्याय एवं अधिकारिता विभाग" },
    name:    { en: "HP Old Age Pension Yojana",                    hi: "हिमाचल प्रदेश वृद्धावस्था पेंशन योजना" },
    benefit: { en: "₹1,500/month pension for senior citizens aged 60+ from low-income families", hi: "60+ वर्ष के कम आय वाले बुजुर्गों को ₹1,500/माह पेंशन" },
    tag:     { en: "Pension", hi: "पेंशन" },
    annual: 18000,
    apply:   { en: "https://hpsocialjustice.gov.in", hi: "hpsocialjustice.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Age Proof (60+ years)","Income Certificate (below ₹35,000/year)","HP Domicile Certificate","Bank Account","Passport Size Photo"],
               hi: ["आधार कार्ड","आयु प्रमाण (60+ वर्ष)","आय प्रमाण (₹35,000/वर्ष से कम)","हिमाचल अधिवास प्रमाण","बैंक खाता","पासपोर्ट साइज फोटो"] },
    match: (a) => a.state === "Himachal Pradesh" && a.who === "senior" && a.age === "above60" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "hp_swavlamban",
    icon: "💼", color: "#6B21A8", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Industries Dept.", hi: "हिमाचल प्रदेश उद्योग विभाग" },
    name:    { en: "Mukhya Mantri Swavlamban Yojana",                              hi: "मुख्यमंत्री स्वावलंबन योजना" },
    benefit: { en: "25–35% capital subsidy on plant & machinery for starting own enterprise (up to ₹60 Lakh project)", hi: "अपना उद्यम शुरू करने पर संयंत्र और मशीनरी पर 25–35% पूंजी सब्सिडी (₹60 लाख तक)" },
    tag:     { en: "Business", hi: "व्यापार" },
    annual: 0,
    apply:   { en: "https://mmsy.hp.gov.in", hi: "mmsy.hp.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","HP Domicile Certificate","Business/Project Report","Educational Certificates","Bank Account","Caste Certificate (if applicable)"],
               hi: ["आधार कार्ड","हिमाचल अधिवास प्रमाण","व्यापार/परियोजना रिपोर्ट","शैक्षणिक प्रमाण पत्र","बैंक खाता","जाति प्रमाण पत्र (यदि लागू हो)"] },
    match: (a) => a.state === "Himachal Pradesh" && (a.who === "business" || ["18to35","35to60"].includes(a.age)),
  },

  {
    id: "hp_mukhyamantri_awas",
    icon: "🏠", color: "#0F766E", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Urban Development Dept.", hi: "हिमाचल प्रदेश शहरी विकास विभाग" },
    name:    { en: "Mukhya Mantri Awas Yojana (HP)",                          hi: "मुख्यमंत्री आवास योजना (हिमाचल प्रदेश)" },
    benefit: { en: "₹1.5 Lakh grant for construction of pucca house for BPL families in hilly areas", hi: "पहाड़ी क्षेत्रों में बीपीएल परिवारों को पक्का मकान बनाने के लिए ₹1.5 लाख अनुदान" },
    tag:     { en: "Housing", hi: "आवास" },
    annual: 150000,
    apply:   { en: "himachal.nic.in", hi: "himachal.nic.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card","BPL Certificate","Land Ownership Proof","HP Domicile Certificate","Bank Account","Photograph of Existing House"],
               hi: ["आधार कार्ड","बीपीएल प्रमाण पत्र","भूमि स्वामित्व प्रमाण","हिमाचल अधिवास प्रमाण","बैंक खाता","मौजूदा घर की फोटो"] },
    match: (a) => a.state === "Himachal Pradesh" && ["no","kutcha"].includes(a.house) && ["below1","1to3"].includes(a.income),
  },

  {
    id: "hp_indira_gandhi_scholarship",
    icon: "📚", color: "#1D4ED8", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Higher Education Dept.", hi: "हिमाचल प्रदेश उच्च शिक्षा विभाग" },
    name:    { en: "Indira Gandhi Utkrisht Chatravriti Yojana",                   hi: "इंदिरा गांधी उत्कृष्ट छात्रवृत्ति योजना" },
    benefit: { en: "₹10,000/year scholarship for meritorious students from low-income HP families pursuing higher education", hi: "उच्च शिक्षा प्राप्त कर रहे कम आय वाले HP परिवारों के मेधावी छात्रों को ₹10,000/वर्ष छात्रवृत्ति" },
    tag:     { en: "Education", hi: "शिक्षा" },
    annual: 10000,
    apply:   { en: "https://scholarships.gov.in", hi: "scholarships.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Mark Sheets (Class 10 & 12)","Income Certificate (below ₹2 Lakh/year)","HP Domicile Certificate","College Admission Proof","Bank Account"],
               hi: ["आधार कार्ड","मार्कशीट (कक्षा 10 और 12)","आय प्रमाण पत्र (₹2 लाख/वर्ष से कम)","हिमाचल अधिवास प्रमाण","कॉलेज प्रवेश प्रमाण","बैंक खाता"] },
    match: (a) => a.state === "Himachal Pradesh" && a.who === "student" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "hp_kheti_suraksha",
    icon: "🌾", color: "#15803D", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Agriculture Dept.", hi: "हिमाचल प्रदेश कृषि विभाग" },
    name:    { en: "Mukhya Mantri Kheti Suraksha Yojana",                              hi: "मुख्यमंत्री खेती सुरक्षा योजना" },
    benefit: { en: "Up to ₹17,000/bigha subsidy on fencing to protect crops from wild animals", hi: "जंगली जानवरों से फसल बचाने के लिए बाड़ लगाने पर ₹17,000/बीघा तक सब्सिडी" },
    tag:     { en: "Farmer", hi: "किसान" },
    annual: 17000,
    apply:   { en: "hpagriculture.gov.in", hi: "hpagriculture.gov.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card","Land Records (Khasra/Khatauni)","HP Domicile Certificate","Bank Account","Photograph of Farm Land"],
               hi: ["आधार कार्ड","भूमि अभिलेख (खसरा/खतौनी)","हिमाचल अधिवास प्रमाण","बैंक खाता","कृषि भूमि की फोटो"] },
    match: (a) => a.state === "Himachal Pradesh" && a.who === "farmer",
  },

  {
    id: "hp_solar_pump",
    icon: "☀️", color: "#CA8A04", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Energy Dept. / HPSEBL", hi: "हिमाचल प्रदेश ऊर्जा विभाग / HPSEBL" },
    name:    { en: "HP Solar Water Pump Scheme",                                hi: "हिमाचल प्रदेश सौर जल पंप योजना" },
    benefit: { en: "70–80% subsidy on solar water pumps (2–10 HP) for irrigation", hi: "सिंचाई के लिए सौर जल पंप (2–10 HP) पर 70–80% सब्सिडी" },
    tag:     { en: "Farmer", hi: "किसान" },
    annual: 0,
    apply:   { en: "https://hpenergy.gov.in", hi: "hpenergy.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Land Records","HP Domicile Certificate","Bank Account","Electricity Bill / No-Electricity Connection Proof"],
               hi: ["आधार कार्ड","भूमि अभिलेख","हिमाचल अधिवास प्रमाण","बैंक खाता","बिजली बिल / बिजली कनेक्शन न होने का प्रमाण"] },
    match: (a) => a.state === "Himachal Pradesh" && a.who === "farmer" && a.area === "rural",
  },

  {
    id: "hp_disabled_pension",
    icon: "♿", color: "#DC2626", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Social Justice & Empowerment Dept.", hi: "हिमाचल प्रदेश सामाजिक न्याय एवं अधिकारिता विभाग" },
    name:    { en: "HP Disability Pension Yojana",                        hi: "हिमाचल प्रदेश विकलांगता पेंशन योजना" },
    benefit: { en: "₹1,500/month pension for persons with ≥40% disability from low-income families", hi: "कम आय वाले ≥40% विकलांग व्यक्तियों को ₹1,500/माह पेंशन" },
    tag:     { en: "Pension", hi: "पेंशन" },
    annual: 18000,
    apply:   { en: "https://hpsocialjustice.gov.in", hi: "hpsocialjustice.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Disability Certificate (≥40% from CMO)","Income Certificate (below ₹35,000/year)","HP Domicile Certificate","Bank Account","Passport Size Photo"],
               hi: ["आधार कार्ड","विकलांगता प्रमाण पत्र (CMO से ≥40%)","आय प्रमाण (₹35,000/वर्ष से कम)","हिमाचल अधिवास प्रमाण","बैंक खाता","पासपोर्ट साइज फोटो"] },
    match: (a) => a.state === "Himachal Pradesh" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "hp_sc_post_matric",
    icon: "🎓", color: "#1E40AF", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Welfare of SC, OBC & Minorities Dept.", hi: "हिमाचल प्रदेश अनुसूचित जाति, ओबीसी एवं अल्पसंख्यक विभाग" },
    name:    { en: "Post-Matric Scholarship for SC/ST Students (HP)",               hi: "अनुसूचित जाति/जनजाति छात्रों के लिए मैट्रिकोत्तर छात्रवृत्ति (हिमाचल प्रदेश)" },
    benefit: { en: "Full tuition fee reimbursement + maintenance allowance up to ₹1,200/month for SC/ST students in Class 11 and above", hi: "कक्षा 11 और उससे ऊपर के SC/ST छात्रों को पूर्ण शिक्षण शुल्क + ₹1,200/माह रखरखाव भत्ता" },
    tag:     { en: "Education", hi: "शिक्षा" },
    annual: 14400,
    apply:   { en: "https://scholarships.gov.in", hi: "scholarships.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Caste Certificate (SC/ST)","Mark Sheets","Income Certificate (below ₹2.5 Lakh/year)","HP Domicile Certificate","College / School Enrollment Proof","Bank Account"],
               hi: ["आधार कार्ड","जाति प्रमाण पत्र (SC/ST)","मार्कशीट","आय प्रमाण पत्र (₹2.5 लाख/वर्ष से कम)","हिमाचल अधिवास प्रमाण","कॉलेज/स्कूल नामांकन प्रमाण","बैंक खाता"] },
    match: (a) => a.state === "Himachal Pradesh" && a.who === "student" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "hp_kaushal_vikas",
    icon: "🛠️", color: "#0369A1", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Skill Development Dept.", hi: "हिमाचल प्रदेश कौशल विकास विभाग" },
    name:    { en: "HP Kaushal Vikas Yojana",                                     hi: "हिमाचल प्रदेश कौशल विकास योजना" },
    benefit: { en: "Free vocational/skill training + ₹1,000/month stipend + placement assistance for youth (18–35 years)", hi: "18–35 वर्ष के युवाओं को निःशुल्क व्यावसायिक प्रशिक्षण + ₹1,000/माह वजीफा + नौकरी सहायता" },
    tag:     { en: "Business", hi: "व्यापार" },
    annual: 12000,
    apply:   { en: "https://hpkvn.gov.in", hi: "hpkvn.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","HP Domicile Certificate","Educational Certificate (Min. Class 8)","Age Proof (18–35 years)","Passport Size Photo","Bank Account"],
               hi: ["आधार कार्ड","हिमाचल अधिवास प्रमाण","शैक्षणिक प्रमाण पत्र (न्यूनतम कक्षा 8)","आयु प्रमाण (18–35 वर्ष)","पासपोर्ट साइज फोटो","बैंक खाता"] },
    match: (a) => a.state === "Himachal Pradesh" && ["18to35"].includes(a.age),
  },

  {
    id: "hp_nari_shakti",
    icon: "🤝", color: "#BE185D", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Women & Child Development Dept.", hi: "हिमाचल प्रदेश महिला एवं बाल विकास विभाग" },
    name:    { en: "Nari Shakti Yojana (HP)",                                 hi: "नारी शक्ति योजना (हिमाचल प्रदेश)" },
    benefit: { en: "Interest-free / low-interest loans up to ₹1 Lakh for women Self-Help Groups (SHGs) + free skill training", hi: "महिला स्वयं सहायता समूहों (SHG) को ₹1 लाख तक ब्याज-मुक्त / कम ब्याज ऋण + निःशुल्क कौशल प्रशिक्षण" },
    tag:     { en: "Women", hi: "महिला" },
    annual: 0,
    apply:   { en: "himachal.nic.in", hi: "himachal.nic.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card","SHG Registration Certificate","HP Domicile Certificate","Bank Account (SHG Account)","Income Certificate","Group Meeting Records"],
               hi: ["आधार कार्ड","SHG पंजीकरण प्रमाण पत्र","हिमाचल अधिवास प्रमाण","बैंक खाता (SHG खाता)","आय प्रमाण पत्र","समूह बैठक अभिलेख"] },
    match: (a) => a.state === "Himachal Pradesh" && a.who === "women" && ["below1","1to3","3to6"].includes(a.income),
  },

  {
    id: "hp_mukhyamantri_bal_uddhar",
    icon: "🧒", color: "#D97706", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Women & Child Development Dept.", hi: "हिमाचल प्रदेश महिला एवं बाल विकास विभाग" },
    name:    { en: "Mukhya Mantri Bal Uddhar Yojana",                        hi: "मुख्यमंत्री बाल उद्धार योजना" },
    benefit: { en: "₹1,500/month cash support for orphan/destitute children under 18 from BPL families", hi: "बीपीएल परिवारों के 18 वर्ष से कम अनाथ/निराश्रित बच्चों को ₹1,500/माह नकद सहायता" },
    tag:     { en: "Women", hi: "महिला" },
    annual: 18000,
    apply:   { en: "hpsocialjustice.gov.in", hi: "hpsocialjustice.gov.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card (Guardian)","Birth Certificate of Child","Death / Abandonment Certificate of Parents","BPL Certificate","HP Domicile Certificate","Bank Account"],
               hi: ["आधार कार्ड (अभिभावक)","बच्चे का जन्म प्रमाण पत्र","माता/पिता का मृत्यु/परित्याग प्रमाण पत्र","बीपीएल प्रमाण पत्र","हिमाचल अधिवास प्रमाण","बैंक खाता"] },
    match: (a) => a.state === "Himachal Pradesh" && a.age === "below18" && a.income === "below1",
  },

  {
    id: "hp_mgnregs_hp",
    icon: "⛏️", color: "#92400E", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Rural Development Dept.", hi: "हिमाचल प्रदेश ग्रामीण विकास विभाग" },
    name:    { en: "MGNREGS – Himachal Pradesh (Enhanced Wages)",               hi: "मनरेगा – हिमाचल प्रदेश (उन्नत मजदूरी)" },
    benefit: { en: "100 days guaranteed wage employment per year at ₹300+/day (HP-enhanced rate); rural households", hi: "ग्रामीण परिवारों को प्रतिवर्ष 100 दिन की गारंटीकृत मजदूरी ₹300+/दिन (HP उन्नत दर)" },
    tag:     { en: "Farmer", hi: "किसान" },
    annual: 30000,
    apply:   { en: "nrega.nic.in", hi: "nrega.nic.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card","Job Card (MGNREGA)","Bank Account","HP Domicile Certificate","Ration Card"],
               hi: ["आधार कार्ड","जॉब कार्ड (मनरेगा)","बैंक खाता","हिमाचल अधिवास प्रमाण","राशन कार्ड"] },
    match: (a) => a.state === "Himachal Pradesh" && a.area === "rural" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "hp_ek_bigha",
    icon: "🌿", color: "#166534", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Rural Development & Panchayati Raj Dept.", hi: "हिमाचल प्रदेश ग्रामीण विकास एवं पंचायती राज विभाग" },
    name:    { en: "Mukhya Mantri Ek Bigha Yojana",                                  hi: "मुख्यमंत्री एक बीघा योजना" },
    benefit: { en: "₹1,500/month wage + up to ₹1 Lakh for water conservation work on own land for rural women", hi: "ग्रामीण महिलाओं को अपनी जमीन पर जल संरक्षण कार्य के लिए ₹1,500/माह मजदूरी + ₹1 लाख तक" },
    tag:     { en: "Women", hi: "महिला" },
    annual: 18000,
    apply:   { en: "nrega.nic.in", hi: "nrega.nic.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card","MGNREGA Job Card","Land Records (Khasra)","HP Domicile Certificate","Bank Account","SHG / Gram Panchayat Membership Proof"],
               hi: ["आधार कार्ड","मनरेगा जॉब कार्ड","भूमि अभिलेख (खसरा)","हिमाचल अधिवास प्रमाण","बैंक खाता","SHG / ग्राम पंचायत सदस्यता प्रमाण"] },
    match: (a) => a.state === "Himachal Pradesh" && a.who === "women" && a.area === "rural",
  },

  {
    id: "hp_bagwani_vikas",
    icon: "🍎", color: "#B91C1C", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Horticulture Dept.", hi: "हिमाचल प्रदेश बागवानी विभाग" },
    name:    { en: "HP Horticulture Development Scheme",                           hi: "हिमाचल प्रदेश बागवानी विकास योजना" },
    benefit: { en: "50% subsidy on planting material, anti-hail nets & drip irrigation for apple/fruit farmers", hi: "सेब/फल किसानों को रोपण सामग्री, एंटी-हेल नेट और ड्रिप सिंचाई पर 50% सब्सिडी" },
    tag:     { en: "Farmer", hi: "किसान" },
    annual: 0,
    apply:   { en: "hpagrisnet.gov.in", hi: "hpagrisnet.gov.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card","Land Records (Khasra/Khatauni)","HP Domicile Certificate","Bank Account","Horticulture Dept. Registration","Photograph of Orchard / Farm"],
               hi: ["आधार कार्ड","भूमि अभिलेख (खसरा/खतौनी)","हिमाचल अधिवास प्रमाण","बैंक खाता","बागवानी विभाग पंजीकरण","बगीचे/खेत की फोटो"] },
    match: (a) => a.state === "Himachal Pradesh" && a.who === "farmer",
  },

  {
    id: "hp_cm_medical_relief",
    icon: "🏨", color: "#0369A1", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Health & Family Welfare Dept.", hi: "हिमाचल प्रदेश स्वास्थ्य एवं परिवार कल्याण विभाग" },
    name:    { en: "Chief Minister's Medical Relief Fund (HP)",              hi: "मुख्यमंत्री चिकित्सा राहत कोष (हिमाचल प्रदेश)" },
    benefit: { en: "Up to ₹2 Lakh one-time financial aid for treatment of serious/life-threatening illness not covered by other schemes", hi: "अन्य योजनाओं से न मिलने वाली गंभीर बीमारी के इलाज के लिए ₹2 लाख तक एकमुश्त सहायता" },
    tag:     { en: "Health", hi: "स्वास्थ्य" },
    annual: 200000,
    apply:   { en: "himachal.nic.in", hi: "himachal.nic.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card","Medical Certificate from Government Hospital","Treatment Cost Estimate","Income Certificate","HP Domicile Certificate","Bank Account"],
               hi: ["आधार कार्ड","सरकारी अस्पताल से चिकित्सा प्रमाण पत्र","उपचार लागत अनुमान","आय प्रमाण पत्र","हिमाचल अधिवास प्रमाण","बैंक खाता"] },
    match: (a) => a.state === "Himachal Pradesh" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "hp_obc_scholarship",
    icon: "📖", color: "#1D4ED8", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Welfare of SC, OBC & Minorities Dept.", hi: "हिमाचल प्रदेश अनुसूचित जाति, ओबीसी एवं अल्पसंख्यक विभाग" },
    name:    { en: "Post-Matric Scholarship for OBC Students (HP)",               hi: "ओबीसी छात्रों के लिए मैट्रिकोत्तर छात्रवृत्ति (हिमाचल प्रदेश)" },
    benefit: { en: "Tuition fee reimbursement + maintenance allowance up to ₹1,000/month for OBC students in Class 11 and above", hi: "कक्षा 11 और उससे ऊपर के OBC छात्रों को शिक्षण शुल्क + ₹1,000/माह रखरखाव भत्ता" },
    tag:     { en: "Education", hi: "शिक्षा" },
    annual: 12000,
    apply:   { en: "https://scholarships.gov.in", hi: "scholarships.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","OBC Certificate (Non-Creamy Layer)","Mark Sheets","Income Certificate (below ₹1 Lakh/year)","HP Domicile Certificate","College / School Enrollment Proof","Bank Account"],
               hi: ["आधार कार्ड","ओबीसी प्रमाण पत्र (नॉन-क्रीमी लेयर)","मार्कशीट","आय प्रमाण पत्र (₹1 लाख/वर्ष से कम)","हिमाचल अधिवास प्रमाण","कॉलेज/स्कूल नामांकन प्रमाण","बैंक खाता"] },
    match: (a) => a.state === "Himachal Pradesh" && a.who === "student" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "hp_startup_policy",
    icon: "🚀", color: "#7C3AED", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Industries Dept. / StartUp Cell", hi: "हिमाचल प्रदेश उद्योग विभाग / स्टार्टअप सेल" },
    name:    { en: "HP StartUp Policy 2019",                              hi: "हिमाचल प्रदेश स्टार्टअप नीति 2019" },
    benefit: { en: "Seed grant up to ₹10 Lakh + 3-year electricity & rent subsidy + mentorship for innovative startups by HP youth", hi: "HP युवाओं के नवाचारी स्टार्टअप को ₹10 लाख तक बीज अनुदान + 3 वर्ष बिजली और किराया सब्सिडी + मेंटरशिप" },
    tag:     { en: "Business", hi: "व्यापार" },
    annual: 0,
    apply:   { en: "https://startup.hp.gov.in", hi: "startup.hp.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","HP Domicile Certificate","Startup Registration (DPIIT / State)","Business Plan / Pitch Deck","Educational Certificates","Bank Account","GST Registration (if applicable)"],
               hi: ["आधार कार्ड","हिमाचल अधिवास प्रमाण","स्टार्टअप पंजीकरण (DPIIT / राज्य)","व्यापार योजना / पिच डेक","शैक्षणिक प्रमाण पत्र","बैंक खाता","GST पंजीकरण (यदि लागू हो)"] },
    match: (a) => a.state === "Himachal Pradesh" && (a.who === "business" || ["18to35","35to60"].includes(a.age)),
  },

  {
    id: "hp_dugdh_utpadan",
    icon: "🐄", color: "#92400E", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Animal Husbandry Dept. / HP Milk Fed", hi: "हिमाचल प्रदेश पशुपालन विभाग / HP मिल्कफेड" },
    name:    { en: "HP Dairy Development & Milk Fed Scheme",                         hi: "हिमाचल प्रदेश दुग्ध विकास एवं मिल्कफेड योजना" },
    benefit: { en: "50% subsidy on purchase of milch cattle + free veterinary care + guaranteed milk procurement at MSP via HP Milk Fed", hi: "दुधारू पशु खरीदने पर 50% सब्सिडी + मुफ्त पशु चिकित्सा + HP मिल्कफेड द्वारा MSP पर दूध खरीद की गारंटी" },
    tag:     { en: "Farmer", hi: "किसान" },
    annual: 0,
    apply:   { en: "hpagrisnet.gov.in", hi: "hpagrisnet.gov.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card","HP Domicile Certificate","Land / Shed Ownership Proof","Bank Account","Income Certificate","Veterinary Dept. Registration"],
               hi: ["आधार कार्ड","हिमाचल अधिवास प्रमाण","जमीन / शेड स्वामित्व प्रमाण","बैंक खाता","आय प्रमाण पत्र","पशु चिकित्सा विभाग पंजीकरण"] },
    match: (a) => a.state === "Himachal Pradesh" && (a.who === "farmer" || a.area === "rural"),
  },

  {
    id: "hp_matsya_palan",
    icon: "🐟", color: "#0369A1", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Fisheries Dept.", hi: "हिमाचल प्रदेश मत्स्य पालन विभाग" },
    name:    { en: "HP Fisheries Development Scheme",                           hi: "हिमाचल प्रदेश मत्स्य पालन विकास योजना" },
    benefit: { en: "40–60% subsidy on fish pond construction, fingerlings, fish feed & fishing equipment for fish farmers", hi: "मछली तालाब निर्माण, अंगुलिकाएं, मछली चारा और उपकरण पर 40–60% सब्सिडी" },
    tag:     { en: "Farmer", hi: "किसान" },
    annual: 0,
    apply:   { en: "hpfisheries.gov.in", hi: "hpfisheries.gov.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card","HP Domicile Certificate","Land Records (for pond site)","Bank Account","HP Fisheries Dept. Registration","Income Certificate"],
               hi: ["आधार कार्ड","हिमाचल अधिवास प्रमाण","भूमि अभिलेख (तालाब स्थल के लिए)","बैंक खाता","HP मत्स्य विभाग पंजीकरण","आय प्रमाण पत्र"] },
    match: (a) => a.state === "Himachal Pradesh" && a.who === "farmer" && a.area === "rural",
  },

  {
    id: "hp_prakritik_kheti",
    icon: "🌱", color: "#15803D", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Agriculture Dept.", hi: "हिमाचल प्रदेश कृषि विभाग" },
    name:    { en: "Prakritik Kheti Khushhal Kisan Yojana",                       hi: "प्राकृतिक खेती खुशहाल किसान योजना" },
    benefit: { en: "₹4,000/year incentive + free training & inputs for farmers switching to natural/zero-budget farming", hi: "प्राकृतिक/शून्य-बजट खेती अपनाने वाले किसानों को ₹4,000/वर्ष प्रोत्साहन + मुफ्त प्रशिक्षण और सामग्री" },
    tag:     { en: "Farmer", hi: "किसान" },
    annual: 4000,
    apply:   { en: "hpagriculture.gov.in", hi: "hpagriculture.gov.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card","Land Records (Khasra)","HP Domicile Certificate","Bank Account","Gram Panchayat Certificate","Training Completion Certificate (after enrolment)"],
               hi: ["आधार कार्ड","भूमि अभिलेख (खसरा)","हिमाचल अधिवास प्रमाण","बैंक खाता","ग्राम पंचायत प्रमाण पत्र","प्रशिक्षण पूर्णता प्रमाण पत्र (नामांकन के बाद)"] },
    match: (a) => a.state === "Himachal Pradesh" && a.who === "farmer",
  },

  {
    id: "hp_grih_murammat",
    icon: "🔧", color: "#B45309", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Social Justice & Empowerment Dept.", hi: "हिमाचल प्रदेश सामाजिक न्याय एवं अधिकारिता विभाग" },
    name:    { en: "Mukhya Mantri Grih Murammat Yojana",                       hi: "मुख्यमंत्री गृह मरम्मत योजना" },
    benefit: { en: "Up to ₹1.5 Lakh grant for repair/renovation of dilapidated house for BPL SC/ST families", hi: "बीपीएल SC/ST परिवारों के जर्जर मकान की मरम्मत/नवीनीकरण के लिए ₹1.5 लाख तक अनुदान" },
    tag:     { en: "Housing", hi: "आवास" },
    annual: 150000,
    apply:   { en: "hpsocialjustice.gov.in", hi: "hpsocialjustice.gov.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card","BPL Certificate","Caste Certificate (SC/ST)","Land / House Ownership Proof","HP Domicile Certificate","Bank Account","Photograph of Damaged House"],
               hi: ["आधार कार्ड","बीपीएल प्रमाण पत्र","जाति प्रमाण पत्र (SC/ST)","जमीन / मकान स्वामित्व प्रमाण","हिमाचल अधिवास प्रमाण","बैंक खाता","क्षतिग्रस्त मकान की फोटो"] },
    match: (a) => a.state === "Himachal Pradesh" && a.house === "kutcha" && a.income === "below1",
  },

  {
    id: "hp_free_uniform_textbook",
    icon: "🎒", color: "#1E40AF", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Elementary Education Dept.", hi: "हिमाचल प्रदेश प्रारंभिक शिक्षा विभाग" },
    name:    { en: "HP Free Uniform & Textbook Scheme",                         hi: "हिमाचल प्रदेश निःशुल्क वर्दी एवं पाठ्यपुस्तक योजना" },
    benefit: { en: "Free textbooks, 2 sets of uniforms & stationery kit every year for all government school students (Class 1–12)", hi: "सरकारी स्कूल के सभी छात्रों (कक्षा 1–12) को हर साल मुफ्त पाठ्यपुस्तकें, 2 वर्दी सेट और स्टेशनरी किट" },
    tag:     { en: "Education", hi: "शिक्षा" },
    annual: 3000,
    apply:   { en: "himachal.nic.in", hi: "himachal.nic.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card (Student)","School Enrollment Certificate","HP Domicile Certificate","Parent's Aadhaar Card"],
               hi: ["आधार कार्ड (छात्र)","स्कूल नामांकन प्रमाण पत्र","हिमाचल अधिवास प्रमाण","माता/पिता का आधार कार्ड"] },
    match: (a) => a.state === "Himachal Pradesh" && a.who === "student" && a.age === "below18",
  },

  {
    id: "hp_e_taxi",
    icon: "🚖", color: "#0F766E", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Transport Dept.", hi: "हिमाचल प्रदेश परिवहन विभाग" },
    name:    { en: "HP e-Taxi Scheme",                                        hi: "हिमाचल प्रदेश ई-टैक्सी योजना" },
    benefit: { en: "50% subsidy (up to ₹50,000) on purchase of electric taxi for unemployed HP youth (18–45 years)", hi: "18–45 वर्ष के बेरोजगार HP युवाओं को इलेक्ट्रिक टैक्सी खरीदने पर 50% सब्सिडी (₹50,000 तक)" },
    tag:     { en: "Business", hi: "व्यापार" },
    annual: 0,
    apply:   { en: "himachal.nic.in", hi: "himachal.nic.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","HP Domicile Certificate","Driving Licence (Commercial)","Age Proof (18–45 years)","Bank Account","Income Certificate","Unemployment Certificate from Employment Exchange"],
               hi: ["आधार कार्ड","हिमाचल अधिवास प्रमाण","ड्राइविंग लाइसेंस (व्यावसायिक)","आयु प्रमाण (18–45 वर्ष)","बैंक खाता","आय प्रमाण पत्र","रोजगार कार्यालय से बेरोजगारी प्रमाण पत्र"] },
    match: (a) => a.state === "Himachal Pradesh" && ["18to35","35to60"].includes(a.age) && ["below1","1to3"].includes(a.income),
  },

  {
    id: "hp_fasal_bima",
    icon: "🌦️", color: "#0369A1", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Agriculture Dept. / State Nodal Agency", hi: "हिमाचल प्रदेश कृषि विभाग / राज्य नोडल एजेंसी" },
    name:    { en: "PM Fasal Bima Yojana – Himachal Pradesh",                      hi: "पीएम फसल बीमा योजना – हिमाचल प्रदेश" },
    benefit: { en: "Crop insurance at 1.5–2% premium for Rabi & Kharif; full coverage against drought, flood, hailstorm & pest damage", hi: "रबी और खरीफ के लिए 1.5–2% प्रीमियम पर फसल बीमा; सूखा, बाढ़, ओलावृष्टि और कीट नुकसान पर पूर्ण कवरेज" },
    tag:     { en: "Farmer", hi: "किसान" },
    annual: 0,
    apply:   { en: "pmfby.gov.in", hi: "pmfby.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Land Records (Khasra/Khatauni)", "Bank Account / Kisan Credit Card", "Sowing Certificate from Patwari", "HP Domicile Certificate"],
               hi: ["आधार कार्ड", "भूमि अभिलेख (खसरा/खतौनी)", "बैंक खाता / किसान क्रेडिट कार्ड", "पटवारी से बुवाई प्रमाण पत्र", "हिमाचल अधिवास प्रमाण"] },
    match: (a) => a.state === "Himachal Pradesh" && a.who === "farmer",
  },

  {
    id: "hp_homestay",
    icon: "🏡", color: "#0F766E", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Tourism & Civil Aviation Dept.", hi: "हिमाचल प्रदेश पर्यटन एवं नागरिक उड्डयन विभाग" },
    name:    { en: "HP Homestay Scheme",                                        hi: "हिमाचल प्रदेश होमस्टे योजना" },
    benefit: { en: "Up to ₹1.5 Lakh one-time grant + interest subsidy on loan for setting up a registered homestay for rural households", hi: "ग्रामीण परिवारों को पंजीकृत होमस्टे शुरू करने के लिए ₹1.5 लाख तक एकमुश्त अनुदान + ऋण पर ब्याज सब्सिडी" },
    tag:     { en: "Business", hi: "व्यापार" },
    annual: 0,
    apply:   { en: "hptdc.in", hi: "hptdc.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "HP Domicile Certificate", "House Ownership Proof", "Bank Account", "NOC from Gram Panchayat", "Photograph of Property", "Tourism Dept. Registration"],
               hi: ["आधार कार्ड", "हिमाचल अधिवास प्रमाण", "मकान स्वामित्व प्रमाण", "बैंक खाता", "ग्राम पंचायत से NOC", "संपत्ति की फोटो", "पर्यटन विभाग पंजीकरण"] },
    match: (a) => a.state === "Himachal Pradesh" && a.area === "rural" && ["below1","1to3","3to6"].includes(a.income),
  },

  {
    id: "hp_bus_pass",
    icon: "🚌", color: "#1D4ED8", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Transport Dept. / HRTC", hi: "हिमाचल प्रदेश परिवहन विभाग / HRTC" },
    name:    { en: "HP Free / Subsidised Bus Pass Scheme",                     hi: "हिमाचल प्रदेश निःशुल्क / रियायती बस पास योजना" },
    benefit: { en: "Free HRTC bus travel for students (Class 1–12 in govt schools) and 50% concession for senior citizens & disabled persons", hi: "सरकारी स्कूल के छात्रों (कक्षा 1–12) को मुफ्त HRTC बस यात्रा और वरिष्ठ नागरिकों व विकलांगों को 50% छूट" },
    tag:     { en: "Education", hi: "शिक्षा" },
    annual: 3600,
    apply:   { en: "hrtc.gov.in", hi: "hrtc.gov.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "School / College ID Card", "HP Domicile Certificate", "Age Proof (for seniors)", "Disability Certificate (for disabled)"],
               hi: ["आधार कार्ड", "स्कूल / कॉलेज आईडी कार्ड", "हिमाचल अधिवास प्रमाण", "आयु प्रमाण (वरिष्ठ नागरिकों के लिए)", "विकलांगता प्रमाण पत्र (विकलांगों के लिए)"] },
    match: (a) => a.state === "Himachal Pradesh" && (a.who === "student" || a.who === "senior"),
  },

  {
    id: "hp_bocw_welfare",
    icon: "👷", color: "#B45309", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Labour & Employment Dept. / HP BOCW Board", hi: "हिमाचल प्रदेश श्रम एवं रोजगार विभाग / HP BOCW बोर्ड" },
    name:    { en: "HP Building & Construction Workers Welfare Scheme",          hi: "हिमाचल प्रदेश भवन एवं निर्माण श्रमिक कल्याण योजना" },
    benefit: { en: "₹2,000/month pension after 60 + ₹1 Lakh accident cover + maternity benefit + child scholarship for registered construction workers", hi: "पंजीकृत निर्माण श्रमिकों को 60 वर्ष के बाद ₹2,000/माह पेंशन + ₹1 लाख दुर्घटना बीमा + प्रसूति लाभ + बच्चों की छात्रवृत्ति" },
    tag:     { en: "Insurance", hi: "बीमा" },
    annual: 24000,
    apply:   { en: "hplabour.gov.in", hi: "hplabour.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Proof of Construction Work (90 days in a year)", "HP Domicile Certificate", "Bank Account", "Passport Size Photo", "Age Proof"],
               hi: ["आधार कार्ड", "निर्माण कार्य का प्रमाण (वर्ष में 90 दिन)", "हिमाचल अधिवास प्रमाण", "बैंक खाता", "पासपोर्ट साइज फोटो", "आयु प्रमाण"] },
    match: (a) => a.state === "Himachal Pradesh" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "hp_mushroom_beekeeping",
    icon: "🍄", color: "#166534", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Horticulture Dept.", hi: "हिमाचल प्रदेश बागवानी विभाग" },
    name:    { en: "HP Mushroom & Beekeeping Development Scheme",                 hi: "हिमाचल प्रदेश मशरूम एवं मधुमक्खी पालन विकास योजना" },
    benefit: { en: "50% subsidy on mushroom spawn, growing chambers & beehive kits + free 5-day training for rural farmers and youth", hi: "ग्रामीण किसानों और युवाओं को मशरूम बीज, उगाने के कमरे और मधुमक्खी के छत्ते के उपकरण पर 50% सब्सिडी + मुफ्त 5-दिवसीय प्रशिक्षण" },
    tag:     { en: "Farmer", hi: "किसान" },
    annual: 0,
    apply:   { en: "hpagrisnet.gov.in", hi: "hpagrisnet.gov.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "HP Domicile Certificate", "Land / Room Availability Proof", "Bank Account", "Income Certificate"],
               hi: ["आधार कार्ड", "हिमाचल अधिवास प्रमाण", "जमीन / कमरा उपलब्धता प्रमाण", "बैंक खाता", "आय प्रमाण पत्र"] },
    match: (a) => a.state === "Himachal Pradesh" && (a.who === "farmer" || ["18to35","35to60"].includes(a.age)) && ["below1","1to3"].includes(a.income),
  },

  {
    id: "hp_apda_rahat",
    icon: "🆘", color: "#DC2626", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Revenue Dept. / State Disaster Management Authority", hi: "हिमाचल प्रदेश राजस्व विभाग / राज्य आपदा प्रबंधन प्राधिकरण" },
    name:    { en: "HP State Disaster Relief Fund (SDRF)",                      hi: "हिमाचल प्रदेश राज्य आपदा राहत कोष (SDRF)" },
    benefit: { en: "Immediate financial aid: ₹95,100 for house fully damaged + ₹4,100/month for up to 3 months relief + cattle/crop loss compensation after flood, landslide or earthquake", hi: "बाढ़, भूस्खलन या भूकंप के बाद पूर्ण मकान नष्ट होने पर ₹95,100 + 3 माह तक ₹4,100/माह राहत + पशु/फसल नुकसान मुआवजा" },
    tag:     { en: "Insurance", hi: "बीमा" },
    annual: 95100,
    apply:   { en: "hpsdma.nic.in", hi: "hpsdma.nic.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "HP Domicile Certificate", "Patwari / SDM Damage Assessment Report", "Bank Account", "FIR / Tehsil Office Report", "Photograph of Damage"],
               hi: ["आधार कार्ड", "हिमाचल अधिवास प्रमाण", "पटवारी / SDM नुकसान आकलन रिपोर्ट", "बैंक खाता", "FIR / तहसील कार्यालय रिपोर्ट", "नुकसान की फोटो"] },
    match: (a) => a.state === "Himachal Pradesh",
  },

  {
    id: "hp_udaan",
    icon: "🌸", color: "#BE185D", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Women & Child Development Dept.", hi: "हिमाचल प्रदेश महिला एवं बाल विकास विभाग" },
    name:    { en: "Udaan Scheme – Free Sanitary Napkins (HP)",                   hi: "उड़ान योजना – निःशुल्क सैनिटरी नैपकिन (हिमाचल प्रदेश)" },
    benefit: { en: "Free sanitary napkins every month to all girl students (Class 6–12) in government schools across HP", hi: "हिमाचल प्रदेश के सरकारी स्कूलों में कक्षा 6–12 की सभी छात्राओं को हर माह निःशुल्क सैनिटरी नैपकिन" },
    tag:     { en: "Women", hi: "महिला" },
    annual: 600,
    apply:   { en: "himachal.nic.in", hi: "himachal.nic.in" }, applyType: "offline",
    docs:    { en: ["School Enrollment Certificate", "Aadhaar Card (Student)", "HP Domicile Certificate"],
               hi: ["स्कूल नामांकन प्रमाण पत्र", "आधार कार्ड (छात्रा)", "हिमाचल अधिवास प्रमाण"] },
    match: (a) => a.state === "Himachal Pradesh" && a.who === "women" && a.age === "below18",
  },

  {
    id: "hp_ex_servicemen",
    icon: "🎖️", color: "#1E3A5F", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Sainik Welfare Dept.", hi: "हिमाचल प्रदेश सैनिक कल्याण विभाग" },
    name:    { en: "HP Ex-Servicemen Welfare & Resettlement Scheme",              hi: "हिमाचल प्रदेश भूतपूर्व सैनिक कल्याण एवं पुनर्वास योजना" },
    benefit: { en: "₹50,000 one-time resettlement grant + priority in govt jobs + free education for children + HP State Transport concession for ex-servicemen & widows", hi: "भूतपूर्व सैनिकों और विधवाओं को ₹50,000 एकमुश्त पुनर्वास अनुदान + सरकारी नौकरी में प्राथमिकता + बच्चों की मुफ्त शिक्षा + HP बस रियायत" },
    tag:     { en: "Pension", hi: "पेंशन" },
    annual: 50000,
    apply:   { en: "sainikwelfare.hp.gov.in", hi: "sainikwelfare.hp.gov.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "Discharge Certificate / Service Book", "HP Domicile Certificate", "Bank Account", "Dependent Family Certificate", "Death Certificate (for widows)"],
               hi: ["आधार कार्ड", "डिस्चार्ज सर्टिफिकेट / सेवा पुस्तक", "हिमाचल अधिवास प्रमाण", "बैंक खाता", "आश्रित परिवार प्रमाण पत्र", "मृत्यु प्रमाण पत्र (विधवाओं के लिए)"] },
    match: (a) => a.state === "Himachal Pradesh" && ["35to60","above60"].includes(a.age),
  },

  {
    id: "hp_handicraft_handloom",
    icon: "🧵", color: "#92400E", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Industry Dept. / HP Handicrafts & Handloom Corp.", hi: "हिमाचल प्रदेश उद्योग विभाग / HP हस्तशिल्प एवं हथकरघा निगम" },
    name:    { en: "HP Handicraft & Handloom Development Scheme",                  hi: "हिमाचल प्रदेश हस्तशिल्प एवं हथकरघा विकास योजना" },
    benefit: { en: "50% subsidy on loom/tool purchase + free skill training + e-commerce marketing support for weavers & artisans", hi: "बुनकरों और कारीगरों को करघे/औजार खरीद पर 50% सब्सिडी + निःशुल्क कौशल प्रशिक्षण + ई-कॉमर्स विपणन सहायता" },
    tag:     { en: "Business", hi: "व्यापार" },
    annual: 0,
    apply:   { en: "hpkvib.gov.in", hi: "hpkvib.gov.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "HP Domicile Certificate", "Artisan Card / Weaver Registration", "Bank Account", "Caste Certificate (if applicable)", "Proof of Craft Activity"],
               hi: ["आधार कार्ड", "हिमाचल अधिवास प्रमाण", "कारीगर कार्ड / बुनकर पंजीकरण", "बैंक खाता", "जाति प्रमाण पत्र (यदि लागू हो)", "शिल्प गतिविधि का प्रमाण"] },
    match: (a) => a.state === "Himachal Pradesh" && ["below1","1to3","3to6"].includes(a.income),
  },

  {
    id: "hp_minority_scholarship",
    icon: "📝", color: "#1D4ED8", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Welfare of SC, OBC & Minorities Dept.", hi: "हिमाचल प्रदेश अनुसूचित जाति, ओबीसी एवं अल्पसंख्यक विभाग" },
    name:    { en: "Pre-Matric Scholarship for Minority Students (HP)",           hi: "अल्पसंख्यक छात्रों के लिए प्री-मैट्रिक छात्रवृत्ति (हिमाचल प्रदेश)" },
    benefit: { en: "₹1,000/month maintenance allowance + full fees for Class 1–10 minority community students from low-income families", hi: "कम आय वाले अल्पसंख्यक समुदाय के कक्षा 1–10 छात्रों को ₹1,000/माह रखरखाव भत्ता + पूर्ण शुल्क" },
    tag:     { en: "Education", hi: "शिक्षा" },
    annual: 12000,
    apply:   { en: "scholarships.gov.in", hi: "scholarships.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Minority Community Certificate (Muslim/Sikh/Christian/Buddhist/Jain/Parsi)", "Income Certificate (below ₹1 Lakh/year)", "Mark Sheets", "HP Domicile Certificate", "School Enrollment Proof", "Bank Account"],
               hi: ["आधार कार्ड", "अल्पसंख्यक समुदाय प्रमाण पत्र (मुस्लिम/सिख/ईसाई/बौद्ध/जैन/पारसी)", "आय प्रमाण पत्र (₹1 लाख/वर्ष से कम)", "मार्कशीट", "हिमाचल अधिवास प्रमाण", "स्कूल नामांकन प्रमाण", "बैंक खाता"] },
    match: (a) => a.state === "Himachal Pradesh" && a.who === "student" && a.income === "below1",
  },

  {
    id: "hp_free_coaching",
    icon: "🏆", color: "#7C3AED", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Social Justice & Empowerment Dept.", hi: "हिमाचल प्रदेश सामाजिक न्याय एवं अधिकारिता विभाग" },
    name:    { en: "HP Free Coaching for Competitive Exams",                      hi: "हिमाचल प्रदेश प्रतियोगी परीक्षाओं के लिए निःशुल्क कोचिंग" },
    benefit: { en: "Free coaching for UPSC, HP Administrative Services, Banking, SSC & JEE/NEET for SC/ST/OBC/EWS youth with ₹1,500/month stipend", hi: "SC/ST/OBC/EWS युवाओं को UPSC, HP प्रशासनिक सेवा, बैंकिंग, SSC और JEE/NEET की मुफ्त कोचिंग + ₹1,500/माह वजीफा" },
    tag:     { en: "Education", hi: "शिक्षा" },
    annual: 18000,
    apply:   { en: "hpsocialjustice.gov.in", hi: "hpsocialjustice.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "HP Domicile Certificate", "Caste Certificate (SC/ST/OBC) or EWS Certificate", "Educational Certificates (Graduation)", "Income Certificate (below ₹2.5 Lakh/year)", "Bank Account"],
               hi: ["आधार कार्ड", "हिमाचल अधिवास प्रमाण", "जाति प्रमाण पत्र (SC/ST/OBC) या EWS प्रमाण पत्र", "शैक्षणिक प्रमाण पत्र (स्नातक)", "आय प्रमाण पत्र (₹2.5 लाख/वर्ष से कम)", "बैंक खाता"] },
    match: (a) => a.state === "Himachal Pradesh" && a.who === "student" && ["18to35"].includes(a.age) && ["below1","1to3"].includes(a.income),
  },

  {
    id: "hp_jal_jeevan",
    icon: "🚰", color: "#0369A1", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Jal Shakti Dept.", hi: "हिमाचल प्रदेश जल शक्ति विभाग" },
    name:    { en: "Jal Jeevan Mission – Himachal Pradesh",                       hi: "जल जीवन मिशन – हिमाचल प्रदेश" },
    benefit: { en: "Free tap water connection (Har Ghar Jal) to every rural household with 55 litres per person per day supply guarantee", hi: "हर ग्रामीण घर को मुफ्त नल जल कनेक्शन (हर घर जल) + प्रतिदिन प्रति व्यक्ति 55 लीटर पानी की आपूर्ति की गारंटी" },
    tag:     { en: "Free Benefits", hi: "मुफ़्त लाभ" },
    annual: 0,
    apply:   { en: "jaljeevanmission.gov.in", hi: "jaljeevanmission.gov.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "HP Domicile Certificate", "Proof of Rural Residence (Gram Panchayat Certificate)", "House Ownership / Rent Agreement"],
               hi: ["आधार कार्ड", "हिमाचल अधिवास प्रमाण", "ग्रामीण निवास का प्रमाण (ग्राम पंचायत प्रमाण पत्र)", "मकान स्वामित्व / किराया समझौता"] },
    match: (a) => a.state === "Himachal Pradesh" && a.area === "rural",
  },

  {
    id: "hp_free_electricity",
    icon: "⚡", color: "#CA8A04", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Energy Dept. / HPSEBL", hi: "हिमाचल प्रदेश ऊर्जा विभाग / HPSEBL" },
    name:    { en: "HP Free Electricity Scheme (BPL Households)",                 hi: "हिमाचल प्रदेश निःशुल्क बिजली योजना (BPL परिवार)" },
    benefit: { en: "125 units of free electricity every month for BPL households with a single-phase connection in Himachal Pradesh", hi: "हिमाचल प्रदेश में सिंगल-फेज कनेक्शन वाले BPL परिवारों को हर माह 125 यूनिट मुफ्त बिजली" },
    tag:     { en: "Free Benefits", hi: "मुफ़्त लाभ" },
    annual: 0,
    apply:   { en: "hpsebl.org", hi: "hpsebl.org" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "BPL Certificate / Ration Card", "Electricity Connection Number", "HP Domicile Certificate", "Bank Account"],
               hi: ["आधार कार्ड", "बीपीएल प्रमाण पत्र / राशन कार्ड", "बिजली कनेक्शन नंबर", "हिमाचल अधिवास प्रमाण", "बैंक खाता"] },
    match: (a) => a.state === "Himachal Pradesh" && a.income === "below1",
  },

  {
    id: "hp_tunnel_farming",
    icon: "🥦", color: "#15803D", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Agriculture Dept.", hi: "हिमाचल प्रदेश कृषि विभाग" },
    name:    { en: "HP Poly / Low Tunnel Farming Scheme",                          hi: "हिमाचल प्रदेश पॉली / लो टनल खेती योजना" },
    benefit: { en: "50% subsidy on poly tunnel / low tunnel installation for off-season vegetable cultivation in hilly areas", hi: "पहाड़ी क्षेत्रों में बेमौसमी सब्जी उत्पादन के लिए पॉली टनल / लो टनल लगाने पर 50% सब्सिडी" },
    tag:     { en: "Farmer", hi: "किसान" },
    annual: 0,
    apply:   { en: "hpagriculture.gov.in", hi: "hpagriculture.gov.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "Land Records (Khasra)", "HP Domicile Certificate", "Bank Account", "Agriculture Dept. Registration", "Photograph of Farm"],
               hi: ["आधार कार्ड", "भूमि अभिलेख (खसरा)", "हिमाचल अधिवास प्रमाण", "बैंक खाता", "कृषि विभाग पंजीकरण", "खेत की फोटो"] },
    match: (a) => a.state === "Himachal Pradesh" && a.who === "farmer",
  },

  {
    id: "hp_tribal_development",
    icon: "🏔️", color: "#78350F", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Tribal Development Dept.", hi: "हिमाचल प्रदेश जनजातीय विकास विभाग" },
    name:    { en: "HP Tribal Sub-Plan & Special Development Scheme",              hi: "हिमाचल प्रदेश जनजातीय उप-योजना एवं विशेष विकास योजना" },
    benefit: { en: "Exclusive grants for ST communities: free housing, sheep/yak rearing subsidy, free winter clothing kit & educational stipend for tribal students in Lahaul-Spiti, Kinnaur & Pangi", hi: "ST समुदायों के लिए: मुफ्त आवास, भेड़/याक पालन सब्सिडी, मुफ्त शीतकालीन वस्त्र किट और लाहौल-स्पीति, किन्नौर व पांगी के जनजातीय छात्रों के लिए शैक्षिक वजीफा" },
    tag:     { en: "Free Benefits", hi: "मुफ़्त लाभ" },
    annual: 0,
    apply:   { en: "himachal.nic.in", hi: "himachal.nic.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "Scheduled Tribe Certificate", "HP Domicile Certificate", "Residence Proof in Tribal Area", "Bank Account", "Income Certificate"],
               hi: ["आधार कार्ड", "अनुसूचित जनजाति प्रमाण पत्र", "हिमाचल अधिवास प्रमाण", "जनजातीय क्षेत्र में निवास प्रमाण", "बैंक खाता", "आय प्रमाण पत्र"] },
    match: (a) => a.state === "Himachal Pradesh" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "hp_free_laptop",
    icon: "💻", color: "#1D4ED8", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Education Dept.", hi: "हिमाचल प्रदेश शिक्षा विभाग" },
    name:    { en: "HP Free Laptop / Tablet Scheme for Meritorious Students",      hi: "हिमाचल प्रदेश मेधावी छात्रों के लिए निःशुल्क लैपटॉप / टैबलेट योजना" },
    benefit: { en: "Free laptop or tablet for students scoring 80%+ in Class 10 / Class 12 board exams from government schools in HP", hi: "HP के सरकारी स्कूलों में कक्षा 10 / 12 की बोर्ड परीक्षा में 80%+ अंक लाने वाले छात्रों को मुफ्त लैपटॉप या टैबलेट" },
    tag:     { en: "Education", hi: "शिक्षा" },
    annual: 0,
    apply:   { en: "himachal.nic.in", hi: "himachal.nic.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "Class 10 / 12 Mark Sheet (80%+ score)", "Government School Enrollment Certificate", "HP Domicile Certificate", "Income Certificate (below ₹2 Lakh/year)", "Bank Account"],
               hi: ["आधार कार्ड", "कक्षा 10 / 12 की मार्कशीट (80%+ अंक)", "सरकारी स्कूल नामांकन प्रमाण पत्र", "हिमाचल अधिवास प्रमाण", "आय प्रमाण पत्र (₹2 लाख/वर्ष से कम)", "बैंक खाता"] },
    match: (a) => a.state === "Himachal Pradesh" && a.who === "student" && ["below18","18to35"].includes(a.age) && ["below1","1to3"].includes(a.income),
  },

  {
    id: "hp_organic_farming",
    icon: "🌾", color: "#065F46", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Agriculture Dept.", hi: "हिमाचल प्रदेश कृषि विभाग" },
    name:    { en: "HP Organic Farming Certification & Market Support Scheme",      hi: "हिमाचल प्रदेश जैविक खेती प्रमाणन एवं बाजार सहायता योजना" },
    benefit: { en: "Free PGS / third-party organic certification + ₹10,000 input subsidy + direct market linkage for farmers converting to organic farming", hi: "जैविक खेती अपनाने वाले किसानों को मुफ्त PGS / तृतीय पक्ष जैविक प्रमाणन + ₹10,000 इनपुट सब्सिडी + सीधी बाजार लिंकेज" },
    tag:     { en: "Farmer", hi: "किसान" },
    annual: 10000,
    apply:   { en: "hpagriculture.gov.in", hi: "hpagriculture.gov.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "Land Records (Khasra)", "HP Domicile Certificate", "Bank Account", "Soil Health Card", "Gram Panchayat Certificate", "Previous 3-year farming records"],
               hi: ["आधार कार्ड", "भूमि अभिलेख (खसरा)", "हिमाचल अधिवास प्रमाण", "बैंक खाता", "मृदा स्वास्थ्य कार्ड", "ग्राम पंचायत प्रमाण पत्र", "पिछले 3 वर्षों के कृषि अभिलेख"] },
    match: (a) => a.state === "Himachal Pradesh" && a.who === "farmer",
  },

  {
    id: "hp_svanidhi",
    icon: "🛒", color: "#D97706", scope: "state", state: "Himachal Pradesh",
    ministry: { en: "HP Urban Development Dept. / MoHUA", hi: "हिमाचल प्रदेश शहरी विकास विभाग / MoHUA" },
    name:    { en: "PM SVANidhi – Street Vendor Micro-Credit (HP)",                hi: "पीएम स्वनिधि – स्ट्रीट वेंडर माइक्रो-क्रेडिट (हिमाचल प्रदेश)" },
    benefit: { en: "Collateral-free working capital loan: ₹10,000 (1st), ₹20,000 (2nd), ₹50,000 (3rd cycle) + 7% interest subsidy for street vendors in HP towns", hi: "HP के शहरों में स्ट्रीट वेंडरों को बिना गारंटी कार्यशील पूंजी ऋण: ₹10,000 (1st), ₹20,000 (2nd), ₹50,000 (3rd) + 7% ब्याज सब्सिडी" },
    tag:     { en: "Business", hi: "व्यापार" },
    annual: 0,
    apply:   { en: "pmsvanidhi.mohua.gov.in", hi: "pmsvanidhi.mohua.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Vending Certificate / Identity Card from ULB", "HP Domicile Certificate", "Bank Account", "Passport Size Photo", "Mobile Number linked to Aadhaar"],
               hi: ["आधार कार्ड", "ULB से वेंडिंग प्रमाण पत्र / पहचान पत्र", "हिमाचल अधिवास प्रमाण", "बैंक खाता", "पासपोर्ट साइज फोटो", "आधार से जुड़ा मोबाइल नंबर"] },
    match: (a) => a.state === "Himachal Pradesh" && a.who === "business" && ["below1","1to3"].includes(a.income),
  },

  // ADD MORE HIMACHAL PRADESH SCHEMES ABOVE THIS LINE ↓
  // {
  //   id: "himachal_new_scheme",
  //   icon: "🆕", color: "#123456", scope: "state", state: "Himachal Pradesh",
  //   ministry: { en: "Dept. Name", hi: "विभाग का नाम" },
  //   name:    { en: "Scheme Name", hi: "योजना का नाम" },
  //   benefit: { en: "Benefit details", hi: "लाभ विवरण" },
  //   tag:     { en: "Tag", hi: "टैग" },
  //   annual: 0,
  //   apply:   { en: "website.gov.in", hi: "website.gov.in" }, applyType: "online",
  //   docs:    { en: ["Aadhaar Card"], hi: ["आधार कार्ड"] },
  //   match: (a) => a.state === "Himachal Pradesh",
  // },

];
