// Madhya Pradesh — YojanaSetu State Schemes
// ─────────────────────────────────────────────────────────────────────────────
// HOW TO ADD A NEW SCHEME:
//   1. Copy any block below, paste it above the closing ];
//   2. Give it a unique id like "mp_new_scheme"
//   3. Update name, benefit, docs, match() and save.
//   No other file needs to change.
// ─────────────────────────────────────────────────────────────────────────────

export const MADHYA_PRADESH_SCHEMES = [

  {
    id: "mp_ladli",
    icon: "👧", color: "#C026D3", scope: "state", state: "Madhya Pradesh",
    ministry: { en: "MP Women & Child Dept.", hi: "मध्यप्रदेश महिला एवं बाल विकास" },
    name:    { en: "Ladli Laxmi Yojana 2.0 (MP)",          hi: "लाड़ली लक्ष्मी योजना 2.0 (म.प्र.)" },
    benefit: { en: "₹1,43,000 total support for girl child", hi: "बालिका के लिए कुल ₹1,43,000 सहायता" },
    tag:     { en: "Girl Child", hi: "बालिका" },
    annual: 143000,
    apply:   { en: "https://www.myscheme.gov.in/schemes/lly", hi: "ladlilaxmi.mp.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Birth Certificate","Residence Proof","Bank Account"],
               hi: ["आधार कार्ड","जन्म प्रमाण","निवास प्रमाण","बैंक खाता"] },
    match: (a) => a.state === "Madhya Pradesh" && ["below1","1to3","3to6"].includes(a.income),
  },

  {
    id: "mp_kanya_vivah",
    icon: "💍", color: "#DB2777", scope: "state", state: "Madhya Pradesh",
    ministry: { en: "MP Women & Child Development Dept.", hi: "मध्यप्रदेश महिला एवं बाल विकास विभाग" },
    name:    { en: "Mukhyamantri Kanya Vivah / Nikah Yojana (MP)", hi: "मुख्यमंत्री कन्या विवाह/निकाह योजना (म.प्र.)" },
    benefit: { en: "₹55,000 financial assistance for marriage of girls from BPL/Sambal families", hi: "BPL/सम्बल परिवार की बेटियों के विवाह पर ₹55,000 सहायता" },
    tag:     { en: "Women / Marriage", hi: "महिला / विवाह" },
    annual: 55000,
    apply:   { en: "https://chayan.mponline.gov.in/Portal/Services/WCDR/links.aspx?langid=en-US&Post=WH", hi: "vivahportal.mp.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Samagra ID","BPL / Sambal Card","Age Proof (girl 18+, boy 21+)","Marriage Registration","Bank Account"],
               hi: ["आधार कार्ड","समग्र ID","BPL/सम्बल कार्ड","आयु प्रमाण (बेटी 18+, लड़का 21+)","विवाह पंजीकरण","बैंक खाता"] },
    match: (a) => a.state === "Madhya Pradesh" && a.who === "women" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "mp_mmvy",
    icon: "🎓", color: "#1D4ED8", scope: "state", state: "Madhya Pradesh",
    ministry: { en: "MP Technical Education & Skill Development Dept.", hi: "मध्यप्रदेश तकनीकी शिक्षा एवं कौशल विकास विभाग" },
    name:    { en: "Mukhyamantri Medhavi Vidyarthi Yojana (MMVY)", hi: "मुख्यमंत्री मेधावी विद्यार्थी योजना (म.प्र.)" },
    benefit: { en: "Full higher-education fee paid by Govt. for students with 75%+ (MP Board) or 85%+ (CBSE/ICSE) in Class 12", hi: "कक्षा 12 में 75%+ (MP बोर्ड) या 85%+ (CBSE/ICSE) पर सरकार पूरी उच्च शिक्षा फीस देती है" },
    tag:     { en: "Student / Education", hi: "छात्र / शिक्षा" },
    annual: 0,
    apply:   { en: "https://scholarshipportal.mp.nic.in", hi: "scholarshipportal.mp.nic.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Class 12 Mark Sheet (75%+ / 85%+)","Income Certificate (≤₹6L/year)","Admission Letter from College","Samagra ID","Bank Account"],
               hi: ["आधार कार्ड","कक्षा 12 मार्कशीट (75%+ / 85%+)","आय प्रमाण (≤₹6 लाख/वर्ष)","कॉलेज प्रवेश पत्र","समग्र ID","बैंक खाता"] },
    match: (a) => a.state === "Madhya Pradesh" && a.who === "student" && ["below1","1to3","3to6"].includes(a.income) && a.age === "18to35",
  },

  {
    id: "mp_sambal",
    icon: "🤲", color: "#0F766E", scope: "state", state: "Madhya Pradesh",
    ministry: { en: "MP Labour Dept. (Jan Kalyan)", hi: "मध्यप्रदेश श्रम विभाग (जन कल्याण)" },
    name:    { en: "Mukhyamantri Jan Kalyan (Sambal) Yojana", hi: "मुख्यमंत्री जन कल्याण (सम्बल) योजना" },
    benefit: { en: "Maternity ₹16,000 · Accidental death ₹4L · Education aid · Subsidised electricity · Funeral ₹5,000 for registered unorganised workers", hi: "मातृत्व ₹16,000 · दुर्घटना मृत्यु ₹4 लाख · शिक्षा सहायता · सब्सिडी बिजली · अंत्येष्टि ₹5,000 (पंजीकृत असंगठित श्रमिक)" },
    tag:     { en: "Labour / General", hi: "श्रमिक / सामान्य" },
    annual: 16000,
    apply:   { en: "https://www.myscheme.gov.in/schemes/mjspy", hi: "sambal.mp.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Samagra ID","Sambal Registration Card","Ration Card","Bank Account"],
               hi: ["आधार कार्ड","समग्र ID","सम्बल पंजीकरण कार्ड","राशन कार्ड","बैंक खाता"] },
    match: (a) => a.state === "Madhya Pradesh" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "mp_krishak_jeevan",
    icon: "🚜", color: "#15803D", scope: "state", state: "Madhya Pradesh",
    ministry: { en: "MP Agriculture & Revenue Dept.", hi: "मध्यप्रदेश कृषि एवं राजस्व विभाग" },
    name:    { en: "Mukhyamantri Krishak Jeevan Kalyan Yojana (MP)", hi: "मुख्यमंत्री कृषक जीवन कल्याण योजना (म.प्र.)" },
    benefit: { en: "Farmer accident insurance: death ₹4L · Permanent disability ₹2L · Partial disability ₹1L · Eye/limb loss ₹50,000", hi: "किसान दुर्घटना बीमा: मृत्यु ₹4 लाख · स्थायी विकलांगता ₹2 लाख · आंशिक विकलांगता ₹1 लाख" },
    tag:     { en: "Farmer / Insurance", hi: "किसान / बीमा" },
    annual: 0,
    apply:   { en: "saara.mp.gov.in / Nearest Tehsil Office", hi: "saara.mp.gov.in / नजदीकी तहसील कार्यालय" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card","Land Records (Khasra)","Samagra ID","FIR Copy (for accident)","Post-Mortem Report (for death claim)","Bank Account"],
               hi: ["आधार कार्ड","जमीन के कागज़ (खसरा)","समग्र ID","FIR प्रति (दुर्घटना हेतु)","पोस्टमार्टम रिपोर्ट (मृत्यु दावे हेतु)","बैंक खाता"] },
    match: (a) => a.state === "Madhya Pradesh" && a.who === "farmer",
  },

  {
    id: "mp_vridha_pension",
    icon: "👴", color: "#D97706", scope: "state", state: "Madhya Pradesh",
    ministry: { en: "MP Social Justice & Disabled Welfare Dept.", hi: "मध्यप्रदेश सामाजिक न्याय एवं दिव्यांगजन कल्याण विभाग" },
    name:    { en: "Mukhyamantri Vridha Pension Yojana (MP)", hi: "मुख्यमंत्री वृद्धा पेंशन योजना (म.प्र.)" },
    benefit: { en: "₹600/month pension for BPL senior citizens aged 60+ years", hi: "60+ वर्ष के BPL वरिष्ठ नागरिकों को ₹600/माह पेंशन" },
    tag:     { en: "Senior / Pension", hi: "वरिष्ठ / पेंशन" },
    annual: 7200,
    apply:   { en: "https://www.myscheme.gov.in/schemes/ignvpy", hi: "socialsecurity.mp.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Samagra ID","Age Proof (60+ years)","BPL / Sambal Certificate","Bank Account"],
               hi: ["आधार कार्ड","समग्र ID","आयु प्रमाण (60+ वर्ष)","BPL/सम्बल प्रमाण पत्र","बैंक खाता"] },
    match: (a) => a.state === "Madhya Pradesh" && (a.who === "senior" || a.age === "above60") && ["below1","1to3"].includes(a.income),
  },

  {
    id: "mp_vidhwa_pension",
    icon: "👩‍🦳", color: "#9D174D", scope: "state", state: "Madhya Pradesh",
    ministry: { en: "MP Social Justice Dept.", hi: "मध्यप्रदेश सामाजिक न्याय विभाग" },
    name:    { en: "Mukhyamantri Vidhwa Pension Yojana (MP)", hi: "मुख्यमंत्री विधवा पेंशन योजना (म.प्र.)" },
    benefit: { en: "₹600/month pension for BPL widows (18+ years)", hi: "BPL विधवाओं (18+ वर्ष) को ₹600/माह पेंशन" },
    tag:     { en: "Women / Widow", hi: "महिला / विधवा" },
    annual: 7200,
    apply:   { en: "https://socialjustice.gov.in", hi: "socialsecurity.mp.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Samagra ID","Husband's Death Certificate","Age Proof","BPL / Sambal Certificate","Bank Account"],
               hi: ["आधार कार्ड","समग्र ID","पति का मृत्यु प्रमाण पत्र","आयु प्रमाण","BPL/सम्बल प्रमाण","बैंक खाता"] },
    match: (a) => a.state === "Madhya Pradesh" && a.who === "women" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "mp_prasuti",
    icon: "🤱", color: "#BE185D", scope: "state", state: "Madhya Pradesh",
    ministry: { en: "MP Labour Dept. (Sambal)", hi: "मध्यप्रदेश श्रम विभाग (सम्बल)" },
    name:    { en: "Prasuti Sahayata Yojana (MP – Sambal)", hi: "प्रसूति सहायता योजना (म.प्र. – सम्बल)" },
    benefit: { en: "₹16,000 maternity benefit: ₹4,000 before delivery + ₹12,000 after delivery (Sambal-registered workers)", hi: "₹16,000 मातृत्व सहायता: प्रसव से पहले ₹4,000 + प्रसव के बाद ₹12,000 (सम्बल पंजीकृत)" },
    tag:     { en: "Maternity / Women", hi: "मातृत्व / महिला" },
    annual: 16000,
    apply:   { en: "https://sambal.mp.gov.in", hi: "sambal.mp.gov.in / नजदीकी श्रम कार्यालय" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Samagra ID","Sambal Card","MCH Card (Mother & Child Health)","Delivery Certificate","Bank Account"],
               hi: ["आधार कार्ड","समग्र ID","सम्बल कार्ड","MCH कार्ड","प्रसव प्रमाण पत्र","बैंक खाता"] },
    match: (a) => a.state === "Madhya Pradesh" && a.who === "women" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "mp_sikho_kamao",
    icon: "🛠️", color: "#7C3AED", scope: "state", state: "Madhya Pradesh",
    ministry: { en: "MP Skill Development & Employment Dept.", hi: "मध्यप्रदेश कौशल विकास एवं रोजगार विभाग" },
    name:    { en: "Mukhyamantri Sikho Kamao Yojana (MP)", hi: "मुख्यमंत्री सीखो-कमाओ योजना (म.प्र.)" },
    benefit: { en: "₹8,000–₹10,000/month stipend while learning on-the-job · Industry training + certificate", hi: "काम करते हुए सीखने पर ₹8,000–₹10,000/माह · उद्योग प्रशिक्षण + प्रमाण पत्र" },
    tag:     { en: "Skill / Youth", hi: "कौशल / युवा" },
    annual: 96000,
    apply:   { en: "https://www.myscheme.gov.in/schemes/mmsky", hi: "mmsky.mp.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Samagra ID","Class 12 / Diploma / Degree Certificate","Bank Account (Aadhaar-linked)","Passport Photo"],
               hi: ["आधार कार्ड","समग्र ID","कक्षा 12/डिप्लोमा/डिग्री प्रमाण पत्र","बैंक खाता (आधार लिंक)","पासपोर्ट फोटो"] },
    match: (a) => a.state === "Madhya Pradesh" && a.who === "student" && a.age === "18to35" && ["below1","1to3","3to6"].includes(a.income),
  },

  {
    id: "mp_yuva_udyami",
    icon: "💼", color: "#6B21A8", scope: "state", state: "Madhya Pradesh",
    ministry: { en: "MP MSME & Industry Dept.", hi: "मध्यप्रदेश MSME एवं उद्योग विभाग" },
    name:    { en: "Mukhyamantri Yuva Udyami Yojana (MP)", hi: "मुख्यमंत्री युवा उद्यमी योजना (म.प्र.)" },
    benefit: { en: "Loan ₹10L – ₹1 Crore at 5% interest · 15–30% margin money (subsidy) for youth businesses", hi: "5% ब्याज पर ₹10 लाख–₹1 करोड़ लोन · 15–30% मार्जिन मनी अनुदान" },
    tag:     { en: "Business / Youth", hi: "व्यापार / युवा" },
    annual: 0,
    apply:   { en: "https://msme.mponline.gov.in", hi: "msme.mponline.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar & PAN Card","Class 10 Pass Certificate","Business Plan / Project Report","Bank Statement (6 months)","Caste Certificate (if SC/ST/OBC)","Passport Photo"],
               hi: ["आधार और पैन कार्ड","कक्षा 10 उत्तीर्ण प्रमाण","व्यापार योजना/प्रोजेक्ट रिपोर्ट","6 महीने बैंक स्टेटमेंट","जाति प्रमाण पत्र (SC/ST/OBC हो तो)","पासपोर्ट फोटो"] },
    match: (a) => a.state === "Madhya Pradesh" && a.who === "business" && ["18to35"].includes(a.age),
  },

  {
    id: "mp_swarojgar",
    icon: "🏪", color: "#0F766E", scope: "state", state: "Madhya Pradesh",
    ministry: { en: "MP MSME Dept.", hi: "मध्यप्रदेश MSME विभाग" },
    name:    { en: "Mukhyamantri Swarojgar Yojana (MP)", hi: "मुख्यमंत्री स्वरोजगार योजना (म.प्र.)" },
    benefit: { en: "Self-employment loan ₹50,000–₹10 Lakh · 15% subsidy (general) or 30% (SC/ST/Women/Divyang)", hi: "स्वरोजगार के लिए ₹50,000–₹10 लाख लोन · 15% सब्सिडी (सामान्य) · 30% (SC/ST/महिला/दिव्यांग)" },
    tag:     { en: "Business / Self-employment", hi: "व्यापार / स्वरोजगार" },
    annual: 0,
    apply:   { en: "https://msme.mponline.gov.in", hi: "msme.mponline.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Class 8 Pass Certificate (minimum)","Project Report","Bank Account","Caste Certificate (if applicable)","Residential Proof"],
               hi: ["आधार कार्ड","कक्षा 8 उत्तीर्ण (न्यूनतम)","प्रोजेक्ट रिपोर्ट","बैंक खाता","जाति प्रमाण पत्र (लागू हो तो)","निवास प्रमाण"] },
    match: (a) => a.state === "Madhya Pradesh" && (a.who === "business" || a.who === "general") && ["below1","1to3","3to6"].includes(a.income),
  },

  {
    id: "mp_chirayu",
    icon: "🏥", color: "#0369A1", scope: "state", state: "Madhya Pradesh",
    ministry: { en: "MP Health & Family Welfare Dept.", hi: "मध्यप्रदेश स्वास्थ्य एवं परिवार कल्याण विभाग" },
    name:    { en: "Mukhyamantri Chirayu Yojana (MPCBY)", hi: "मुख्यमंत्री चिरायु योजना (म.प्र.)" },
    benefit: { en: "₹5 Lakh/year free cashless treatment at empanelled hospitals (covers families up to ₹2.5L annual income — bridges gap above Ayushman Bharat)", hi: "₹5 लाख/वर्ष मुफ्त कैशलेस इलाज (₹2.5 लाख वार्षिक आय तक के परिवार – आयुष्मान से ऊपर का अंतर भरता है)" },
    tag:     { en: "Health / Insurance", hi: "स्वास्थ्य / बीमा" },
    annual: 500000,
    apply:   { en: "https://iforms.mponline.gov.in/Form/GetAllNotification", hi: "chirayuayushmanmp.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Samagra ID","Income Certificate (≤₹2.5L/year)","Ration Card","Passport Photo"],
               hi: ["आधार कार्ड","समग्र ID","आय प्रमाण पत्र (≤₹2.5 लाख/वर्ष)","राशन कार्ड","पासपोर्ट फोटो"] },
    match: (a) => a.state === "Madhya Pradesh" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "mp_bhavantar",
    icon: "⚖️", color: "#78350F", scope: "state", state: "Madhya Pradesh",
    ministry: { en: "MP Agriculture Dept.", hi: "मध्यप्रदेश कृषि विभाग" },
    name:    { en: "Mukhyamantri Bhavantar Bhugtan Yojana (MP)", hi: "मुख्यमंत्री भावांतर भुगतान योजना (म.प्र.)" },
    benefit: { en: "Direct payment of price deficit to farmers' accounts when market price falls below MSP for notified crops", hi: "अधिसूचित फसलों का बाज़ार भाव MSP से कम होने पर मूल्य अंतर सीधे किसान के बैंक खाते में" },
    tag:     { en: "Farmer / Price Support", hi: "किसान / मूल्य समर्थन" },
    annual: 0,
    apply:   { en: "mpeuparjan.nic.in / Nearest Procurement Centre", hi: "mpeuparjan.nic.in / नजदीकी उपार्जन केंद्र" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card","Land Records (Khasra)","Samagra ID","Bank Account","Crop Sowing Declaration"],
               hi: ["आधार कार्ड","जमीन के कागज़ (खसरा)","समग्र ID","बैंक खाता","फसल बुवाई घोषणा पत्र"] },
    match: (a) => a.state === "Madhya Pradesh" && a.who === "farmer",
  },

  {
    id: "mp_ladli_behna",
    icon: "👩", color: "#EC4899", scope: "state", state: "Madhya Pradesh",
    ministry: { en: "MP Women & Child Development Dept.", hi: "मध्यप्रदेश महिला एवं बाल विकास विभाग" },
    name:    { en: "Ladli Behna Yojana (MP)", hi: "लाड़ली बहना योजना (म.प्र.)" },
    benefit: { en: "₹1,250/month direct cash transfer to all married women (21–60 years) in MP", hi: "म.प्र. की सभी विवाहित महिलाओं (21–60 वर्ष) को ₹1,250/माह सीधे बैंक में" },
    tag:     { en: "Women / Cash Transfer", hi: "महिला / नकद हस्तांतरण" },
    annual: 15000,
    apply:   { en: "cmladlibahna.mp.gov.in", hi: "cmladlibahna.mp.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Samagra ID", "Bank Account (Aadhaar-linked)", "Marriage Certificate / Self-declaration", "MP Domicile Proof"],
               hi: ["आधार कार्ड", "समग्र ID", "बैंक खाता (आधार लिंक)", "विवाह प्रमाण पत्र / स्व-घोषणा", "म.प्र. निवास प्रमाण"] },
    match: (a) => a.state === "Madhya Pradesh" && a.who === "women" && ["18to35", "35to60"].includes(a.age),
  },

  {
    id: "mp_viklang_pension",
    icon: "♿", color: "#6366F1", scope: "state", state: "Madhya Pradesh",
    ministry: { en: "MP Social Justice & Disabled Welfare Dept.", hi: "मध्यप्रदेश सामाजिक न्याय एवं दिव्यांगजन कल्याण विभाग" },
    name:    { en: "Mukhyamantri Nishakt / Viklang Pension Yojana (MP)", hi: "मुख्यमंत्री निशक्त/विकलांग पेंशन योजना (म.प्र.)" },
    benefit: { en: "₹600/month pension for persons with 40%+ disability (BPL / Sambal registered)", hi: "40%+ विकलांगता वाले BPL/सम्बल व्यक्तियों को ₹600/माह पेंशन" },
    tag:     { en: "Disability / Pension", hi: "विकलांगता / पेंशन" },
    annual: 7200,
    apply:   { en: "https://www.myscheme.gov.in/schemes/mkapy", hi: "socialsecurity.mp.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Samagra ID", "Disability Certificate (40%+ from CMO)", "BPL / Sambal Certificate", "Bank Account", "Passport Photo"],
               hi: ["आधार कार्ड", "समग्र ID", "विकलांगता प्रमाण पत्र (CMO से 40%+)", "BPL/सम्बल प्रमाण", "बैंक खाता", "पासपोर्ट फोटो"] },
    match: (a) => a.state === "Madhya Pradesh" && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "mp_tirth_darshan",
    icon: "🛕", color: "#F59E0B", scope: "state", state: "Madhya Pradesh",
    ministry: { en: "MP Religious Trust & Endowment Dept.", hi: "मध्यप्रदेश धार्मिक न्यास एवं धर्मस्व विभाग" },
    name:    { en: "Mukhyamantri Tirth Darshan Yojana (MP)", hi: "मुख्यमंत्री तीर्थ दर्शन योजना (म.प्र.)" },
    benefit: { en: "Free pilgrimage (train + stay + food + guide) for senior citizens (60+) to major religious sites across India", hi: "60+ वर्ष के वरिष्ठ नागरिकों को देश के प्रमुख तीर्थस्थलों की मुफ्त यात्रा (ट्रेन + रहना + खाना + गाइड)" },
    tag:     { en: "Senior / Pilgrimage", hi: "वरिष्ठ / तीर्थ यात्रा" },
    annual: 0,
    apply:   { en: "dharmasva.mp.gov.in / Nearest District Collector Office", hi: "dharmasva.mp.gov.in / नजदीकी जिला कलेक्टर कार्यालय" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "Samagra ID", "Age Proof (60+ years)", "MP Domicile Proof", "Medical Fitness Certificate", "Passport Photo"],
               hi: ["आधार कार्ड", "समग्र ID", "आयु प्रमाण (60+ वर्ष)", "म.प्र. निवास प्रमाण", "चिकित्सा फिटनेस प्रमाण", "पासपोर्ट फोटो"] },
    match: (a) => a.state === "Madhya Pradesh" && (a.who === "senior" || a.age === "above60"),
  },

  {
    id: "mp_baal_hriday",
    icon: "❤️‍🩹", color: "#DC2626", scope: "state", state: "Madhya Pradesh",
    ministry: { en: "MP Health & Family Welfare Dept.", hi: "मध्यप्रदेश स्वास्थ्य एवं परिवार कल्याण विभाग" },
    name:    { en: "Mukhyamantri Baal Hriday Upchaar Yojana (MP)", hi: "मुख्यमंत्री बाल हृदय उपचार योजना (म.प्र.)" },
    benefit: { en: "Free open-heart surgery for children (up to 15 years) with congenital heart disease at empanelled hospitals", hi: "जन्मजात हृदय रोग से पीड़ित बच्चों (15 वर्ष तक) का पैनलबद्ध अस्पतालों में मुफ्त ओपन-हार्ट ऑपरेशन" },
    tag:     { en: "Health / Child", hi: "स्वास्थ्य / बच्चे" },
    annual: 0,
    apply:   { en: "Nearest Govt. Hospital / CMHO Office", hi: "नजदीकी सरकारी अस्पताल / मुख्य चिकित्सा एवं स्वास्थ्य अधिकारी कार्यालय" }, applyType: "offline",
    docs:    { en: ["Child's Aadhaar Card", "Birth Certificate", "Parent's Aadhaar Card", "Samagra ID", "Doctor's Referral / Diagnosis Report", "Income / BPL Certificate"],
               hi: ["बच्चे का आधार कार्ड", "जन्म प्रमाण पत्र", "माता-पिता का आधार कार्ड", "समग्र ID", "डॉक्टर का रेफरल / निदान रिपोर्ट", "आय/BPL प्रमाण पत्र"] },
    match: (a) => a.state === "Madhya Pradesh" && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "mp_kalyani_sahayata",
    icon: "💐", color: "#9D174D", scope: "state", state: "Madhya Pradesh",
    ministry: { en: "MP Social Justice Dept.", hi: "मध्यप्रदेश सामाजिक न्याय विभाग" },
    name:    { en: "Mukhyamantri Kalyani Vivah Sahayata Yojana (MP)", hi: "मुख्यमंत्री कल्याणी विवाह सहायता योजना (म.प्र.)" },
    benefit: { en: "₹2 Lakh one-time financial aid for remarriage of widows (Kalyani) aged 18–45 years", hi: "18–45 वर्ष की विधवाओं (कल्याणी) के पुनर्विवाह पर ₹2 लाख एकमुश्त सहायता" },
    tag:     { en: "Women / Widow", hi: "महिला / विधवा" },
    annual: 200000,
    apply:   { en: "https://www.myscheme.gov.in/schemes/mmkvsy", hi: "socialsecurity.mp.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Samagra ID", "Husband's Death Certificate", "Age Proof (18–45 years)", "New Marriage Registration Certificate", "BPL Certificate", "Bank Account"],
               hi: ["आधार कार्ड", "समग्र ID", "पति का मृत्यु प्रमाण पत्र", "आयु प्रमाण (18–45 वर्ष)", "नए विवाह का पंजीकरण प्रमाण पत्र", "BPL प्रमाण पत्र", "बैंक खाता"] },
    match: (a) => a.state === "Madhya Pradesh" && a.who === "women" && ["below1", "1to3"].includes(a.income) && ["18to35", "35to60"].includes(a.age),
  },

  {
    id: "mp_udyam_kranti",
    icon: "🚀", color: "#0891B2", scope: "state", state: "Madhya Pradesh",
    ministry: { en: "MP MSME & Industry Dept.", hi: "मध्यप्रदेश MSME एवं उद्योग विभाग" },
    name:    { en: "Mukhyamantri Udyam Kranti Yojana (MP)", hi: "मुख्यमंत्री उद्यम क्रांति योजना (म.प्र.)" },
    benefit: { en: "Collateral-free loan ₹1 Lakh – ₹50 Lakh · 3% interest subvention for 7 years · No guarantor required", hi: "₹1 लाख–₹50 लाख तक बिना गारंटी लोन · 7 वर्षों के लिए 3% ब्याज अनुदान · कोई गारंटर नहीं" },
    tag:     { en: "Business / Startup", hi: "व्यापार / स्टार्टअप" },
    annual: 0,
    apply:   { en: "https://msme.mponline.gov.in", hi: "samast.mp.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar & PAN Card", "Class 12 Certificate (minimum)", "Samagra ID", "Project Report / Business Plan", "Bank Account", "MP Domicile Proof"],
               hi: ["आधार और पैन कार्ड", "कक्षा 12 प्रमाण पत्र (न्यूनतम)", "समग्र ID", "प्रोजेक्ट रिपोर्ट / व्यापार योजना", "बैंक खाता", "म.प्र. निवास प्रमाण"] },
    match: (a) => a.state === "Madhya Pradesh" && a.who === "business" && ["18to35", "35to60"].includes(a.age),
  },

  {
    id: "mp_deendayal_rasoi",
    icon: "🍱", color: "#92400E", scope: "state", state: "Madhya Pradesh",
    ministry: { en: "MP Urban Development & Housing Dept.", hi: "मध्यप्रदेश नगरीय विकास एवं आवास विभाग" },
    name:    { en: "Deendayal Rasoi Yojana (MP)", hi: "दीनदयाल रसोई योजना (म.प्र.)" },
    benefit: { en: "Nutritious meal (dal, rice, roti, sabzi) at just ₹10/plate at govt. canteens for daily wage workers & poor", hi: "दैनिक मजदूरों और गरीबों को सरकारी कैंटीन पर केवल ₹10/थाली में पौष्टिक भोजन (दाल, चावल, रोटी, सब्जी)" },
    tag:     { en: "Food / General", hi: "भोजन / सामान्य" },
    annual: 3650,
    apply:   { en: "Walk-in at nearest Deendayal Rasoi canteen (no registration required)", hi: "नजदीकी दीनदयाल रसोई कैंटीन में सीधे जाएं (पंजीकरण की आवश्यकता नहीं)" }, applyType: "offline",
    docs:    { en: ["No documents required · Walk-in service"],
               hi: ["कोई दस्तावेज़ नहीं · सीधे सेवा"] },
    match: (a) => a.state === "Madhya Pradesh" && ["below1", "1to3"].includes(a.income) && ["urban", "semi"].includes(a.area),
  },

  {
    id: "mp_gaon_ki_beti",
    icon: "📖", color: "#7C3AED", scope: "state", state: "Madhya Pradesh",
    ministry: { en: "MP Higher Education Dept.", hi: "मध्यप्रदेश उच्च शिक्षा विभाग" },
    name:    { en: "Gaon Ki Beti Yojana (MP)", hi: "गांव की बेटी योजना (म.प्र.)" },
    benefit: { en: "₹500/month (10 months/year) scholarship for rural girls who scored 60%+ in Class 12 and are pursuing higher education", hi: "60%+ अंक से कक्षा 12 उत्तीर्ण ग्रामीण बेटियों को उच्च शिक्षा के दौरान ₹500/माह (10 माह/वर्ष) छात्रवृत्ति" },
    tag:     { en: "Student / Women", hi: "छात्र / महिला" },
    annual: 5000,
    apply:   { en: "scholarshipportal.mp.nic.in", hi: "scholarshipportal.mp.nic.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Samagra ID", "Class 12 Mark Sheet (min. 60%)", "Rural Domicile / Caste Certificate", "College Enrollment Certificate", "Bank Account"],
               hi: ["आधार कार्ड", "समग्र ID", "कक्षा 12 मार्कशीट (न्यूनतम 60%)", "ग्रामीण निवास / जाति प्रमाण पत्र", "कॉलेज नामांकन प्रमाण", "बैंक खाता"] },
    match: (a) => a.state === "Madhya Pradesh" && a.who === "student" && a.area === "rural" && ["18to35"].includes(a.age),
  },

  {
    id: "mp_ladli_behna_awas",
    icon: "🏠", color: "#EA580C", scope: "state", state: "Madhya Pradesh",
    ministry: { en: "MP Housing & Environment Dept.", hi: "मध्यप्रदेश आवास एवं पर्यावरण विभाग" },
    name:    { en: "Ladli Behna Awas Yojana (MP)", hi: "लाड़ली बहना आवास योजना (म.प्र.)" },
    benefit: { en: "Free pucca house (₹1.2–₹1.5 Lakh grant) for women in families missed by PMAY Gramin · Priority to Ladli Behna beneficiaries", hi: "PMAY ग्रामीण से छूटे परिवारों की महिलाओं को मुफ्त पक्का मकान (₹1.2–₹1.5 लाख अनुदान) · लाड़ली बहना लाभार्थियों को प्राथमिकता" },
    tag:     { en: "Housing / Women", hi: "आवास / महिला" },
    annual: 150000,
    apply:   { en: "https://cmladlibahna.mp.gov.in", hi: "cmladlibahna.mp.gov.in / नजदीकी ग्राम पंचायत" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Samagra ID", "Ladli Behna Registration ID", "Land / Plot Ownership Proof", "No Pucca House Declaration", "Bank Account"],
               hi: ["आधार कार्ड", "समग्र ID", "लाड़ली बहना पंजीकरण ID", "जमीन/प्लॉट स्वामित्व प्रमाण", "पक्का मकान न होने की घोषणा", "बैंक खाता"] },
    match: (a) => a.state === "Madhya Pradesh" && a.who === "women" && ["no", "kutcha"].includes(a.house) && ["below1", "1to3"].includes(a.income),
  },

  {
    id: "mp_nishakt_vivah",
    icon: "🤝", color: "#6366F1", scope: "state", state: "Madhya Pradesh",
    ministry: { en: "MP Social Justice & Disabled Welfare Dept.", hi: "मध्यप्रदेश सामाजिक न्याय एवं दिव्यांगजन कल्याण विभाग" },
    name:    { en: "Mukhyamantri Nishaktjan Vivah Protsahan Yojana (MP)", hi: "मुख्यमंत्री निशक्तजन विवाह प्रोत्साहन योजना (म.प्र.)" },
    benefit: { en: "₹2 Lakh one-time incentive for marriage where one or both partners have 40%+ disability", hi: "विवाह पर ₹2 लाख एकमुश्त प्रोत्साहन जहाँ एक या दोनों पक्षों को 40%+ विकलांगता हो" },
    tag:     { en: "Disability / Marriage", hi: "विकलांगता / विवाह" },
    annual: 200000,
    apply:   { en: "socialsecurity.mp.gov.in / Nearest District Social Welfare Office", hi: "socialsecurity.mp.gov.in / नजदीकी जिला सामाजिक न्याय कार्यालय" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Samagra ID", "Disability Certificate (40%+, from CMO)", "Age Proof (both partners 18+ / 21+)", "Marriage Registration Certificate", "BPL / Income Certificate", "Bank Account"],
               hi: ["आधार कार्ड", "समग्र ID", "विकलांगता प्रमाण पत्र (CMO से 40%+)", "आयु प्रमाण (18+/21+)", "विवाह पंजीकरण प्रमाण पत्र", "BPL/आय प्रमाण", "बैंक खाता"] },
    match: (a) => a.state === "Madhya Pradesh" && ["below1", "1to3"].includes(a.income),
  },

  // ADD MORE MADHYA PRADESH SCHEMES ABOVE THIS LINE ↓
  // {
  //   id: "madhya_new_scheme",
  //   icon: "🆕", color: "#123456", scope: "state", state: "Madhya Pradesh",
  //   ministry: { en: "Dept. Name", hi: "विभाग का नाम" },
  //   name:    { en: "Scheme Name", hi: "योजना का नाम" },
  //   benefit: { en: "Benefit details", hi: "लाभ विवरण" },
  //   tag:     { en: "Tag", hi: "टैग" },
  //   annual: 0,
  //   apply:   { en: "website.gov.in", hi: "website.gov.in" }, applyType: "online",
  //   docs:    { en: ["Aadhaar Card"], hi: ["आधार कार्ड"] },
  //   match: (a) => a.state === "Madhya Pradesh",
  // },

];
