// Maharashtra — YojanaSetu State Schemes
// ─────────────────────────────────────────────────────────────────────────────
// HOW TO ADD A NEW SCHEME:
//   1. Copy any block below, paste it above the closing ];
//   2. Give it a unique id like "maharashtra_new_scheme"
//   3. Update name, benefit, docs, match() and save.
//   No other file needs to change.
// ─────────────────────────────────────────────────────────────────────────────

export const MAHARASHTRA_SCHEMES = [

  {
    id: "maha_health",
    icon: "🏥", color: "#0369A1", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Health Dept.", hi: "महाराष्ट्र स्वास्थ्य विभाग" },
    name:    { en: "Mahatma Phule Jan Arogya Yojana",             hi: "महात्मा फुले जन आरोग्य योजना" },
    benefit: { en: "₹1.5 Lakh/year cashless hospital treatment", hi: "₹1.5 लाख/वर्ष कैशलेस अस्पताल" },
    tag:     { en: "Health", hi: "स्वास्थ्य" },
    annual: 150000,
    apply:   { en: "jeevandayee.maharashtra.gov.in", hi: "jeevandayee.maharashtra.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Yellow/Orange Ration Card","Income Certificate"],
               hi: ["आधार कार्ड","पीला/नारंगी राशन कार्ड","आय प्रमाण पत्र"] },
    match: (a) => a.state === "Maharashtra" && ["below1","1to3","3to6"].includes(a.income),
  },

  {
    id: "maha_shetkari",
    icon: "🌾", color: "#16A34A", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Agriculture Dept.", hi: "महाराष्ट्र कृषि विभाग" },
    name:    { en: "Shetkari Sanman Yojana (Maha)",           hi: "शेतकरी सन्मान योजना (महाराष्ट्र)" },
    benefit: { en: "₹6,000/year additional to PM Kisan",     hi: "पीएम किसान के अतिरिक्त ₹6,000/वर्ष" },
    tag:     { en: "Farmer", hi: "किसान" },
    annual: 6000,
    apply:   { en: "krishi.maharashtra.gov.in", hi: "krishi.maharashtra.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","7/12 Land Extract","Bank Passbook"],
               hi: ["आधार कार्ड","7/12 जमीन उतारा","बैंक पासबुक"] },
    match: (a) => a.state === "Maharashtra" && a.who === "farmer",
  },

  {
    id: "maha_majhi_ladki_bahin",
    icon: "👧", color: "#C026D3", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Women & Child Dev. Dept.", hi: "महाराष्ट्र महिला एवं बाल विकास विभाग" },
    name:    { en: "Majhi Ladki Bahin Yojana (Maharashtra)",          hi: "माझी लाडकी बहीण योजना (महाराष्ट्र)" },
    benefit: { en: "₹1,500/month to women aged 21–65 with income below ₹2.5 Lakh/year", hi: "21–65 वर्ष की महिलाओं को ₹1,500/माह (वार्षिक आय ₹2.5 लाख से कम)" },
    tag:     { en: "Women", hi: "महिला" },
    annual: 18000,
    apply:   { en: "ladakibahin.maharashtra.gov.in", hi: "ladakibahin.maharashtra.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Ration Card","Bank Account (women's name)","Income Certificate","Maharashtra Domicile"],
               hi: ["आधार कार्ड","राशन कार्ड","बैंक खाता (महिला के नाम)","आय प्रमाण","महाराष्ट्र अधिवास प्रमाण"] },
    match: (a) => a.state === "Maharashtra" && a.who === "women" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "maha_annasaheb_patil",
    icon: "🏦", color: "#1D4ED8", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra MAVIM / Annasaheb Patil Corp.", hi: "महाराष्ट्र अण्णासाहेब पाटील महामंडळ" },
    name:    { en: "Annasaheb Patil Loan Scheme",                          hi: "अण्णासाहेब पाटील आर्थिक मागास विकास महामंडळ योजना" },
    benefit: { en: "Interest-free/subsidised loan up to ₹10 Lakh for OBC entrepreneurs", hi: "OBC उद्यमियों को ₹10 लाख तक ब्याजमुक्त/सब्सिडी लोन" },
    tag:     { en: "Business / OBC", hi: "व्यापार / OBC" },
    annual: 0,
    apply:   { en: "mahaswayam.gov.in", hi: "mahaswayam.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Caste Certificate (OBC)", "Business Plan", "Income Certificate", "Bank Passbook"],
               hi: ["आधार कार्ड", "जाति प्रमाण पत्र (OBC)", "व्यापार योजना", "आय प्रमाण पत्र", "बैंक पासबुक"] },
    match: (a) => a.state === "Maharashtra" && a.who === "business" && ["below1","1to3","3to6"].includes(a.income),
  },

  {
    id: "maha_baliraja_sinchana",
    icon: "💧", color: "#0891B2", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Water Resources Dept.", hi: "महाराष्ट्र जल संसाधन विभाग" },
    name:    { en: "Baliraja Chaitanya Sinchana Yojana",              hi: "बळीराजा चेतना सिंचन योजना" },
    benefit: { en: "Free drip/sprinkler irrigation installation for small & marginal farmers", hi: "लघु व सीमांत किसानों को मुफ्त ड्रिप/स्प्रिंकलर सिंचाई" },
    tag:     { en: "Farmer / Irrigation", hi: "किसान / सिंचाई" },
    annual: 45000,
    apply:   { en: "mahaagri.gov.in", hi: "mahaagri.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "7/12 Land Extract", "Caste Certificate (if SC/ST)", "Bank Passbook"],
               hi: ["आधार कार्ड", "7/12 जमीन उतारा", "जाति प्रमाण (SC/ST के लिए)", "बैंक पासबुक"] },
    match: (a) => a.state === "Maharashtra" && a.who === "farmer" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "maha_sant_rohidas",
    icon: "🧰", color: "#B45309", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra SC/OBC Finance Corp.", hi: "महाराष्ट्र अनुसूचित जाति वित्त व विकास महामंडळ" },
    name:    { en: "Sant Rohidas Charmakar Artisan Scheme",           hi: "संत रोहिदास चर्मकार योजना" },
    benefit: { en: "Subsidised loan up to ₹5 Lakh for leather artisans (SC community)", hi: "चमड़ा कारीगरों (SC) को ₹5 लाख तक सब्सिडी लोन" },
    tag:     { en: "Artisan / SC", hi: "कारीगर / SC" },
    annual: 0,
    apply:   { en: "mahasamajkalyan.gov.in", hi: "mahasamajkalyan.gov.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "Caste Certificate (SC)", "Income Certificate", "Trade Proof", "Bank Passbook"],
               hi: ["आधार कार्ड", "जाति प्रमाण पत्र (SC)", "आय प्रमाण पत्र", "व्यवसाय प्रमाण", "बैंक पासबुक"] },
    match: (a) => a.state === "Maharashtra" && a.who === "business" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "maha_rajarshi_shahu",
    icon: "📚", color: "#1D4ED8", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Higher & Tech. Education Dept.", hi: "महाराष्ट्र उच्च व तंत्र शिक्षण विभाग" },
    name:    { en: "Rajarshi Chhatrapati Shahu Maharaj Shishyavrutti", hi: "राजर्षी छत्रपती शाहू महाराज शिष्यवृत्ती" },
    benefit: { en: "₹5,000–₹8,000/year scholarship for OBC students in higher education", hi: "OBC छात्रों को उच्च शिक्षा के लिए ₹5,000–₹8,000/वर्ष छात्रवृत्ति" },
    tag:     { en: "Student / OBC", hi: "छात्र / OBC" },
    annual: 8000,
    apply:   { en: "mahadbt.gov.in", hi: "mahadbt.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "OBC Caste Certificate", "Income Certificate (≤₹8L/year)", "Previous Year Mark Sheet", "College Bonafide", "Bank Passbook"],
               hi: ["आधार कार्ड", "OBC जाति प्रमाण पत्र", "आय प्रमाण (≤₹8 लाख/वर्ष)", "पिछले वर्ष की मार्कशीट", "कॉलेज बोनाफाइड", "बैंक पासबुक"] },
    match: (a) => a.state === "Maharashtra" && a.who === "student" && ["below1","1to3","3to6"].includes(a.income),
  },

  {
    id: "maha_swadhar_gruh",
    icon: "🏠", color: "#9D174D", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Social Justice Dept.", hi: "महाराष्ट्र सामाजिक न्याय विभाग" },
    name:    { en: "Swadhar Gruh Scheme (SC Girls Hostel)",           hi: "स्वाधार गृह योजना (SC बालिका छात्रावास)" },
    benefit: { en: "Free hostel + ₹51,000/year living & education expenses for SC girls studying away from home", hi: "SC छात्राओं को मुफ्त हॉस्टल + ₹51,000/वर्ष शिक्षा व जीवन व्यय" },
    tag:     { en: "Student / Women / SC", hi: "छात्र / महिला / SC" },
    annual: 51000,
    apply:   { en: "sjsa.maharashtra.gov.in", hi: "sjsa.maharashtra.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "SC Caste Certificate", "Income Certificate", "College Admission Proof", "Bank Passbook"],
               hi: ["आधार कार्ड", "SC जाति प्रमाण पत्र", "आय प्रमाण पत्र", "कॉलेज प्रवेश प्रमाण", "बैंक पासबुक"] },
    match: (a) => a.state === "Maharashtra" && a.who === "student" && a.who === "women" || (a.state === "Maharashtra" && a.who === "women" && ["below1","1to3"].includes(a.income)),
  },

  {
    id: "maha_gharkul",
    icon: "🏡", color: "#15803D", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Housing Dept. (PMAY-G State Top-up)", hi: "महाराष्ट्र गृहनिर्माण विभाग" },
    name:    { en: "Ramai Gharkul Yojana (Maharashtra)",              hi: "रमाई घरकुल योजना (महाराष्ट्र)" },
    benefit: { en: "₹1.20 Lakh housing grant for SC/Nav-Buddhist BPL families (state top-up to PMAY)", hi: "SC/नव-बौद्ध BPL परिवारों को ₹1.20 लाख आवास अनुदान" },
    tag:     { en: "Housing / SC", hi: "आवास / SC" },
    annual: 120000,
    apply:   { en: "rhgrhay.maharashtra.gov.in", hi: "rhgrhay.maharashtra.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "SC / Nav-Buddhist Caste Certificate", "BPL Certificate", "7/12 Land Extract or Plot Allotment Letter", "Bank Passbook"],
               hi: ["आधार कार्ड", "SC/नव-बौद्ध जाति प्रमाण पत्र", "BPL प्रमाण पत्र", "7/12 उतारा या भूखंड आवंटन पत्र", "बैंक पासबुक"] },
    match: (a) => a.state === "Maharashtra" && ["no","kutcha"].includes(a.house) && ["below1","1to3"].includes(a.income),
  },

  {
    id: "maha_sanjay_gandhi",
    icon: "👴", color: "#D97706", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Social Justice & Special Assistance Dept.", hi: "महाराष्ट्र सामाजिक न्याय व विशेष सहाय्य विभाग" },
    name:    { en: "Sanjay Gandhi Niradhar Anudan Yojana",            hi: "संजय गांधी निराधार अनुदान योजना" },
    benefit: { en: "₹600/month pension for destitute, disabled, widows & orphans not covered by other pensions", hi: "अन्य पेंशन से वंचित असहाय, विकलांग, विधवा व अनाथों को ₹600/माह" },
    tag:     { en: "Pension / Senior", hi: "पेंशन / वरिष्ठ" },
    annual: 7200,
    apply:   { en: "aaplesarkar.mahaonline.gov.in", hi: "aaplesarkar.mahaonline.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Income Certificate (≤₹21,000/year)", "Disability / Widow / Destitute Proof", "Bank Passbook", "Maharashtra Domicile"],
               hi: ["आधार कार्ड", "आय प्रमाण (≤₹21,000/वर्ष)", "विकलांगता/विधवा/निराधार प्रमाण", "बैंक पासबुक", "महाराष्ट्र अधिवास प्रमाण"] },
    match: (a) => a.state === "Maharashtra" && ["below1"].includes(a.income) && (a.who === "senior" || a.who === "women" || a.age === "above60"),
  },

  {
    id: "maha_shravan_bal",
    icon: "🧓", color: "#92400E", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Social Justice Dept.", hi: "महाराष्ट्र सामाजिक न्याय विभाग" },
    name:    { en: "Shravan Bal Seva Rajya Pension Yojana",           hi: "श्रवण बाळ सेवा राज्य निवृत्ती वेतन योजना" },
    benefit: { en: "₹600/month state pension for senior citizens (65+) not covered by IGNOAPS", hi: "IGNOAPS से वंचित 65+ वरिष्ठ नागरिकों को ₹600/माह राज्य पेंशन" },
    tag:     { en: "Senior / Pension", hi: "वरिष्ठ / पेंशन" },
    annual: 7200,
    apply:   { en: "aaplesarkar.mahaonline.gov.in", hi: "aaplesarkar.mahaonline.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Age Proof (65+)", "Income Certificate", "Bank Passbook", "Maharashtra Domicile (15+ years)"],
               hi: ["आधार कार्ड", "आयु प्रमाण (65+)", "आय प्रमाण पत्र", "बैंक पासबुक", "महाराष्ट्र अधिवास (15+ वर्ष)"] },
    match: (a) => a.state === "Maharashtra" && (a.who === "senior" || a.age === "above60") && ["below1","1to3"].includes(a.income),
  },

  {
    id: "maha_yellow_ration",
    icon: "🍚", color: "#CA8A04", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Food, Civil Supplies & Consumer Protection Dept.", hi: "महाराष्ट्र अन्न, नागरी पुरवठा व ग्राहक संरक्षण विभाग" },
    name:    { en: "Maharashtra Yellow Ration Card Scheme",           hi: "महाराष्ट्र पीला राशन कार्ड योजना" },
    benefit: { en: "Subsidised grain (35 kg/family/month) at ₹1–₹3/kg + free LPG connection eligibility", hi: "35 किलो अनाज/माह ₹1–₹3/किलो + मुफ्त LPG कनेक्शन पात्रता" },
    tag:     { en: "Food Security", hi: "खाद्य सुरक्षा" },
    annual: 5040,
    apply:   { en: "rcms.mahafood.gov.in", hi: "rcms.mahafood.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Income Certificate (BPL / ≤₹15,000/month)", "Address Proof", "Family Photo"],
               hi: ["आधार कार्ड", "आय प्रमाण (BPL / ≤₹15,000/माह)", "पता प्रमाण", "पारिवारिक फोटो"] },
    match: (a) => a.state === "Maharashtra" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "maha_yuva_karya",
    icon: "💼", color: "#0F766E", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Skill Development Dept.", hi: "महाराष्ट्र कौशल विकास विभाग" },
    name:    { en: "Mahaswayam – Yuva Karya Prashikshan Yojana",     hi: "महास्वयं – युवा कार्य प्रशिक्षण योजना" },
    benefit: { en: "Free skill training + ₹2,000–₹5,000/month stipend during apprenticeship for youth", hi: "युवाओं को मुफ्त कौशल प्रशिक्षण + अप्रेंटिसशिप में ₹2,000–₹5,000/माह" },
    tag:     { en: "Skill / Youth", hi: "कौशल / युवा" },
    annual: 60000,
    apply:   { en: "mahaswayam.gov.in", hi: "mahaswayam.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Educational Certificate (Min. SSC)", "Maharashtra Domicile", "Bank Passbook", "Passport Photo"],
               hi: ["आधार कार्ड", "शैक्षणिक प्रमाण (न्यूनतम SSC)", "महाराष्ट्र अधिवास प्रमाण", "बैंक पासबुक", "पासपोर्ट फोटो"] },
    match: (a) => a.state === "Maharashtra" && ["18to35"].includes(a.age) && ["below1","1to3","3to6"].includes(a.income),
  },

  // ── Disability ───────────────────────────────────────────────────────────────

  {
    id: "maha_divyang_pension",
    icon: "♿", color: "#6B21A8", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Social Justice & Special Assistance Dept.", hi: "महाराष्ट्र सामाजिक न्याय व विशेष सहाय्य विभाग" },
    name:    { en: "Indira Gandhi National Disability Pension (Maha Top-up)",  hi: "इंदिरा गांधी राष्ट्रीय दिव्यांग पेंशन (महाराष्ट्र टॉप-अप)" },
    benefit: { en: "₹600/month state pension for persons with 80%+ disability (BPL)", hi: "80%+ दिव्यांग BPL व्यक्तियों को ₹600/माह राज्य पेंशन" },
    tag:     { en: "Disability / Pension", hi: "दिव्यांग / पेंशन" },
    annual: 7200,
    apply:   { en: "aaplesarkar.mahaonline.gov.in", hi: "aaplesarkar.mahaonline.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Disability Certificate (80%+, from Civil Surgeon)", "BPL / Income Certificate", "Bank Passbook", "Maharashtra Domicile"],
               hi: ["आधार कार्ड", "दिव्यांगता प्रमाण पत्र (80%+, सिविल सर्जन से)", "BPL/आय प्रमाण", "बैंक पासबुक", "महाराष्ट्र अधिवास प्रमाण"] },
    match: (a) => a.state === "Maharashtra" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "maha_divyang_vehicle",
    icon: "🛵", color: "#7C3AED", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Social Justice Dept.", hi: "महाराष्ट्र सामाजिक न्याय विभाग" },
    name:    { en: "Divyang Motorised Tricycle / Assistive Device Scheme",     hi: "दिव्यांग मोटराइज्ड ट्रायसिकल / सहाय्यक उपकरण योजना" },
    benefit: { en: "Free motorised tricycle or assistive device (up to ₹45,000) for physically disabled persons", hi: "शारीरिक दिव्यांग व्यक्तियों को मुफ्त मोटराइज्ड ट्रायसिकल या ₹45,000 तक उपकरण" },
    tag:     { en: "Disability / Assistive Aid", hi: "दिव्यांग / सहाय्यक उपकरण" },
    annual: 45000,
    apply:   { en: "sjsa.maharashtra.gov.in", hi: "sjsa.maharashtra.gov.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "Disability Certificate (40%+)", "Income Certificate (≤₹3L/year)", "Passport Photo", "Bank Passbook"],
               hi: ["आधार कार्ड", "दिव्यांगता प्रमाण पत्र (40%+)", "आय प्रमाण (≤₹3 लाख/वर्ष)", "पासपोर्ट फोटो", "बैंक पासबुक"] },
    match: (a) => a.state === "Maharashtra" && ["below1","1to3","3to6"].includes(a.income),
  },

  // ── Tribal / Adivasi ─────────────────────────────────────────────────────────

  {
    id: "maha_tribal_ashram",
    icon: "🏫", color: "#78350F", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Tribal Development Dept.", hi: "महाराष्ट्र आदिवासी विकास विभाग" },
    name:    { en: "Ashram School Scheme (ST Students)",                       hi: "आश्रमशाळा योजना (ST विद्यार्थी)" },
    benefit: { en: "Free residential schooling + food, clothing & books for ST children (Class 1–12)", hi: "ST बच्चों को कक्षा 1–12 तक मुफ्त निवासी शिक्षा, भोजन, वस्त्र व पुस्तकें" },
    tag:     { en: "Student / Tribal / ST", hi: "छात्र / आदिवासी / ST" },
    annual: 30000,
    apply:   { en: "tribal.maharashtra.gov.in", hi: "tribal.maharashtra.gov.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "ST Caste Certificate", "Birth Certificate", "Previous School Leaving Certificate", "Parent's Income Certificate"],
               hi: ["आधार कार्ड", "ST जाति प्रमाण पत्र", "जन्म प्रमाण पत्र", "पिछली शाला छोड़ने का प्रमाण", "माता-पिता का आय प्रमाण"] },
    match: (a) => a.state === "Maharashtra" && a.who === "student" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "maha_tribal_scholarship",
    icon: "🎓", color: "#92400E", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Tribal Development Dept.", hi: "महाराष्ट्र आदिवासी विकास विभाग" },
    name:    { en: "Post-Matric Scholarship for ST Students (Maharashtra)",    hi: "मॅट्रिकोत्तर छात्रवृत्ती योजना (ST, महाराष्ट्र)" },
    benefit: { en: "Full tuition fee + ₹380–₹1,200/month maintenance allowance for ST students in college", hi: "ST कॉलेज छात्रों को पूरी ट्यूशन फीस + ₹380–₹1,200/माह भत्ता" },
    tag:     { en: "Student / Tribal / ST", hi: "छात्र / आदिवासी / ST" },
    annual: 14400,
    apply:   { en: "mahadbt.gov.in", hi: "mahadbt.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "ST Caste Certificate", "Income Certificate (≤₹2.5L/year)", "Previous Year Mark Sheet", "College Fee Receipt", "Bank Passbook"],
               hi: ["आधार कार्ड", "ST जाति प्रमाण पत्र", "आय प्रमाण (≤₹2.5 लाख/वर्ष)", "पिछले वर्ष की मार्कशीट", "कॉलेज शुल्क रसीद", "बैंक पासबुक"] },
    match: (a) => a.state === "Maharashtra" && a.who === "student" && ["below1","1to3"].includes(a.income),
  },

  // ── Women – Self-Employment & Safety ─────────────────────────────────────────

  {
    id: "maha_mahila_arthik",
    icon: "👩‍💼", color: "#BE185D", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Women & Child Development Dept.", hi: "महाराष्ट्र महिला व बाल विकास विभाग" },
    name:    { en: "Mahila Arthik Vikas Mahamandal (MAVIM) Loan",             hi: "महिला आर्थिक विकास महामंडळ (MAVIM) लोन" },
    benefit: { en: "Low-interest loan ₹1–₹5 Lakh through SHG for women entrepreneurs", hi: "SHG के माध्यम से महिला उद्यमियों को ₹1–₹5 लाख कम ब्याज लोन" },
    tag:     { en: "Women / Business / SHG", hi: "महिला / व्यापार / SHG" },
    annual: 0,
    apply:   { en: "mavim.org.in", hi: "mavim.org.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "SHG Membership Certificate", "Business Plan", "Income Certificate", "Bank Passbook (SHG account)"],
               hi: ["आधार कार्ड", "SHG सदस्यता प्रमाण पत्र", "व्यापार योजना", "आय प्रमाण", "बैंक पासबुक (SHG खाता)"] },
    match: (a) => a.state === "Maharashtra" && a.who === "women" && ["below1","1to3","3to6"].includes(a.income),
  },

  {
    id: "maha_manodairya",
    icon: "🆘", color: "#DC2626", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Women & Child Development Dept.", hi: "महाराष्ट्र महिला व बाल विकास विभाग" },
    name:    { en: "Manodhairya Scheme (Rape / Acid Attack Survivors)",        hi: "मनोधैर्य योजना (बलात्कार / एसिड हमले की पीड़िता)" },
    benefit: { en: "Immediate compensation ₹3 Lakh (rape) / ₹5 Lakh (acid attack) + free medical & legal aid", hi: "बलात्कार पीड़िता को ₹3 लाख / एसिड हमले पर ₹5 लाख तत्काल मुआवजा + मुफ्त चिकित्सा व कानूनी सहायता" },
    tag:     { en: "Women / Safety / Relief", hi: "महिला / सुरक्षा / राहत" },
    annual: 300000,
    apply:   { en: "District Legal Services Authority (DLSA) / nearest police station", hi: "जिला कानूनी सेवा प्राधिकरण (DLSA) / नजदीकी पुलिस थाना" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "FIR / Medico-Legal Case (MLC) Report", "Medical Treatment Records", "Bank Passbook"],
               hi: ["आधार कार्ड", "FIR / MLC रिपोर्ट", "चिकित्सा उपचार रिकॉर्ड", "बैंक पासबुक"] },
    match: (a) => a.state === "Maharashtra" && a.who === "women",
  },

  // ── Farmer – Additional ───────────────────────────────────────────────────────

  {
    id: "maha_gopinath_munde",
    icon: "🚜", color: "#15803D", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Agriculture Dept.", hi: "महाराष्ट्र कृषि विभाग" },
    name:    { en: "Gopinath Munde Shetkari Apghat Vima Yojana",              hi: "गोपीनाथ मुंडे शेतकरी अपघात विमा योजना" },
    benefit: { en: "₹2 Lakh accidental death insurance + ₹1 Lakh partial disability cover for all registered farmers", hi: "सभी पंजीकृत किसानों को ₹2 लाख आकस्मिक मृत्यु बीमा + ₹1 लाख आंशिक दिव्यांगता कवर" },
    tag:     { en: "Farmer / Insurance", hi: "किसान / बीमा" },
    annual: 0,
    apply:   { en: "krishi.maharashtra.gov.in", hi: "krishi.maharashtra.gov.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "7/12 Land Extract (in farmer's name)", "Bank Passbook", "Nominee's Aadhaar (for death claim)"],
               hi: ["आधार कार्ड", "7/12 उतारा (किसान के नाम)", "बैंक पासबुक", "नॉमिनी का आधार (मृत्यु दावे के लिए)"] },
    match: (a) => a.state === "Maharashtra" && a.who === "farmer",
  },

  {
    id: "maha_nanaji_deshmukh",
    icon: "🌱", color: "#16A34A", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Agriculture & Horticulture Dept.", hi: "महाराष्ट्र कृषि व फलोत्पादन विभाग" },
    name:    { en: "Nanaji Deshmukh Krishi Sanjivani Prakalp (PoCRA)",        hi: "नानाजी देशमुख कृषि संजीवनी प्रकल्प (PoCRA)" },
    benefit: { en: "Subsidy up to 50% on climate-resilient farming inputs, farm ponds & micro-irrigation for drought-prone villages", hi: "सूखाग्रस्त गांवों में जलवायु-अनुकूल खेती इनपुट, फार्म पॉन्ड व सूक्ष्म सिंचाई पर 50% तक सब्सिडी" },
    tag:     { en: "Farmer / Climate Resilience", hi: "किसान / जलवायु अनुकूलन" },
    annual: 25000,
    apply:   { en: "pocramaharashtra.gov.in", hi: "pocramaharashtra.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "7/12 Land Extract", "Soil & Water Test Report", "Bank Passbook", "Village Inclusion Certificate (PoCRA village list)"],
               hi: ["आधार कार्ड", "7/12 उतारा", "मिट्टी व पानी जांच रिपोर्ट", "बैंक पासबुक", "ग्राम समावेश प्रमाण (PoCRA ग्राम सूची)"] },
    match: (a) => a.state === "Maharashtra" && a.who === "farmer" && ["below1","1to3","3to6"].includes(a.income),
  },

  // ── Urban Poor / Employment ───────────────────────────────────────────────────

  {
    id: "maha_pmay_slum",
    icon: "🏙️", color: "#0369A1", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Housing & Area Development Authority (MHADA)", hi: "महाराष्ट्र गृहनिर्माण व क्षेत्र विकास प्राधिकरण (MHADA)" },
    name:    { en: "MHADA Slum Rehabilitation Scheme (SRA)",                  hi: "MHADA झोपडपट्टी पुनर्वास योजना (SRA)" },
    benefit: { en: "Free permanent pucca house (269 sq ft carpet) for eligible slum dwellers in Maharashtra", hi: "पात्र झुग्गीवासियों को मुफ्त पक्का मकान (269 वर्ग फुट कार्पेट)" },
    tag:     { en: "Housing / Urban Poor", hi: "आवास / शहरी गरीब" },
    annual: 500000,
    apply:   { en: "sra.gov.in", hi: "sra.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Slum Identity Card / Electoral Roll (pre-2000 residence proof)", "Ration Card", "Passport Photo", "Bank Passbook"],
               hi: ["आधार कार्ड", "स्लम पहचान पत्र / मतदाता सूची (2000 से पहले निवास प्रमाण)", "राशन कार्ड", "पासपोर्ट फोटो", "बैंक पासबुक"] },
    match: (a) => a.state === "Maharashtra" && ["no","kutcha"].includes(a.house) && ["urban","semi"].includes(a.area) && ["below1","1to3"].includes(a.income),
  },

  {
    id: "maha_rojgar_hami",
    icon: "⛏️", color: "#78350F", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Employment Guarantee Dept.", hi: "महाराष्ट्र रोजगार हमी विभाग" },
    name:    { en: "Maharashtra Employment Guarantee Scheme (EGS)",           hi: "महाराष्ट्र रोजगार हमी योजना (EGS)" },
    benefit: { en: "Guaranteed 365-day unskilled employment @ ₹309/day for rural job-seekers (pre-dates MGNREGA)", hi: "ग्रामीण बेरोजगारों को ₹309/दिन पर 365 दिन गारंटीड रोजगार" },
    tag:     { en: "Employment / Rural", hi: "रोजगार / ग्रामीण" },
    annual: 37000,
    apply:   { en: "egs.mahaonline.gov.in", hi: "egs.mahaonline.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Maharashtra Domicile", "Job Card (from Gram Panchayat)", "Bank / Post Office Account"],
               hi: ["आधार कार्ड", "महाराष्ट्र अधिवास", "जॉब कार्ड (ग्राम पंचायत से)", "बैंक / डाकघर खाता"] },
    match: (a) => a.state === "Maharashtra" && a.area === "rural" && ["below1","1to3"].includes(a.income),
  },

  // ── Minority ─────────────────────────────────────────────────────────────────

  {
    id: "maha_minority_scholarship",
    icon: "🕌", color: "#0F766E", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Minority Development Dept.", hi: "महाराष्ट्र अल्पसंख्यक विकास विभाग" },
    name:    { en: "Maharashtra Minority Post-Matric Scholarship",             hi: "महाराष्ट्र अल्पसंख्यक मॅट्रिकोत्तर छात्रवृत्ती" },
    benefit: { en: "₹10,000–₹20,000/year scholarship for Muslim, Christian, Buddhist, Sikh, Jain & Parsi students in higher education", hi: "मुस्लिम, ईसाई, बौद्ध, सिख, जैन व पारसी छात्रों को उच्च शिक्षा में ₹10,000–₹20,000/वर्ष छात्रवृत्ती" },
    tag:     { en: "Student / Minority", hi: "छात्र / अल्पसंख्यक" },
    annual: 20000,
    apply:   { en: "mahadbt.gov.in", hi: "mahadbt.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Minority Community Certificate", "Income Certificate (≤₹8L/year)", "Previous Year Mark Sheet", "College Bonafide", "Bank Passbook"],
               hi: ["आधार कार्ड", "अल्पसंख्यक समुदाय प्रमाण पत्र", "आय प्रमाण (≤₹8 लाख/वर्ष)", "पिछले वर्ष की मार्कशीट", "कॉलेज बोनाफाइड", "बैंक पासबुक"] },
    match: (a) => a.state === "Maharashtra" && a.who === "student" && ["below1","1to3","3to6"].includes(a.income),
  },

  // ── NEW / LATEST SCHEMES (2024–2026) ─────────────────────────────────────────

  {
    id: "maha_karjmafi_2026",
    icon: "🏦", color: "#15803D", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Finance & Co-operation Dept.", hi: "महाराष्ट्र वित्त व सहकार विभाग" },
    name:    { en: "Punyashlok Ahilyadevi Holkar Shetkari Karjmafi Yojana (2026)", hi: "पुण्यश्लोक अहिल्यादेवी होळकर शेतकरी कर्जमाफी योजना (2026)" },
    benefit: { en: "Complete crop loan waiver up to ₹2 Lakh for defaulting farmers (loans Apr 2019–Mar 2025, overdue as of Sep 2025) + ₹50,000 incentive for regular repayers", hi: "अप्रैल 2019–मार्च 2025 के बकाया फसल लोन पर ₹2 लाख तक पूर्ण कर्जमाफी + नियमित चुकाने वाले किसानों को ₹50,000 प्रोत्साहन" },
    tag:     { en: "Farmer / Loan Waiver", hi: "किसान / कर्जमाफी" },
    annual: 200000,
    apply:   { en: "krishi.maharashtra.gov.in", hi: "krishi.maharashtra.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Farmer Registry Registration Number", "Crop Loan Account Details (Bank Passbook)", "7/12 Land Extract", "Mobile Number (Aadhaar-linked)"],
               hi: ["आधार कार्ड", "शेतकरी नोंदणी क्रमांक", "फसल लोन खाता विवरण (बैंक पासबुक)", "7/12 उतारा", "मोबाइल नंबर (आधार से लिंक)"] },
    match: (a) => a.state === "Maharashtra" && a.who === "farmer",
  },

  {
    id: "maha_namo_shetkari",
    icon: "🌾", color: "#16A34A", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Agriculture Dept.", hi: "महाराष्ट्र कृषि विभाग" },
    name:    { en: "Namo Shetkari Maha Samman Nidhi Yojana",                   hi: "नमो शेतकरी महासन्मान निधी योजना" },
    benefit: { en: "₹6,000/year additional state top-up (₹2,000 × 3 instalments) on top of PM Kisan — total ₹12,000/year for eligible farmers", hi: "PM किसान के ऊपर राज्य से अतिरिक्त ₹6,000/वर्ष (₹2,000 × 3 किस्तें) — कुल ₹12,000/वर्ष" },
    tag:     { en: "Farmer / Income Support", hi: "किसान / आय सहायता" },
    annual: 6000,
    apply:   { en: "nsmny.mahait.org", hi: "nsmny.mahait.org" }, applyType: "online",
    docs:    { en: ["Aadhaar Card (Aadhaar-linked mobile)", "7/12 Land Extract", "PM Kisan Registration Number", "Bank Passbook"],
               hi: ["आधार कार्ड (मोबाइल लिंक)", "7/12 उतारा", "PM किसान पंजीकरण क्रमांक", "बैंक पासबुक"] },
    match: (a) => a.state === "Maharashtra" && a.who === "farmer",
  },

  {
    id: "maha_magel_tyala_solar_pump",
    icon: "☀️", color: "#CA8A04", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Energy Dept. / MSEDCL", hi: "महाराष्ट्र ऊर्जा विभाग / MSEDCL" },
    name:    { en: "Magel Tyala Saur Krushi Pump Yojana (Solar Irrigation Pump)", hi: "मागेल त्याला सौर कृषी पंप योजना" },
    benefit: { en: "90% subsidy (95% for SC/ST) on solar irrigation pump (3–7.5 HP) + 5-year repair guarantee & insurance. Farmer pays only 5–10%", hi: "सिंचाई सौर पंप (3–7.5 HP) पर 90% सब्सिडी (SC/ST को 95%) + 5 वर्ष मरम्मत गारंटी व बीमा। किसान केवल 5–10% भुगतान करे" },
    tag:     { en: "Farmer / Solar / Irrigation", hi: "किसान / सौर / सिंचाई" },
    annual: 90000,
    apply:   { en: "mahadiscom.in", hi: "mahadiscom.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "7/12 Land Extract", "Proof of Water Source (borewell/well/pond)", "Caste Certificate (SC/ST for extra subsidy)", "Bank Passbook", "Passport Photo"],
               hi: ["आधार कार्ड", "7/12 उतारा", "जल स्रोत का प्रमाण (बोरवेल/कुआं/तालाब)", "जाति प्रमाण (SC/ST अतिरिक्त सब्सिडी हेतु)", "बैंक पासबुक", "पासपोर्ट फोटो"] },
    match: (a) => a.state === "Maharashtra" && a.who === "farmer",
  },

  {
    id: "maha_smart_solar",
    icon: "🔆", color: "#F59E0B", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Energy Dept. / MSEDCL", hi: "महाराष्ट्र ऊर्जा विभाग / MSEDCL" },
    name:    { en: "Maharashtra SMART Solar Scheme 2025 (Rooftop Solar)",       hi: "महाराष्ट्र SMART सोलर योजना 2025 (रूफटॉप सोलर)" },
    benefit: { en: "Up to 95% subsidy on 1 kW rooftop solar panel (BPL pays only ₹2,500 for a ₹50,000 system) generating ~120 units/month free electricity", hi: "BPL परिवारों को 1 kW रूफटॉप सोलर पर 95% सब्सिडी — ₹50,000 के सिस्टम पर केवल ₹2,500 भुगतान, हर माह ~120 यूनिट मुफ्त बिजली" },
    tag:     { en: "Solar / Energy / BPL", hi: "सोलर / ऊर्जा / BPL" },
    annual: 12000,
    apply:   { en: "msedcl.in / mahadiscom.in", hi: "msedcl.in / mahadiscom.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Electricity Bill (consumer number)", "Yellow / Saffron Ration Card (for BPL subsidy)", "Bank Passbook", "Roof Ownership Proof or NOC from owner"],
               hi: ["आधार कार्ड", "बिजली बिल (उपभोक्ता क्रमांक)", "पीला/केसरी राशन कार्ड (BPL सब्सिडी हेतु)", "बैंक पासबुक", "छत स्वामित्व प्रमाण या NOC"] },
    match: (a) => a.state === "Maharashtra" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "maha_annapurna_lpg",
    icon: "🔥", color: "#EA580C", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Food, Civil Supplies & Consumer Protection Dept.", hi: "महाराष्ट्र अन्न, नागरी पुरवठा व ग्राहक संरक्षण विभाग" },
    name:    { en: "Mukhyamantri Annapurna Yojana (Free LPG Cylinders)",        hi: "मुख्यमंत्री अन्नपूर्णा योजना (मुफ्त LPG सिलेंडर)" },
    benefit: { en: "3 free LPG cylinders per year for families holding yellow or saffron ration cards (~52 lakh families covered)", hi: "पीला या केसरी राशन कार्ड धारक परिवारों को प्रतिवर्ष 3 मुफ्त LPG सिलेंडर (~52 लाख परिवार)" },
    tag:     { en: "LPG / Women / BPL", hi: "LPG / महिला / BPL" },
    annual: 2400,
    apply:   { en: "mahafood.gov.in", hi: "mahafood.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Yellow / Saffron Ration Card", "LPG Connection Details (existing connection)", "Bank Passbook"],
               hi: ["आधार कार्ड", "पीला/केसरी राशन कार्ड", "LPG कनेक्शन विवरण (मौजूदा कनेक्शन)", "बैंक पासबुक"] },
    match: (a) => a.state === "Maharashtra" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "maha_one_rupee_fasal_bima",
    icon: "🌧️", color: "#0369A1", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Agriculture Dept.", hi: "महाराष्ट्र कृषि विभाग" },
    name:    { en: "One Rupee Crop Insurance Scheme (Maharashtra)",             hi: "एक रुपया पीक विमा योजना (महाराष्ट्र)" },
    benefit: { en: "Full PMFBY crop insurance coverage at just ₹1 premium — state pays entire farmer's share of premium", hi: "केवल ₹1 प्रीमियम पर पूर्ण PMFBY फसल बीमा — किसान के हिस्से का पूरा प्रीमियम राज्य सरकार भरती है" },
    tag:     { en: "Farmer / Crop Insurance", hi: "किसान / फसल बीमा" },
    annual: 0,
    apply:   { en: "aaplesarkar.mahaonline.gov.in / nearest bank or CSC", hi: "aaplesarkar.mahaonline.gov.in / नजदीकी बैंक या CSC" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "7/12 Land Extract", "Sowing Certificate", "Bank Passbook", "₹1 payment receipt"],
               hi: ["आधार कार्ड", "7/12 उतारा", "बुवाई प्रमाण पत्र", "बैंक पासबुक", "₹1 भुगतान रसीद"] },
    match: (a) => a.state === "Maharashtra" && a.who === "farmer",
  },

  {
    id: "maha_ahilyadevi_mahila_startup",
    icon: "🚀", color: "#7C3AED", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Women & Child Development Dept.", hi: "महाराष्ट्र महिला व बाल विकास विभाग" },
    name:    { en: "Punyashlok Ahilya Devi Holkar Mahila Startup Yojana",       hi: "पुण्यश्लोक अहिल्यादेवी होळकर महिला स्टार्टअप योजना" },
    benefit: { en: "Seed funding ₹25 Lakh + incubation & mentorship support for women-led startups in Maharashtra", hi: "महाराष्ट्र की महिला नेतृत्व वाली स्टार्टअप को ₹25 लाख सीड फंडिंग + इनक्यूबेशन व मार्गदर्शन" },
    tag:     { en: "Women / Startup / Business", hi: "महिला / स्टार्टअप / व्यापार" },
    annual: 0,
    apply:   { en: "wcd.maharashtra.gov.in", hi: "wcd.maharashtra.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Business / Startup Registration Certificate", "Pitch Deck / Business Plan", "Bank Account", "Maharashtra Domicile", "Incorporation / GST Certificate (if applicable)"],
               hi: ["आधार कार्ड", "व्यापार/स्टार्टअप पंजीकरण प्रमाण पत्र", "पिच डेक/व्यापार योजना", "बैंक खाता", "महाराष्ट्र अधिवास", "निगमन/GST प्रमाण (यदि लागू)"] },
    match: (a) => a.state === "Maharashtra" && a.who === "women" && (a.who === "business" || ["18to35","35to60"].includes(a.age)),
  },

  {
    id: "maha_mukhyamantri_vaidyakiya",
    icon: "🏥", color: "#0891B2", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Medical Education & Drugs Dept.", hi: "महाराष्ट्र वैद्यकीय शिक्षण व औषध विभाग" },
    name:    { en: "Mukhyamantri Vaidyakiya Sahayata Nidhi (CM Medical Relief Fund)", hi: "मुख्यमंत्री वैद्यकीय सहायता निधी" },
    benefit: { en: "Up to ₹5 Lakh financial assistance for catastrophic illness (cancer, organ transplant, rare diseases) for APL/BPL families not covered under MJPJAY/Ayushman", hi: "MJPJAY/आयुष्मान से वंचित APL/BPL परिवारों को कैंसर, अंग प्रत्यारोपण, दुर्लभ रोग पर ₹5 लाख तक वित्तीय सहायता" },
    tag:     { en: "Health / Medical Relief", hi: "स्वास्थ्य / चिकित्सा राहत" },
    annual: 500000,
    apply:   { en: "Apply via Dean/Medical Superintendent of Govt. Hospital", hi: "सरकारी अस्पताल के डीन/मेडिकल सुपरिंटेंडेंट के माध्यम से आवेदन करें" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "Medical Certificate & Estimated Cost from treating hospital", "Income Certificate", "Ration Card", "Bank Passbook"],
               hi: ["आधार कार्ड", "उपचार अस्पताल का मेडिकल सर्टिफिकेट व अनुमानित लागत", "आय प्रमाण पत्र", "राशन कार्ड", "बैंक पासबुक"] },
    match: (a) => a.state === "Maharashtra" && ["below1","1to3","3to6"].includes(a.income),
  },

  {
    id: "maha_gems_jewellery_skill",
    icon: "💎", color: "#BE185D", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Skills, Employment, Entrepreneurship & Innovation Dept.", hi: "महाराष्ट्र कौशल, रोजगार, उद्योजकता व नवोपक्रम विभाग" },
    name:    { en: "Certificate Course in Gems & Jewellery Sector (Maharashtra 2025)", hi: "रत्न व आभूषण क्षेत्र प्रमाणपत्र अभ्यासक्रम (महाराष्ट्र 2025)" },
    benefit: { en: "Free 3–6 month certified skill training in gems, jewellery design & manufacturing at Maharashtra State Skills University centres", hi: "महाराष्ट्र राज्य कौशल विद्यापीठ केंद्रों पर रत्न, आभूषण डिजाइन व निर्माण में 3–6 माह मुफ्त प्रमाणित प्रशिक्षण" },
    tag:     { en: "Skill / Youth / Artisan", hi: "कौशल / युवा / कारीगर" },
    annual: 30000,
    apply:   { en: "mss.edu.in (Maharashtra State Skills University)", hi: "mss.edu.in (महाराष्ट्र राज्य कौशल विद्यापीठ)" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "SSC / 10th Pass Certificate (min.)", "Maharashtra Domicile", "Passport Photo", "Bank Passbook"],
               hi: ["आधार कार्ड", "SSC / 10वीं पास प्रमाण पत्र (न्यूनतम)", "महाराष्ट्र अधिवास", "पासपोर्ट फोटो", "बैंक पासबुक"] },
    match: (a) => a.state === "Maharashtra" && ["18to35","35to60"].includes(a.age) && ["below1","1to3","3to6"].includes(a.income),
  },

  {
    id: "maha_mukhyamantri_saur_krishi_vahini",
    icon: "⚡", color: "#16A34A", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Energy Dept. / MSEDCL", hi: "महाराष्ट्र ऊर्जा विभाग / MSEDCL" },
    name:    { en: "Mukhyamantri Solar Krishi Vahini Yojana 2.0",              hi: "मुख्यमंत्री सौर कृषी वाहिनी योजना 2.0" },
    benefit: { en: "Daytime solar-powered agricultural electricity to farmers — eliminates night-time load shedding for irrigation; 119+ solar feeders commissioned (147 MW)", hi: "किसानों को दिन के समय सौर ऊर्जा से कृषि बिजली — सिंचाई के लिए रात की लोड शेडिंग समाप्त; 119+ सौर फीडर चालू (147 MW)" },
    tag:     { en: "Farmer / Solar / Electricity", hi: "किसान / सौर / बिजली" },
    annual: 15000,
    apply:   { en: "msedcl.in / agri feeder solarisation portal", hi: "msedcl.in / कृषि फीडर सोलराइजेशन पोर्टल" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "7/12 Land Extract", "Agricultural Electricity Connection Number (meter details)", "Bank Passbook"],
               hi: ["आधार कार्ड", "7/12 उतारा", "कृषि बिजली कनेक्शन क्रमांक (मीटर विवरण)", "बैंक पासबुक"] },
    match: (a) => a.state === "Maharashtra" && a.who === "farmer" && a.area === "rural",
  },

  // ── Construction Workers (MAHABOCW) ──────────────────────────────────────────

  {
    id: "maha_bandhkam_kamgar",
    icon: "🧱", color: "#78350F", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Building & Other Construction Workers Welfare Board (MAHABOCW)", hi: "महाराष्ट्र इमारत व इतर बांधकाम कामगार कल्याण मंडळ (MAHABOCW)" },
    name:    { en: "Bandhkam Kamgar Yojana – Construction Worker Welfare",      hi: "बांधकाम कामगार योजना – निर्माण कामगार कल्याण" },
    benefit: { en: "Bundle: ₹5L accidental death, ₹2L natural death, ₹15,000 maternity, ₹1L critical illness, ₹51,000 daughter marriage grant, ₹2,500–₹25,000/yr children scholarship, ₹10,000 tool grant, ₹2L housing aid", hi: "₹5L दुर्घटना मृत्यु, ₹2L स्वाभाविक मृत्यु, ₹15,000 मातृत्व, ₹1L गंभीर बीमारी, ₹51,000 बेटी विवाह, बच्चों की छात्रवृत्ति ₹2,500–₹25,000/वर्ष, ₹10,000 टूल अनुदान, ₹2L आवास सहायता" },
    tag:     { en: "Labour / Construction Worker", hi: "श्रमिक / बांधकाम कामगार" },
    annual: 15000,
    apply:   { en: "mahabocw.in", hi: "mahabocw.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Proof of 90 days construction work in last 12 months (employer certificate)", "Bank Passbook", "Passport Photo", "Age Proof", "Address Proof"],
               hi: ["आधार कार्ड", "पिछले 12 महीनों में 90 दिन बांधकाम कार्य प्रमाण (नियोक्ता प्रमाण पत्र)", "बैंक पासबुक", "पासपोर्ट फोटो", "आयु प्रमाण", "पता प्रमाण"] },
    match: (a) => a.state === "Maharashtra" && ["below1","1to3"].includes(a.income),
  },

  // ── Fishermen ────────────────────────────────────────────────────────────────

  {
    id: "maha_matsyavyavasay_vima",
    icon: "🎣", color: "#0369A1", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Fisheries Dept.", hi: "महाराष्ट्र मत्स्यव्यवसाय विभाग" },
    name:    { en: "Maharashtra Fishermen Group Accidental Insurance Scheme",   hi: "महाराष्ट्र मच्छीमार समूह अपघात विमा योजना" },
    benefit: { en: "₹5 Lakh accidental death + ₹2.5 Lakh partial disability insurance for registered marine/inland fishermen; state pays the premium", hi: "पंजीकृत समुद्री/अंतर्देशीय मच्छीमारों को ₹5 लाख दुर्घटना मृत्यु + ₹2.5 लाख आंशिक दिव्यांगता बीमा; प्रीमियम राज्य भरता है" },
    tag:     { en: "Fishermen / Insurance", hi: "मच्छीमार / बीमा" },
    annual: 0,
    apply:   { en: "fisheries.maharashtra.gov.in", hi: "fisheries.maharashtra.gov.in" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "Fishermen Identity Card / Registration Certificate", "Boat Registration Certificate (if applicable)", "Bank Passbook", "Passport Photo"],
               hi: ["आधार कार्ड", "मच्छीमार पहचान पत्र / पंजीकरण प्रमाण पत्र", "बोट पंजीकरण प्रमाण (यदि लागू)", "बैंक पासबुक", "पासपोर्ट फोटो"] },
    match: (a) => a.state === "Maharashtra" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "maha_matsya_vikas",
    icon: "🐟", color: "#0891B2", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Fisheries Dept. (under PMMSY)", hi: "महाराष्ट्र मत्स्यव्यवसाय विभाग (PMMSY अंतर्गत)" },
    name:    { en: "Maharashtra Fisheries Development Scheme (PMMSY State Component)", hi: "महाराष्ट्र मत्स्यव्यवसाय विकास योजना (PMMSY राज्य घटक)" },
    benefit: { en: "40–60% subsidy on fishing boats, nets, aquaculture ponds, ice plants & fish kiosks; SC/ST/women fishers get up to 60% subsidy", hi: "मछली नाव, जाल, जलकृषि तालाब, बर्फ संयंत्र व मछली कियोस्क पर 40–60% सब्सिडी; SC/ST/महिला को 60% तक" },
    tag:     { en: "Fishermen / Aquaculture", hi: "मच्छीमार / जलकृषि" },
    annual: 75000,
    apply:   { en: "pmmsy.dof.gov.in / fisheries.maharashtra.gov.in", hi: "pmmsy.dof.gov.in / fisheries.maharashtra.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Fishermen / Aquaculture Farmer Registration", "Project Report / Cost Estimate", "Land / Water Body Documents", "Bank Passbook", "Caste Certificate (SC/ST for higher subsidy)"],
               hi: ["आधार कार्ड", "मच्छीमार / जलकृषि किसान पंजीकरण", "परियोजना रिपोर्ट / लागत अनुमान", "भूमि / जलाशय दस्तावेज", "बैंक पासबुक", "जाति प्रमाण (SC/ST अधिक सब्सिडी हेतु)"] },
    match: (a) => a.state === "Maharashtra" && ["below1","1to3","3to6"].includes(a.income),
  },

  // ── Water Conservation ────────────────────────────────────────────────────────

  {
    id: "maha_jalyukt_shivar",
    icon: "💧", color: "#1D4ED8", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Water Conservation Dept.", hi: "महाराष्ट्र जलसंधारण विभाग" },
    name:    { en: "Jalyukt Shivar Abhiyan 2.0 (Drought-Free Village Programme)", hi: "जलयुक्त शिवार अभियान 2.0 (दुष्काळमुक्त गाव कार्यक्रम)" },
    benefit: { en: "Free water conservation works (farm ponds, check dams, canal deepening) for drought-prone villages — improves irrigation & groundwater recharge for farmers", hi: "दुष्काळग्रस्त गांवों में मुफ्त जल संरक्षण कार्य (शेततळे, साखळी बंधारे, कालवा खोलीकरण) — किसानों के लिए सिंचाई व भूजल पुनर्भरण" },
    tag:     { en: "Farmer / Water Conservation", hi: "किसान / जलसंधारण" },
    annual: 0,
    apply:   { en: "Gram Panchayat / Panchayat Samiti / District Water Conservation Office", hi: "ग्राम पंचायत / पंचायत समिती / जिला जलसंधारण कार्यालय" }, applyType: "offline",
    docs:    { en: ["Gram Panchayat Resolution", "Village Water Scarcity Report", "Land & Water Body Survey Map", "Aadhaar Card (applicant farmer)"],
               hi: ["ग्राम पंचायत ठराव", "गांव जल टंचाई रिपोर्ट", "भूमि व जलाशय सर्वे नक्शा", "आधार कार्ड (आवेदक किसान)"] },
    match: (a) => a.state === "Maharashtra" && a.who === "farmer" && a.area === "rural",
  },

  // ── Women – Girl Child & Marriage ─────────────────────────────────────────────

  {
    id: "maha_mazi_kanya_bhagyashree",
    icon: "👧", color: "#DB2777", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Women & Child Development Dept.", hi: "महाराष्ट्र महिला व बाल विकास विभाग" },
    name:    { en: "Mazi Kanya Bhagyashree Yojana",                             hi: "माझी कन्या भाग्यश्री योजना" },
    benefit: { en: "₹50,000 FD in girl's name at birth (family income ≤₹7.5L); interest paid for education at key milestones + ₹1L at age 18 for higher education or marriage", hi: "जन्म पर बालिका के नाम ₹50,000 FD (परिवार आय ≤₹7.5 लाख); शिक्षा हेतु समय-समय पर ब्याज + 18 वर्ष पर ₹1 लाख" },
    tag:     { en: "Women / Girl Child / Savings", hi: "महिला / बालिका / बचत" },
    annual: 0,
    apply:   { en: "womenchild.maharashtra.gov.in", hi: "womenchild.maharashtra.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card (parent)", "Girl Child's Birth Certificate", "Income Certificate (≤₹7.5L/year)", "Bank Account in girl's name", "Maharashtra Domicile", "Family Planning Certificate"],
               hi: ["आधार कार्ड (माता-पिता)", "बालिका का जन्म प्रमाण पत्र", "आय प्रमाण (≤₹7.5 लाख/वर्ष)", "बालिका के नाम बैंक खाता", "महाराष्ट्र अधिवास", "परिवार नियोजन प्रमाण पत्र"] },
    match: (a) => a.state === "Maharashtra" && a.who === "women" && ["below1","1to3","3to6"].includes(a.income),
  },

  {
    id: "maha_mukhyamantri_kanya_vivah",
    icon: "💍", color: "#9D174D", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Social Justice & Special Assistance Dept.", hi: "महाराष्ट्र सामाजिक न्याय व विशेष सहाय्य विभाग" },
    name:    { en: "Mukhyamantri Kanya Vivah Yojana (Mass Marriage Scheme)",    hi: "मुख्यमंत्री कन्या विवाह योजना (सामूहिक विवाह योजना)" },
    benefit: { en: "₹10,000 cash gift to bride + ₹2,000 household items for BPL families marrying daughters at government-organised mass marriage events", hi: "सरकारी सामूहिक विवाह कार्यक्रम के माध्यम से BPL परिवारों की बेटी की शादी पर ₹10,000 नकद + ₹2,000 गृहस्थी सामान" },
    tag:     { en: "Women / Marriage / BPL", hi: "महिला / विवाह / BPL" },
    annual: 12000,
    apply:   { en: "aaplesarkar.mahaonline.gov.in / District Social Welfare Office", hi: "aaplesarkar.mahaonline.gov.in / जिला समाज कल्याण कार्यालय" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card (bride & groom)", "BPL / Income Certificate", "Age Proof (bride min. 18, groom min. 21)", "Ration Card", "Bank Passbook (bride's name)", "Caste Certificate (SC/ST/OBC)"],
               hi: ["आधार कार्ड (वधू और वर)", "BPL / आय प्रमाण पत्र", "आयु प्रमाण (वधू न्यूनतम 18, वर न्यूनतम 21)", "राशन कार्ड", "बैंक पासबुक (वधू के नाम)", "जाति प्रमाण (SC/ST/OBC के लिए)"] },
    match: (a) => a.state === "Maharashtra" && a.who === "women" && ["below1","1to3"].includes(a.income),
  },

  // ── Education – Overseas & Professional ──────────────────────────────────────

  {
    id: "maha_ambedkar_overseas_scholarship",
    icon: "✈️", color: "#1D4ED8", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Social Justice Dept.", hi: "महाराष्ट्र सामाजिक न्याय विभाग" },
    name:    { en: "Dr. Babasaheb Ambedkar Overseas Scholarship (SC Students)", hi: "डॉ. बाबासाहेब आंबेडकर परदेशी शिष्यवृत्ती (SC विद्यार्थी)" },
    benefit: { en: "Full scholarship for SC students to study abroad — tuition + living + travel (up to ₹12 Lakh/year) for Master's / PhD at top global universities", hi: "SC छात्रों के विदेशी उच्च शिक्षा के लिए पूर्ण छात्रवृत्ति — ट्यूशन + जीवनयापन + यात्रा (₹12 लाख/वर्ष तक), मास्टर्स/PhD" },
    tag:     { en: "Student / SC / Overseas", hi: "छात्र / SC / विदेशी शिक्षा" },
    annual: 1200000,
    apply:   { en: "mahadbt.gov.in", hi: "mahadbt.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "SC Caste Certificate", "Income Certificate (family ≤₹6L/year)", "Admission Letter from QS Top-500 Foreign University", "Degree Marksheet (min. 60%)", "Bank Passbook", "Passport"],
               hi: ["आधार कार्ड", "SC जाति प्रमाण पत्र", "आय प्रमाण (परिवार ≤₹6 लाख/वर्ष)", "QS Top-500 विदेशी विश्वविद्यालय का प्रवेश पत्र", "डिग्री मार्कशीट (न्यूनतम 60%)", "बैंक पासबुक", "पासपोर्ट"] },
    match: (a) => a.state === "Maharashtra" && a.who === "student" && ["below1","1to3","3to6"].includes(a.income),
  },

  {
    id: "maha_women_professional_fee",
    icon: "🎓", color: "#4F46E5", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Higher & Technical Education Dept.", hi: "महाराष्ट्र उच्च व तंत्र शिक्षण विभाग" },
    name:    { en: "100% Fee Reimbursement for Women in Professional Courses",  hi: "महिला छात्रांसाठी व्यावसायिक अभ्यासक्रम 100% शुल्क परतावा" },
    benefit: { en: "Full tuition & exam fee reimbursement for women enrolled in engineering, medical, pharmacy, law, MBA & other professional courses (Budget 2025 announcement)", hi: "इंजीनियरिंग, मेडिकल, फार्मसी, कानून, MBA व अन्य व्यावसायिक पाठ्यक्रमों में नामांकित महिलाओं को 100% ट्यूशन व परीक्षा शुल्क वापसी (बजट 2025)" },
    tag:     { en: "Student / Women / Professional", hi: "छात्र / महिला / व्यावसायिक" },
    annual: 150000,
    apply:   { en: "mahadbt.gov.in", hi: "mahadbt.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "College Admission Letter & Fee Receipt", "Gender Certificate", "Income Certificate", "Maharashtra Domicile", "Previous Marksheet", "Bank Passbook"],
               hi: ["आधार कार्ड", "कॉलेज प्रवेश पत्र व शुल्क रसीद", "लिंग प्रमाण पत्र", "आय प्रमाण", "महाराष्ट्र अधिवास", "पिछले वर्ष की मार्कशीट", "बैंक पासबुक"] },
    match: (a) => a.state === "Maharashtra" && a.who === "women" && ["18to35"].includes(a.age),
  },

  // ── Poultry / Animal Husbandry ────────────────────────────────────────────────

  {
    id: "maha_kukut_palan_karj",
    icon: "🐔", color: "#B45309", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Animal Husbandry & Dairy Development Dept.", hi: "महाराष्ट्र पशुसंवर्धन व दुग्धव्यवसाय विभाग" },
    name:    { en: "Maharashtra Kukut Palan Karj Yojana (Poultry Farming Loan)", hi: "महाराष्ट्र कुक्कुटपालन कर्ज योजना" },
    benefit: { en: "Subsidised loan ₹1–₹10 Lakh at 4% interest to start or expand poultry farm; SC/ST/women/BPL get higher subsidy; NABARD-linked", hi: "कुक्कुटपालन शुरू या विस्तार हेतु 4% ब्याज पर ₹1–₹10 लाख लोन; SC/ST/महिला/BPL को अधिक सब्सिडी; NABARD से जुड़ा" },
    tag:     { en: "Farmer / Poultry / Animal Husbandry", hi: "किसान / कुक्कुटपालन / पशुसंवर्धन" },
    annual: 0,
    apply:   { en: "ahdmaharashtra.gov.in / nearest bank", hi: "ahdmaharashtra.gov.in / नजदीकी बैंक" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Land / Shed Ownership Proof", "Project Report (bird count, breed, feed plan)", "Bank Passbook", "Caste Certificate (SC/ST for higher subsidy)", "Income Certificate"],
               hi: ["आधार कार्ड", "जमीन/शेड स्वामित्व प्रमाण", "परियोजना रिपोर्ट (पक्षी संख्या, नस्ल, चारा योजना)", "बैंक पासबुक", "जाति प्रमाण (SC/ST अधिक सब्सिडी हेतु)", "आय प्रमाण पत्र"] },
    match: (a) => a.state === "Maharashtra" && a.who === "farmer" && ["below1","1to3","3to6"].includes(a.income),
  },

  // ── Sports ────────────────────────────────────────────────────────────────────

  {
    id: "maha_shiv_chhatrapati_sports",
    icon: "🏅", color: "#D97706", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Sports & Youth Welfare Dept.", hi: "महाराष्ट्र क्रीडा व युवक कल्याण विभाग" },
    name:    { en: "Shiv Chhatrapati Sports Award & Sports Nursery Scheme",     hi: "शिव छत्रपती क्रीडा पुरस्कार व क्रीडा रोपवाटिका योजना" },
    benefit: { en: "₹5 Lakh cash award + trophy for outstanding sportspersons + free coaching & kit under Sports Nursery Scheme for rural youth aged 8–19", hi: "उत्कृष्ट खिलाड़ियों को ₹5 लाख नकद + ट्रॉफी + क्रीडा रोपवाटिका के तहत 8–19 वर्ष ग्रामीण युवाओं को मुफ्त कोचिंग व किट" },
    tag:     { en: "Sports / Youth", hi: "क्रीडा / युवा" },
    annual: 500000,
    apply:   { en: "sports.maharashtra.gov.in", hi: "sports.maharashtra.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card", "Age Proof", "Sports Achievement Certificates (district/state/national level)", "Maharashtra Domicile", "Photo", "Bank Passbook", "NOC from School / Club"],
               hi: ["आधार कार्ड", "आयु प्रमाण", "खेल उपलब्धि प्रमाण पत्र (जिला/राज्य/राष्ट्रीय स्तर)", "महाराष्ट्र अधिवास", "फोटो", "बैंक पासबुक", "स्कूल/क्लब से NOC"] },
    match: (a) => a.state === "Maharashtra" && ["18to35","below18"].includes(a.age),
  },

  // ── Senior Citizens ────────────────────────────────────────────────────────────

  {
    id: "maha_senior_citizen_cooperation",
    icon: "🤝", color: "#92400E", scope: "state", state: "Maharashtra",
    ministry: { en: "Maharashtra Social Justice Dept.", hi: "महाराष्ट्र सामाजिक न्याय विभाग" },
    name:    { en: "Maharashtra Senior Citizens Cooperation Scheme (Vriddhashram & Welfare)", hi: "महाराष्ट्र ज्येष्ठ नागरिक सहयोग योजना (वृद्धाश्रम व कल्याण)" },
    benefit: { en: "Free / subsidised old-age home + legal aid + helpline (1800) for ~1.25 crore senior citizens; maintenance allowance for destitute seniors not covered by other pensions", hi: "~1.25 करोड़ वरिष्ठ नागरिकों के लिए मुफ्त/रियायती वृद्धाश्रम + कानूनी सहायता + हेल्पलाइन (1800); अन्य पेंशन से वंचित असहाय वरिष्ठों को भत्ता" },
    tag:     { en: "Senior / Old Age Care", hi: "वरिष्ठ / वृद्धसेवा" },
    annual: 7200,
    apply:   { en: "aaplesarkar.mahaonline.gov.in / District Social Welfare Office", hi: "aaplesarkar.mahaonline.gov.in / जिला समाज कल्याण कार्यालय" }, applyType: "offline",
    docs:    { en: ["Aadhaar Card", "Age Proof (60+)", "Income Certificate", "Maharashtra Domicile (15+ years)", "No Pension / Family Support Declaration", "Bank Passbook"],
               hi: ["आधार कार्ड", "आयु प्रमाण (60+)", "आय प्रमाण पत्र", "महाराष्ट्र अधिवास (15+ वर्ष)", "पेंशन/परिवार सहायता न होने का घोषणापत्र", "बैंक पासबुक"] },
    match: (a) => a.state === "Maharashtra" && (a.who === "senior" || a.age === "above60") && ["below1","1to3"].includes(a.income),
  },

  // ADD MORE MAHARASHTRA SCHEMES ABOVE THIS LINE ↓
  // {
  //   id: "maharashtra_new_scheme",
  //   icon: "🆕", color: "#123456", scope: "state", state: "Maharashtra",
  //   ministry: { en: "Dept. Name", hi: "विभाग का नाम" },
  //   name:    { en: "Scheme Name", hi: "योजना का नाम" },
  //   benefit: { en: "Benefit details", hi: "लाभ विवरण" },
  //   tag:     { en: "Tag", hi: "टैग" },
  //   annual: 0,
  //   apply:   { en: "website.gov.in", hi: "website.gov.in" }, applyType: "online",
  //   docs:    { en: ["Aadhaar Card"], hi: ["आधार कार्ड"] },
  //   match: (a) => a.state === "Maharashtra",
  // },

];
